### ISSUE TITLE
Add capturedAs<T>() helper?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#105]
Not high priority, but the unfortunate fact that [`captured`](https://github.com/dart-lang/mockito/blob/master/lib/src/mock.dart#L589) is a `List<dynamic>` does not play well with the Dart 2 concept of not-using-dynamic-as-bottom. For example:

```dart
cat.eatFood("Milk");
cat.eatFood("Fish");
expect(
    verify(cat.eatFood(captureAny)).captured.every((String s) => s.isNotEmpty), isTrue);
```

This code treats dynamic as bottom, by passing a `Function(String)` where a `Function(dynamic)` is expected. In Dart 2 you have `cast<T>()` and `retype<T>()` at your fingertips, so you can do:

```dart
expect(
    verify(cat.eatFood(captureAny))
        .captured
        .retype<String>()
        .every((String s) => s.isNotEmpty),
    isTrue);
```

which (again, not high priority) either adds a few characters to your statement, or a new line (or forces line wrapping). We could provide `capturedAs<T>()`:

```dart
expect(
    verify(cat.eatFood(captureAny))
        .capturedAs<String>()
        .every((String s) => s.isNotEmpty),
    isTrue);
```

One problem is how do you treat function invocations with multiple captured arguments...

**Comment by natebosch** [comment]
> One problem is how do you treat function invocations with multiple captured arguments...

Only 1 capture is probably a really common case, but it would be very unfortunate to need a completely different approach once you hit the case where you capture two arguments of different types. I think it would be better to solve that case and the single capture (or all captures of the same type) would work in a consistent way.

**Comment by matanlurey** [comment]
@srawlins Is this going to happen for Mockito 3? If not, do you either want to:

* Milestone it for Mockito 3.1 or Mockito 4
* Close the issue as not planned

**Comment by srawlins** [comment]
It's not going to happen for Mockito 3. I'm happy to leave it open for discussion, or give it "Milestone: later".

**Comment by srawlins** [comment]
We can play with this in Mockito's code-generated API that will be written at some point. It may look significantly different than what is proposed above, so I'll close this.
