### ISSUE TITLE
typed() doesn't work well with named parameters

### ISSUE THREAD

**Issue by robertoscaramuzzi** [dart-lang/mockito#106]
In order to transition to strong mode, we have been converting our `when()` and `verify()` calls from
`any` and `captureAny` to `typed(any) `and `typed(captureAny)`

However this doesn't work well with named parameters where

`when(... foo: any)` becomes `when(... foo: typed(any, named: 'foo'))`

Why does typed need to know the name of the parameter?
And the tests will break when the name of the parameter is refactored, which runs counter to one of the main advantages of Mockito compared to other mocking frameworks.

**Comment by matanlurey** [comment]
Closed as WAI for now.
