### ISSUE TITLE
Please consider release of non-alpha version of mockito for 3.0.0-alpha+2

### ISSUE THREAD

**Issue by aam** [dart-lang/mockito#110]
flutter's automatic dependency tracking doesn't support tracking alpha version of packages, so it will need proper release of mockito that is at 3.0.0-alpha+2.

**Comment by matanlurey** [comment]
I think that is very unlikely until we are done with the work for 3.x.

Maybe just fix Flutter's dependency tracking?

**Comment by srawlins** [comment]
Hrm... yeah this seems like a problem that will affect flutter long term for packages other than mockito. If flutter needs to depend on pre-release versions of deps, then it needs to depend on pre-release versions of deps...

That being said, I am prioritizing a Mockito 3.0.0 final and 2.3.0 final simultaneous release as early as next week. I'll keep Flutter in mind and keep y'all in the loop.

**Comment by aam** [comment]
There is a workaround in place in Flutter, yes. This issue tracks when workaround for mockito can be removed.

**Comment by aam** [comment]
> If flutter needs to depend on pre-release versions of deps

flutter doesn't _need_ it, but its dependencies internally and in OSS should match. That's what drives this issue.

**Comment by matanlurey** [comment]
@aam I agree with @srawlins. We can try and prioritize this time, but in general we aren't going to release dev versions as stable because Flutter's repo's script can't handle it. As a third party vendored package/tool internally, Flutter needs to abide by internal policies, it can't create its own.

**Comment by aam** [comment]
> @matanlurey closed this 44 minutes ago

Hm, this is pretty harsh. :-( Intent for this bug was to track next non-alpha release of Mockito so that Flutter can remove it's workaround. Given that, not sure what to make out of closing of this issue.

**Comment by matanlurey** [comment]
I sent you and Ian an email internally. tl;dr, we might have alpha releases internally at any given time, so it's not something that can be worked around temporarily.

**Comment by aam** [comment]
There was no intent to request an immediate non-`alpha` release of mockito that matches 3.0.0-alpha+<n>. The intent was to track next such release _when_ it becomes available so that when that happens we can remove workaround from Flutter code that pins mockito to 3.0.0-alpha+<n>.

**Comment by matanlurey** [comment]
Alexander, I understand. I sent you an email explaining why you'll need to keep the "workaround" indefinitely (forever) - we are going to have -alpha releases of various pub packages around forever. Please respond to my email internally or schedule a video call if you'd like to chat in person.

I understand you are frustrated but there is a lot of prior art here already.

**Comment by Hixie** [comment]
In general I think we're fine not using the latest alpha. It's only for this specific issue that there's a reason why we need to use it.
