### ISSUE TITLE
Additional Future/Stream return API?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#111]
Since we [stopped allowing Futures or Streams](https://github.com/dart-lang/mockito/commit/bbc51179c30ec0e95c79017e5a9181d5ff399ca6) from being returned in `thenReturn` _and_ we are [enforcing return type correctness](https://github.com/dart-lang/mockito/commit/8fbf1b1de695ffd868e03dc4559a90b57ba300f4), we're often stuck adding more syntactic sugar for (what many people perceive as) a no-op:

```dart
// old: `fn() returns a Future<List>, but it was always awaited, so returning a straight
// List was fine.
when(obj.fn()).thenReturn(new List.generate(10));

// new: We must now return a Future. Ugh but thenReturn won't let us.
when(obj.fn()).thenAnswer(
    (_) => new Future<List>.value(new List.generate(10)));

// shorter new:
when(obj.fn()).thenAnswer((_) async => new List.generate(10));
```

I hate both replacements because they use the Answer API which requires your callback to take an argument (the Invocation), when the user never needed the invocation. `thenReturn` is meant for _static_ return stubs that don't need access to the Invocation, and `thenAnswer` is meant for _dynamic_ return stubs which need access to the Invocation (or maybe call other code which will return dynamic values). So our answer to users is "paste this magic incantation: `thenAnswer((_) async =>`."

I don't disagree that the enforcement for Future/Stream is good, and prevents weird errors that are unintuitive for users, but new API is unfortunate.

I'd love an API like `thenReturnAsync(new List.generate(10))`, which is just sugar for `thenAnswer((_) async => new List.generate(10))`, but I don't think there is a sound way to write it...

I've seen another suggestion, `whenFuture` and `whenStream`, which allows the API to be written soundly. (`get whenFuture` would return `PostExpectation<Future<T>>`). But I really don't like putting the API all the way at the front like that. I think it's really unintuitive, and would be surprising... I think we can experiment and find something nice.

**Comment by joshua-i** [comment]
Having suggested whenFuture and whenStream, I'm a little biased towards that. But I did have another idea. There could be functions called something like `futureOf` and `streamOf` that use the same null-return-with-side-effects trick as `any` and `argThat`, which would be picked up by thenReturn. 
So the API would look like
```dart
when(obj.fn()).thenReturn(futureOf(new List.generate(10)));
```

Here's a first cut at an impl for `futureOf`
```dart
dynamic futureValue;
Future<T> futureOf<T>(T value) {
  futureValue = value;
  return null;
}

class PostExpectation<T> {
  T thenReturn<T>(T value) {
    if (futureValue != null) {
      if (value != null) throw new ArgumentError('futureOf was used wrong');
      thenAnswer((_) async => futureValue);
      futureReturn = null;
      return;
    }
    // Rest of the current impl below...
  }
}
```

**Comment by matanlurey** [comment]
@srawlins:

> ... we're often stuck adding more syntactic sugar for (what many people perceive as) a no-op:
> 
> ```dart
> // old: `fn() returns a Future<List>, but it was always awaited, so returning a straight
> // List was fine.
> when(obj.fn()).thenReturn(new List.generate(10));
> ```

This isn't syntactic sugar, this is _invalid_ code.

We return a `List` when `fn()` must return a `Future<List>`. I'm not sure this even works with the new NSM-semantics of Dart 2 (that DDC hasn't implemented yet, AFAICT).

> ```dart
> // new: We must now return a Future. Ugh but thenReturn won't let us.
> when(obj.fn()).thenAnswer(
>     (_) => new Future<List>.value(new List.generate(10)));
> ```

This wasn't the full issue, the full issue is that the API of `Future` (and `Stream`) _require_ that they are created in the `Zone` in which they are requested. Otherwise _lots_ of stuff doesn't work properly (`package:test`, `package:angular`, parts of Flutter, etc). It _has_ to be lazy (in a closure).

We _could_ give a small short-hand (instead of `.thenAnswer(_)`):

```dart
when(obj.fn()).thenLazy(() => new List.generate(10));
```

... but is that really worth it/valuable?

@joshua-i:

> Having suggested whenFuture and whenStream, I'm a little biased towards that

This doesn't work, again, it violates the contract of `Future` and `Stream`.

**Comment by joshua-i** [comment]
The `whenFuture` and `whenStream` I proposed would give you a different implementation of `PostExpectation` that always uses `thenAnswer`, maintaining the contract. 

```dart
typedef FutureExpectation = PostExpectation<T> Function<T>(Future<T> x);

FutureExpectation get whenFuture {
  Expectation expectation = when;
  return <T>(Future<T> t) => new FuturePostExpectation<T>._(expectation(t));
}

class FuturePostExpectation<T> implements PostExpectation<T> {
  final PostExpectation<Future<T>> _delegate;
  FuturePostExpectation._(this._delegate);

  @override
  thenReturn(T expected) =>
      _delegate.thenAnswer((_) => new Future.value(expected));

  @override
  thenAnswer(Answering<T> answer) => _delegate
      .thenAnswer((invocation) => new Future.value(answer(invocation)));
}
```

That being said, `thenLazy` isn't too bad.

I do think that a better solution to this is valuable. The current API is not only annoying to type out, but as Sam mentioned it mixes up the notions of what `thenReturn` and `thenAnswer` mean to most people (static vs dynamic).

**Comment by matanlurey** [comment]
Ah, I see what you mean. Yeah, SGTM, seems fine.

**Comment by srawlins** [comment]
Hmm, I'm not crazy about either of these. I don't know a sound way to write `thenLazy`'s signature (`void thenLazy(S where T is Future<S> expected)`?).

And again, it seems more confusing than simplifying to go all the way back to the beginning of the statement and write `whenFuture` instead of `when`... I'd rather not implement anything yet, but we can leave this open.

**Comment by joshua-i** [comment]
Sam, what did you think of the futureOf/streamOf from my first post?

**Comment by srawlins** [comment]
Yeah `futureOf` seems like it would work. I'm loathe to add more parens to stubs after this whole `typed(any)` debacle. I think I wouldn't use it myself, like I'd just stick to `new Future.value(...)` or `(_) async => ...`.

I dunno... seems like replacing an API with strangeness score of 10 (`thenAnswer((_) async => ...)`) with an API with strangeness score of 8 (`thenReturn(futureOf(...))`), and increasing the API surface area. I'd like to sit on this for a bit.

**Comment by TedSander** [comment]
I wouldn't call typed a debacle. It was the path forward without a complete rewrite. If you want to think about a debacle think of what another rewrite would have turned into.

**Comment by srawlins** [comment]
Haha yeah that's true. I just cringe every time I have to migrate Dart 1 code (`when(a.b(any, any, any, foo: any))...`) to Dart 2 code (`when(a.b(typed(any), typed(any), typed(any), foo: typed(any, named: 'foo')))...`) (which gets dartfmt'ed into 4 lines or something) and I know it makes a lot of users sad.

Like, I feel like you're violating some variant of the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) when you see three close parens (`)))`), and the current, unfortunate (not debacle) API strictly requires so many parens. ☹️ 

Mockito 3.0.0 cannot come soon enough!

To loop it back to `futureOf`, it's another unfortunate case of requiring so many close parens together, because Mockito already beaks a lot of "normal behavior" by _requiring_ certain things to take place within the `when(a.b(...))` (you can't setup `typed(any, named: 'foo')` above, or as a static variable).

**Comment by matanlurey** [comment]
I'm guessing this is no longer planned. We can re-open if that is the case, though.
