### ISSUE TITLE
Error message tells you to use typed(eq(null)) which is not a real thing

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/mockito#118]
If you try to call a mocked function with a null parameter, you get this error message:

Invalid argument(s): null arguments are not allowed alongside typed(); use "typed(eq(null))"

Unfortunately, trying to use typed(eq(null)) results in a test that does not actually build.

**Comment by srawlins** [comment]
Eek, sorry about that. What error do you get?

It should probably say `typed(argThat(isNull))` or something.

**Comment by matanlurey** [comment]
Closing due to lack of response from the author.
