### ISSUE TITLE
Why are the getters for Argmatchers not typed?

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/mockito#119]
Hi,

I ran today into the problem with Dart2 and disabling implicit casts that I got an error while using mockito in this project https://github.com/escamoteur/rx_widgets/tree/mockito_any_is_not_typed

![image](https://user-images.githubusercontent.com/16635729/39074021-21146fdc-44f0-11e8-8166-d240427f38f1.png)

That's in `rx_widgets\example\test\homepage_model_test.dart` 

When looking at your current source I saw that all types of the getters are commented out:

```
/// An argument matcher that matches any argument passed in "this" position.
/*ArgMatcher*/ get any => new ArgMatcher(anything, false);

/// An argument matcher that matches any argument passed in "this" position, and
/// captures the argument for later access with `captured`.
/*ArgMatcher*/ get captureAny => new ArgMatcher(anything, true);

/// An argument matcher that matches an argument that matches [matcher].
/*ArgMatcher*/ argThat(Matcher matcher, {String named}) =>
    new ArgMatcher(matcher, false);

/// An argument matcher that matches an argument that matches [matcher], and
/// captures the argument for later access with `captured`.
/*ArgMatcher*/ captureThat(Matcher matcher, {String named}) =>
    new ArgMatcher(matcher, true);

/// A Strong-mode safe argument matcher that wraps other argument matchers.
/// See the README for a full explanation.
T typed<T>(ArgMatcher matcher, {String named}) {
  if (named == null) {
    _typedArgs.add(matcher);
  } else {
    _typedNamedArgs[named] = matcher;
  }
  return null;
}
```

Why is that so? 
I only could help me now by casting `any as ArgMatcher`

**Comment by srawlins** [comment]
Not sure, @matanlurey this was your change: https://github.com/dart-lang/mockito/commit/66ed4feb516473883cd77d8f22d153ede13510cd

**Comment by matanlurey** [comment]
Prior to Dart 2, Dart 1.x + strong mode would fail if you wrote:

```dart
// ERROR: takesString expects (String) got (ArgMatcher).
when(something.takesString(any));
```

... so this was an easy way to "solve" that error. Now that we always require wrapping in `typed` in the "old" API and the various `ArgMatcher` getters are implicitly `typed(...)` in the new one, I don't know if we need to do anything? @srawlins

**Comment by srawlins** [comment]
Right so in master they return `null`. @escamoteur I think you'll have to keep casting until we release 3.0.0-beta, which is planned for next week.

**Comment by srawlins** [comment]
Not in master / Mockito 3.

In Mockito 3, all of the arg matcher APIs (`any`, `anyNamed`, `argThat`, `captureAny`, and `captureAnyNamed`, and `captureArgThat`) return `null`. At the moment I don't see a good place where this is documented...

But anyways, when you write `when(foo.fn(any))` in Dart 2, we can no longer pass crazy objects to `fn()`, we must only pass exactly objects of the type that are expected. The only object that can pass as an object of any type (the "bottom" type) is null. Calling one of the arg matcher APIs "stores" your arg matcher on the side, before returning null.

**Comment by escamoteur** [comment]
Thanks for the explanation
