### ISSUE TITLE
How to mock an async method to return simple value without any Future

### ISSUE THREAD

**Issue by acrozes** [dart-lang/mockito#138]
Is it possible (and how if yes) mock an async method that return a Future value by a simple value directly returned without any Future ...
Thank you.

**Comment by srawlins** [comment]
I think you're essentially asking for https://github.com/dart-lang/mockito/issues/111. For now, I do things like `thenReturn((_) async => 7);` which I think conveys that it returns a `Future<int>` just fine.

**Comment by acrozes** [comment]
I have a method like `` Future<int> original() async { [...] }`` and I'd like to mock this method to have an ``int`` as return type and not a ``Future<int>``

**Comment by srawlins** [comment]
Oh I see. Not that's a violation of overriding the `original` function. It's a language violation.

**Comment by acrozes** [comment]
Ok. So it is not possible and I need to create another class specifically for test. This is too bad ;) 
I'm working on a simplified example to show you ...

**Comment by TedSander** [comment]
If you are willing to change the method signature of the original function you can use FutureOr<int> which allows returning a Future, or an int directly.

Otherwise the dart language doesn't allow you to say you will return one type and then return a completely incompatible one instead.
