### ISSUE TITLE
Please export ArgMatcher type, add type annotation to any, captureAny.

### ISSUE THREAD

**Issue by redforks** [dart-lang/mockito#143]
Function `typed()` first argument is `ArgMatcher` type, which is not export.
`any`, `captureAny` type is dynamic.

dart 2 warns me when I use `typed(any)`:

```
The argument type 'dynamic' can't be assigned to the parameter type 'ArgMatcher'.
```

**Comment by matanlurey** [comment]
Typed is no longer required in the latest beta.

**Comment by redforks** [comment]
What a quick response!

I reviewed code after raise this issue, just before I pull back, you closed it. Sorry about wasting your time. I'll try to dig more deep before raise issue next time.

**Comment by matanlurey** [comment]
No worries!
