### ISSUE TITLE
Cannot capture non primitive parameters

### ISSUE THREAD

**Issue by matibzurovski** [dart-lang/mockito#153]
I have seen the example on the docs, where a `String` is captured (and its value verified):
```
cat.eatFood("Fish");
expect(verify(cat.eatFood(captureAny)).captured.single, "Fish");
```

However, if I want to run a more _complex_ test where and send the type of food in my own defined class, I get this error:
> Exception has occurred.
> type 'ArgMatcher' is not a subtype of type 'FoodObject'

Also, I want to send another parameter with a callback that should be executed when the async operation succeeds. Therefore, I wouldn't be comparing this object (like the example does with `"Fish"`), but directly invoking it in the test so that I can test the behavior triggered.

Leaving the code below with the comments detailing what I am missing.

```Dart
typedef void EndpointCallback(String body);

class Client {
    void hitEndpoint(RequestObject reqObject, EndpointCallback callback) async {
        // Implementation..
    }
}

class RequestObject {
    String value;
}

class Manager {
    
    Client _client;

    Manager(client: Client) {
        this._client = client
    }

    void method() {
        void callback(String body) {
          print(body);
        }

        RequestObject reqObject = RequestObject(value: 'important value');

        client.hitEndpoint(reqOject: reqObject, callback: callback);
    }
}

// Testing the Manager
void main() {
    MockClient client;
    Manager manager;

    setUp(() {
        client = MockClient();
        manager = Manager(client: client);
    });

    test('test callack is called', () {
      when(client.hitEndpoint(captureAny, any)).
      thenAnswer((_) => 5); // 1. what should I put here?

      // 2. how can I capture the second argument (callback) and invoke it from the test?

      
    });
}

class MockClient extends Mock implements Client {}
```

**Comment by matanlurey** [comment]
Depending on the version of Mockito you are using, you might have to write:

```dart
.hitEndpoint(typed(captureAny), ...)
```

See https://github.com/dart-lang/mockito/blob/master/upgrading-to-mockito-3.md#table.

Does that help?

**Comment by matibzurovski** [comment]
Hey @matanlurey, thanks for the quick answer.

I am using version `2.2.3`, so it looks like I need to add the `typed(captureAny)` keyword. Still, I am not sure how to access the `captured` argument later, nor what should I put (the `thenAnswer((_) => 5)` is more like a placeholder I put in order to be able to _capture_ the argument.

**Comment by srawlins** [comment]
Thanks for following up, @matibzurovski
