### ISSUE TITLE
Mockito can guard against misleading stubbing of real methods.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#158]
Take this mock:

```dart
class MockA extends Mock implements A {
  @override
  int foo() => 7
}
```

If someone tries to stub `foo()`, mockito will pretend to do it, but it won't work:

```dart
var a = new MockA();
when(a.foo()).thenReturn(6);
a.foo(); // returns 7.
```

I think it would be easy for Mockito to crash on the stubbing line above. `noSuchMethod` could return `const WHEN_STUB = const Object()` during a `when` call. Then, in the `when` call, if the method returns something other than`WHEN_STUB`, like `7`, it can throw, saying "Uh... this doesn't look like it was properly stubbed."

WDYT @matanlurey

**Comment by srawlins** [comment]
I hate you.

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

I tried this, you are right.

**Comment by srawlins** [comment]
We could set another marker, like the other globals Mockito uses, `_whenInProgress`, `_verificationInProgress`...

`noSuchMethod` could set `_iWasJustInsideNoSuchMethod = true`. This should be as foolproof as `_whenInProgress` is.

**Comment by matanlurey** [comment]
Works for me!
