### ISSUE TITLE
Stub-and-verify wrapper

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#164]
I wrote a test recently that went something like this:

```dart
  test('parse calls `fancy query` given a path with /BUILD', () async {
    var expectedArgs = ['several', 'arguments', 'here'];
    when(processManager.run(expectedArgs,
            stdoutEncoding: null, runInShell: true))
        .thenAnswer((_) async => _emtpytResult);

    await FancyFile.parse('foo/BUILD', controller: controller);

    verify(processManager.run(expectedArgs,
            stdoutEncoding: null, runInShell: true))
        .called(1);
  });
```

As the description said, the verification is all I care about. But I have to write the stub because the value returned by `processManager.run` is used; it cannot be null. And since a handful of arguments are passed, the stub takes 3 lines to write, and the verification takes 3 more, with a ton of duplication ☹️ . What if we had an API that took a closure, and performed the stub and the verification for you?

```dart
  test('parse calls `fancy query` given a path with /BUILD', () async {
    var expectedArgs = ['several', 'arguments', 'here'];
    callWithStub(
      () async {
        await FancyFile.parse('foo/BUILD', controller: controller);
      },
      stub: processManager.run(expectedArgs,
          stdoutEncoding: null, runInShell: true),
      answers: (_) async => _emtpyResult,
      verifyCalled: 1,
    );
  });
```

This code would do the same thing, something like:

1. Add a stub with `stub` and `answers` (or `returns`).
2. Execute the closure.
3. Verify the stub was called, again using `stub`, and `verifyCalled`.

#### Upsides

* Reduces duplication.
* Can catch exceptions while executing the closure, and hint to user that "stub" (call matcher) might be incorrect, and display caught calls. Right now, if a stub doesn't have the right arguments, the user usually gets a NoSuchMethodError or similar during their test, and has to use Mockito's debugging stuff, or guess better what the method arguments should be.

#### Downsides

* Code is pretty hard to read with the inline closure as an argument to callWithStub...
* Separates a "stub" (call matcher) from the canned response return value.
* I think the inline function call at `stub:` feels gross, especially when it has to wrap.
* Duplicates lots of API, which may or may not be intuitive if you know the regular API.
* Would not support capturing... or would with another closure \*cringe*.

If the main code closure was also a named parameter, then it could be placed anywhere, which might feel more natural:

```dart
  test('parse calls `fancy query` given a path with /BUILD', () async {
    var expectedArgs = ['several', 'arguments', 'here'];
    withStub(
      stub: processManager.run(expectedArgs,
          stdoutEncoding: null, runInShell: true),
      answers: (_) async => _emtpyResult,
      forCode: () async {
        await FancyFile.parse('foo/BUILD', controller: controller);
      },
      verifyCalled: 1,
    );
  });
```

Anyways, posting here to see if anyone has any thoughts.

**Comment by TedSander** [comment]
I'm not very excited about this... I guess I come from a more classically trained background where I like to see tests with the format:
// setup
// action
// verify

This seems to break that format, and makes the test a bunch harder to read for me.

If we need to do anything here I would rather see:

```dart
test('parse calls `fancy query` given a path with /BUILD', () async {
    var expectedArgs = ['several', 'arguments', 'here'];
    when(processManager.run(expectedArgs,
            stdoutEncoding: null, runInShell: true))
        .thenAnswer((_) async => _emtpytResult)
        .expect(1);

    await FancyFile.parse('foo/BUILD', controller: controller);

    verifyStubs();
  });
```

**Comment by srawlins** [comment]
Yeah I am also a big fan of setup/action/verify, another downside.

Your approach is interesting! Not a bad idea.

**Comment by srawlins** [comment]
Imma close this, as I really agree that setup/action/verify should be encouraged.
