### ISSUE TITLE
Add a `Fake` class - noSuchMethod throws

### ISSUE THREAD

**Issue by natebosch** [dart-lang/mockito#169]
I'm noticing a common pattern is using `extends Mock` but then still manually implementing a bunch of overridden methods and treating the class as a Fake - never using `when()` or `verify()` with it. The `Mock` superclass is only applied because it has a `noSuchMethod` which means that they don't need to add _all_ the overrides, just the ones that are called in the test.

A better practice would be to implement a `Fake` once in a testing library next to the class, but that doesn't seem to be something authors are willing to do. If they are going to use and `extends` to pick up a `noSuchMethod` this way maybe we should give them a supported way to do it that still nudges towards better naming.

Thoughts @srawlins @matanlurey ?

**Comment by srawlins** [comment]
Interesting, so the provided `Fake` class would just have a no-op `noSuchMethod`? The benefit here is in the naming?

**Comment by natebosch** [comment]
Yes, the benefits as I see them are:

- Nudge towards better naming. Lets reviewers point to an alternative which isn't extra work but also follows conventions and so is less confusing.
- Disallow using a `Fake` as a `Mock` and having blurred lines between the two. It would be confusing to have a class which has some faked methods manually implemented, but then later _also_ get used with `when()` and `verify()`. We could potentially add a lint that classes which `extends Mock` don't have manually overridden faked methods - not sure if that's going too far though.

**Comment by matanlurey** [comment]
I'd support that.
