### ISSUE TITLE
3.0.1: type 'Invoker' is not a subtype of type 'Invoker'

### ISSUE THREAD

**Issue by MarcinusX** [dart-lang/mockito#172]
I'm trying to run a unit test:
```
test("Given empty list ChartPainter draws only Paragraph", () {
    //given
    MockCanvas mockCanvas = new MockCanvas();
    Size size = new Size(600.0, 600.0);
    ChartPainter chartPainter = new ChartPainter([], 30, true);
    //when
    chartPainter.paint(mockCanvas, size);
    //then
    verifyNever(mockCanvas.drawCircle(any, any, any));
    verifyNever(mockCanvas.drawLine(any, any, any));
    verify(mockCanvas.drawParagraph(any, any)).called(1);
  });
```
On version `3.0.0` everything works fine.  
On version `3.0.1` I get following error:

>type 'Invoker' is not a subtype of type 'Invoker' in type cast where
  Invoker is from package:test/src/backend/invoker.dart
  Invoker is from package:test_api/src/backend/invoker.dart
dart:core                                         Object._as
package:test_api/src/backend/invoker.dart 138:40  Invoker.current
package:test_api/src/frontend/expect.dart 94:15   _expect
package:test_api/src/frontend/expect.dart 60:3    expect
package:mockito/src/mock.dart 668:5               VerificationResult.called
test/unit_tests/chart_painter_test.dart 21:48     main.<fn>

`flutter doctor -v`:
>Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale pl-PL)
    • Flutter version 0.9.4 at /Users/mszalek/flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

**Comment by srawlins** [comment]
Sorry about this. There is sort of just a known incompatibility between mockito `3.0.1` and test `^1.3.0`.

Mockito is using Invoker from the `test_api` package. But your test is using Invoker from the `test` package. This incompatibility cannot be resolved until Flutter puts out a release that uses the test package `>=1.4.0`. I think they will do this in the coming week.

Until then, you can pin your version of Mockito to `3.0.0` (instead of `^3.0.0`).

**Comment by srawlins** [comment]
CC @jonahwilliams

**Comment by Panthro** [comment]
That shouldn't have been a bugfix release then right?
It's breaking builds for everyone on CI's 👎

**Comment by srawlins** [comment]
We'll release a new 3.x release that goes back to the 'test' package, and re-release the bump to the 'test_api' package in a mockito 4.0.0 release.

That way, CI will go green for now. When Flutter's tests start using test ^1.4.0 (IIUC), they will again break until a package's mockito dependency bumps to ^4.0.0, but that seems like a more correct path forward. We might be able to put in messaging around "type 'Invoker' is not a subtype of type 'Invoker'" to say, "try upgrading mockito to 4.0.0. what could it hurt?"

**Comment by Panthro** [comment]
Agree on that approach. Is easier to detect a failure when you upgrade the
SDK version easier than a dependency that was automatically updated
