### ISSUE TITLE
Wrong pub link in readme

### ISSUE THREAD

**Issue by MisterJimson** [dart-lang/mockito#178]
Pub badge in readme goes to https://github.com/dart-lang/mockito/blob/master

Should be https://pub.dartlang.org/packages/mockito

**Comment by srawlins** [comment]
@kevmoo, who maintains the pub badge stuff at shields.io/pub ?

The source for that badge in this README is

```markdown
[![Pub](https://img.shields.io/pub/v/mockito.svg)]()
```

which should compile from Markdown to the following HTML

```html
<a href=""><img src="https://img.shields.io/pub/v/mockito.svg" /></a>
```

so I have no idea where it is getting `https://github.com/dart-lang/mockito/blob/master` from, which is a 404 ☹️ . I assume leaving the URL blank is a GitHub badges feature?
