### ISSUE TITLE
Null value on component testing

### ISSUE THREAD

**Issue by manuscle** [dart-lang/mockito#181]
Hi, I have a problem while testing a component that use a service which use a mockService:
I don't know why in my component I get a null value, It should get WcfPreselction instance

The service:
```dart
class EtablissementService {
  static const _preselectionUrl = '/etablissement/preselection';
  final WcfService _wcfService;
  EtablissementService(this._wcfService);

  Future<WcfPreselection> preselection() async {
    return _wcfService.preselection(_preselectionUrl);
  }
}
```

The mock service:
```dart
class WcfMockService extends Mock implements WcfService {}
```
In The component:
```dart
Future<void> _getEtablissements() async {
    preselection = await _etablissementService.preselection();
}
```
The test:
```dart
NgTestFixture<EtablissementListComponent> fixture;
Router router;

@GenerateInjector([
  ClassProvider(EtablissementService),
  ClassProvider(WcfService, useClass: WcfMockService),
  routerProvidersForTesting,
])
final InjectorFactory rootInjector = self.rootInjector$Injector;

main() {
  final injector = InjectorProbe(rootInjector);
  final testBed = NgTestBed.forComponent<EtablissementListComponent>(
      ng.EtablissementListComponentNgFactory,
      rootInjector: injector.factory);

  WcfMockService wcfMockService;
  EtablissementService etablissementService;

  setUp(() async {
    wcfMockService = injector.get<WcfMockService>(WcfService);
    etablissementService = injector.get<EtablissementService>(EtablissementService);
    clearInteractions(wcfMockService);

    when(wcfMockService.preselection('/etablissement/preselection'))
        .thenAnswer((_) => Future.value(WcfPreselection.fromJson(etablissement_preselection)));

    var pre = await etablissementService.preselection(); // Work
    fixture = await testBed.create(); // Don't work, the service.preselection() return null in the component
    await router?.navigate('/etablissements'); 
    await fixture.update();
  });

  tearDown(disposeAnyRunningTest);
}
```

**Comment by srawlins** [comment]
This seems like a bug having to do with injection, more than the mocking. A few questions:

* When you say ` var pre = await etablissementService.preselection();` "works", what do you mean by that?
* When you say `fixture = await testBed.create();` "doesn't work", what do you mean by that? When would 
* In the EstablissmentService, can you print what type of WcfService is being injected? Like:

  ```dart
  EtablissementService(this._wcfService) {
    print('wfcService is a ${_wcfService.runtimeType}');
  }
  ```
* Have you tried substituting `any` in for the string `'/etablissement/preselection'`?

**Comment by manuscle** [comment]
> This seems like a bug having to do with injection, more than the mocking. A few questions:
> 
> * When you say ` var pre = await etablissementService.preselection();` "works", what do you mean by that?

I mean that the WcfMockService return what is expected, so an instance of WcfResponse, so the when() stubbing has worked as expected

> * When you say `fixture = await testBed.create();` "doesn't work", what do you mean by that? When is `service.preselection()` called?

I mean that the component call EtablissementService::preselection() method, which call the WcfMockService::preselection() method that should return an instance of WcfResponse. I've checked inside the EtablissementService class, and the _wcfService is an instance of WcfMockService, but the when() stubbing created earlier is not applied and it return null. So the component throw an Exception.

> * In the EstablissmentService, can you print what type of WcfService is being injected? Like:
>   ```dart
>   EtablissementService(this._wcfService) {
>     print('wfcService is a ${_wcfService.runtimeType}');
>   }
>   ```

Of course: wfcService is a WcfMockService

> * Have you tried substituting `any` in for the string `'/etablissement/preselection'`?

Yes

**Comment by manuscle** [comment]
You were true, it's an injection problem.
The WcfMockService was created twice.
So I made a Singleton

**Comment by srawlins** [comment]
Ahhh great catch. So it was injecting the mock each time, but the stub was only written onto the one mock.
