### ISSUE TITLE
Capture argument Type

### ISSUE THREAD

**Issue by e-belair** [dart-lang/mockito#189]
Hi, I have a service typed method:

```dart
class MyService {
  Future<List<T>> getTableRefModel<T>({WcfRequest request, bool cache=true}) async {}
}
```
How can I mock to capture the given Type argument ?
I tried this but it capture every given class
```dart
when(myMockService.getTableRefModel<Commune>())
      .thenAnswer((_) => Future.value(communes));
```

**Comment by srawlins** [comment]
The argument sent to the callback in `thenAnswer` is the [Invocation]() object which has a [typeArguments](https://api.dartlang.org/stable/2.2.0/dart-core/Invocation/typeArguments.html) field.

I don't think you can restrict the stub matching on the type argument, so I would just write a smart callback that either returns null or throws or whatever if typeArguments.first is not Commune.

**Comment by e-belair** [comment]
Ok I got it.
Thank you very much!
