### ISSUE TITLE
How to mock static methods?

### ISSUE THREAD

**Issue by daviidmorales** [dart-lang/mockito#214]
I don't know how to mock static methods and i would like to know if you have any example or i have to fix mi code to works without static methods. 

Thanks.

**Comment by srawlins** [comment]
There is no way to override a class's static method. Depending on your use case, you can wrap the static methods with a class and instance methods, like in the [process](https://pub.dev/packages/process) package, or in the [file](https://pub.dev/packages/file) package.

**Comment by daviidmorales** [comment]
@srawlins Can you show me an example, please?

**Comment by srawlins** [comment]
E.g. [Process.runSync](https://api.dartlang.org/stable/2.4.1/dart-io/Process/runSync.html), is static.

Refactor this code:

```dart
class DirectoryLister {
  ProcessResult list(String directory) => Process.runSync('ls', [directory]);
}
```

to

```dart
class DirectoryLister {
  final ProcessManager processManager;
  DirectoryLister({ProcessManager processManager}) :
      this.processManager = processManager ?? ProcessManager;

  ProcessResult list(String directory) => processManager.runSync('ls', [directory]);
}

class ProcessManager {
  ProcessResult runSync(String command, List<String> args) =>
      Process.runSync(command, args);
}
```

Then in tests, you can create a MockProcessManager, and stub its `runSync` instance method. In real code,  no need to fuss with or pass a ProcessManager in code that uses DirectoryLister. In tests, you create and pass a mock as the ProcessManager.

**Comment by daviidmorales** [comment]
Thanks, I'm going to refactor my code.
