### ISSUE TITLE
How to mock second call?

### ISSUE THREAD

**Issue by RomanKapshuk** [dart-lang/mockito#221]
How to mock the second call of function? 
E.g, I have the function, that calls API, and in case if it fails we are trying to make the same call and then expecting fine answer?

```
  final api = Api();


  Info _getRemoteInfo() async {

    try {
      final result = await api.getInfo(); // should throw Exception
      return result;
    } catch (ex) {
     // Do some stuff to fix the api issue;
      final result = await api.getInfo(); // should return Info object
      return result;  
    }

  }
```

**Comment by srawlins** [comment]
In GitHub comments, make sure to put code examples in Markdown codeblocks. The easiest way to do this for your code above is to wrap your example in triple-backticks:

    ```dart
    final api = Api();
    ...
    ```

When you stub a method call like `when(foo.bar()).thenReturn(7)`, then  7 will be returned every time `bar()` is called, including the first, second, ...

**Comment by RomanKapshuk** [comment]
@srawlins Thanks.
Ok, but what about to make the ability to add a sequence of expected values?
Something like 

``` 
when(foo.bar()).thenReturn([1, 2, 3]);
when(foo.bar()).thenAnswer([() async => 1, () async => 2, () async => 3]);
etc..
```
So on every new call of bar() method – it will returns next value in the list?

``` 
final mockedFoo = MockedFoo();

test('', () {
when(foo.bar()).thenReturn([1, 2, 3]);

final firstResult = foo.bar(); // 1
final secondResult = foo.bar(); // 2
final thirdResult = foo.bar(); // 3

});
```

**Comment by srawlins** [comment]
Mockito doesn't have a mechanism for that, but I could see us adding something like `thenReturnInOrder` and `thenAnswerInOrder`.

For now, use a variable declared outside the "answer" response.

```dart
var callCount = 0;
when(mockedFoo.bar()).thenAnswer((_) => [1, 2, 3][callCount++]);
```

But make it more readable :P

**Comment by RomanKapshuk** [comment]
@srawlins Sure, it would be awesome! Thanks!

**Comment by MJablonskiCodespot** [comment]
Here's extension for it:

```dart
extension When<T> on PostExpectation<T> {
  void thenAnswerInOrder(List<T> values) {
    int callCount = 0;
    thenAnswer((_) => values[callCount++]);
  }
}
```

And usage:

```dart
final ChannelsDao channelsDao = MockChannelsDao();
final List<Channel> apiChannels = [MockChannel()];
final List<Channel> emptyChannelLis = [];
when(channelsDao.getAll()).thenAnswerInOrder([
      Future.value(emptyChannelLis),
      Future.value(apiChannels),
    ]);
```
