### ISSUE TITLE
How to Mock Streams?

### ISSUE THREAD

**Issue by felangel** [dart-lang/mockito#223]
```dart
class Foo {
  StreamSubscription _subscription;
  
  Foo(Stream stream) {
    _subscription = stream.listen((data) {
      // some logic that needs to be unit tested
    });
  }
}
```

Is it possible to use `mockito` to mock the injected `Stream`? I've tried

```dart
class MockStream extends Mock implements Stream {}

test('', () {
  final mockStream = MockStream():
  when(mockStream).thenAnswer((_) => Stream.fromIterable([...]));

  final foo = Foo(mockStream);

  ...
});
``` 

But I get the error:
```sh
ERROR: Bad state: Mock method was not called within `when()`. Was a real method called?
```

Is there a recommended way to use `mockito` to mock classes that extend `Stream` so that a fake stream of data can be provided to the `onData` closure in `listen`?

**Comment by srawlins** [comment]
`when(mockStream)` is not a valid use of the Mockito API; please see the readme for how to stub methods.

**Comment by mmcc007** [comment]
FYI: [This](https://github.com/flutter/flutter/blob/bae92c32e5233e9113e42962179773309fb3ad8c/dev/manual_tests/test/mock_image_http.dart#L23-L29) shows a way to mock `onData`. Though it's several years old, so there might be another way.

**Comment by mmcc007** [comment]
[This](https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/test/general.shard/commands/create_test.dart#L1294-L1302) looks like another way

**Comment by Elias8** [comment]
Any solutions, Please.

**Comment by srawlins** [comment]
@Elias8 Any solutions to what, please?

**Comment by Elias8** [comment]
To the above question. About mocking streams. I was wondering if there is any update. Thanks.

**Comment by srawlins** [comment]
Sorry, I didn't understand the original question. I responded to the question [here](https://github.com/dart-lang/mockito/issues/223#issuecomment-542043107) that it involved an unsupported use of Mockito.

If you wish to mock a Stream, create a mock class.

```dart
import 'package:mockito/mockito.dart';

class MS extends Mock implements Stream<int> {}

void main() async {
  var stream = MS();
  when(stream.first).thenAnswer((_) => Future.value(7));
  print(await stream.first);

  when(stream.listen(any)).thenAnswer((Invocation invocation) {
    var callback = invocation.positionalArguments.single;
    callback(1);
    callback(2);
    callback(3);
  });

  stream.listen((e) async => print(await e));
}
```

**Comment by Babwenbiber** [comment]
Some return value is missing (for null safety?!).
When I use the code above, I get the following at `thenAnswer`: 
`The body might complete normally, causing 'null' to be returned, but the return type is a potentially non-nullable type. (Documentation)  Try adding either a return or a throw statement at the end.`

**Comment by srawlins** [comment]
@Babwenbiber please read the [top of the README](https://github.com/dart-lang/mockito#lets-create-mocks) regarding using mockito with null safety. [The above solution](https://github.com/dart-lang/mockito/issues/223#issuecomment-640286713) is no longer valid under the null safety language feature.

**Comment by cbatson** [comment]
FWIW, this works these days:

```dart
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

import 'test_test.mocks.dart';

@GenerateMocks([Stream])
void main() {
  test('foo', () async {
    var stream = MockStream();

    Stream<int> streamFunc() async* {
      yield 1;
      yield 2;
      yield 3;
    }
    when(stream.listen(
      any,
      onError: anyNamed('onError'),
      onDone: anyNamed('onDone'),
      cancelOnError: anyNamed('cancelOnError'),
    )).thenAnswer((inv) {
      var onData = inv.positionalArguments.single;
      var onError = inv.namedArguments[#onError];
      var onDone = inv.namedArguments[#onDone];
      var cancelOnError = inv.namedArguments[#cancelOnError];
      return streamFunc().listen(onData, onError: onError, onDone: onDone, cancelOnError: cancelOnError);
    });

    stream.listen((e) async => print(await e));
  });
}
```
