### ISSUE TITLE
Fail to count a call when mockito instance called from inside a stream transformer

### ISSUE THREAD

**Issue by jhionan** [dart-lang/mockito#229]
If a mocked class is called inside a  stream transformer like map, asyncMap etc..
the stub will work, but when you verify if the function was called it will fail and return 
"No matching calls (actually, no calls at all). (If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)"

**Comment by natebosch** [comment]
Are you sure the call has been done before you are attempting to verify it? A Stream is async, so if you set up the expectation and verify before the events have gone through the stream this would happen.

There is nothing about Stream or any chained calls on a Stream that would break Mockito behavior.

Can you post a minimal reproduction?

**Comment by jhionan** [comment]
I just made more tests, and you  are right,  the problem here is the async call, my verify didnt have a `await untilCalled`
