### ISSUE TITLE
Bug with functions Future<void> when  trying to mock null parameter

### ISSUE THREAD

**Issue by Feralnex** [dart-lang/mockito#235]
Hello,
I found a bug with mocking functions that returns Future<void> and have more than 2 parameters. When You mock it like when(mock.returnsFutureVoid(null, any)).thenThrow(AssertionError) - because returnsFutureVoid can't be invoked with null - and check if assertion is thrown, You get that it didn't (but it should, because I'm checking all parameters with assert()). BUT You can only check whether last parameter is null or all of them, in any other attempt it doesn't work as it should.

**Comment by Feralnex** [comment]
Ok so for example i would like to test if this function will throw AssertionError:

`class Repository {
  Future<void> printSomething(String head, String body) async {
    assert(head != null);
    assert(body != null);

    print(head + body);
  }
}`

`class MockRepository extends Mock implements Repository {}

void main() {
  MockRepository mockRepository;

  setUp(() {
    mockRepository = MockRepository();
  });

  test('Test if throws AssertionError', () {
    when(mockRepository.printSomething(null, any)).thenThrow(AssertionError);

    expect(() async => mockRepository.printSomething(null, 'body'),
        throwsAssertionError);
  });
}`

And the test fails, why? Sorry if this is stupid issue or i'm doing something wrong.

**Comment by srawlins** [comment]
I think you need to throw an instance of AssertionError, rather than the type, AssertionError.

**Comment by Feralnex** [comment]
I tried throw AssertionError object, even with message, and still it doesn't seems to work.

**Comment by srawlins** [comment]
Where does your `throwsAssertionError` come from? I don't see it in the [test API](https://pub.dev/documentation/test/latest/test/test-library.html).

**Comment by srawlins** [comment]
Closing this bug as we need more information to resolve; please re-open if you are still experiencing the issue.
