### ISSUE TITLE
Some tests pass, while very similar tests fail

### ISSUE THREAD

**Issue by phasee** [dart-lang/mockito#237]
I posted a question on stackoverflow and don't seem to be getting much traction in way of answers.

I will just post the link to avoid duplication: [Fluitter Unit Testing: Some tests pass, while other similar tests fail
](https://stackoverflow.com/questions/60118434/fluitter-unit-testing-some-tests-pass-while-other-similar-tests-fail)

Is this a bug? Or am I doing something wrong?

**Comment by jakemac53** [comment]
Transferred to mockito - I suspect this is working as intended and is more a side effect of the expected arguments you are passing to `when`.

Specific red flags there are `Paths.reviews()` and `review.toMap()`. I am not personally aware of what type of matching strategy mockito uses (specifically for collections), but that is probably failing to match in the 2nd case for some reason.

I would look at those functions and make sure repeated calls will give the same result, etc.

**Comment by natebosch** [comment]
It could be something with the named arguments, you might try something like `data: argThat(equals(review.toMap()), named: 'data')`.

**Comment by phasee** [comment]
Tried your suggestion, test still fails with the same 'null' instead of 'true'

**Comment by phasee** [comment]
Is there anything else I can try? Should I be setting the test up differently?

**Comment by natebosch** [comment]
> Is there anything else I can try? Should I be setting the test up differently?

It's hard to tell without a full minimal reproduction case. I strongly suspect it has to do with your argument matchers for named arguments.

I'd recommend trying to pare down your case until it no longer reproduces and see if you can find the problem from there. You might want to focus on differences between `Item.toMap()` and `Review.toMap()` since that looks like the relevant difference?

**Comment by phasee** [comment]
The tests are now passing. I believe I was missing a named parameter, so it was failing to pick up the mocked method being called.

That's what I guess was the issue...
