### ISSUE TITLE
Flutter widget test - open and tap value in DropDownButton, not working as expected

### ISSUE THREAD

**Issue by phasee** [dart-lang/mockito#238]
Created a sample app for the issue, which can be found here: https://github.com/phasee/flutter_dropdown_test_selection_issue

I am trying to test the value passed to a model from a dropdownbutton, and the WidgetTester does not seem to tap the item correctly.

I have a model which I am mocking using mockito. When a value is chosen from the dropdownbutton, that value should be passed to the model.updateSelection method. I cannot verify this method is called during the test.

Is this a bug? Or am I misunderstanding how dropdownbuttons behave?

**Comment by phasee** [comment]
Can anyone offer any insight into this issue? Thanks!

**Comment by roxifas** [comment]
@phasee Your test is missing `tester.pump()` or `tester.pumpAndSettle()` calls after the taps. An example how these are used is here: https://flutter.dev/docs/cookbook/testing/widget/tap-drag

**Comment by srawlins** [comment]
Closing as resolved; please re-open if the latest suggestion does not fix.
