### ISSUE TITLE
Error because subtype 'dynamic' does not match if using equals() in expexted()

### ISSUE THREAD

**Issue by blaueeiner** [dart-lang/mockito#240]
Hi Mockito Community!
I got a problem related to equality match with subtypes.

This is my code snippet that is relevant: 
`expect(result, equals(Right([tActivity])));`
and I get the following error when running tests:

**"Expected: Right<dynamic, List<Activity>>:<Right([ActivityModel])>
  Actual: Right<Failure, List<Activity>>:<Right([ActivityModel])>"**

The problem is caused by the little type difference 'dynamic' <-> 'Failure'.

This behaviour might be correct but is there another way for expecting the code to pass?

**Comment by srawlins** [comment]
I don't see how the issue you have described relates to the Mockito mocking framework. Can you give more context?

**Comment by natebosch** [comment]
It looks like what is happening here is failing to get the right types because inference is filling them in a way you don't expect.

I'd add explicit type arguments

```dart
expect(result, equals(Right<Failure, List>([tActivity]));
```
