### ISSUE TITLE
Integration test mocking

### ISSUE THREAD

**Issue by pwnywiz** [dart-lang/mockito#241]
I've been trying to mock a method call while doing some integration tests but with no success.
As I read in [this](https://medium.com/stuart-engineering/mocking-integration-tests-with-flutter-af3b6ba846c7) article I tried to use a `DataHandler` to pass a message to my app isolate in order to mock my method call. Below I will be presenting a simple demonstration.

This is my Class
```
class RandomThing {
  String getRandomString() => 'aaa';
}
```

This is the app part
```
class MockRandom extends Mock implements RandomThing {}

void main() {
  Future<String> dataHandler(String msg) async {
    switch (msg) {
      case 'randomThing':
        final randomMocked = MockRandom();
        print('INSIDE DATA HANDLER');
        when(randomMocked.getRandomString()).thenReturn('aaabbb');
        break;
      default:
        break;
    }
  }

  enableFlutterDriverExtension(handler: dataHandler);
  test_app.main();
```
This is the part of my app_test
```
test('Do that random thing', () async {
        await driver.requestData('randomThing');
        await driver.waitFor(someFinder, timeout: Duration(seconds: 15));
        await driver.tap(someFinder);
        await Future.delayed(Duration(seconds: 10));
});
```
So when the `someFinder` button is tapped, the method I am trying to mock is called inside my widget but returns the real result instead of the mocked.
Am I missing something regarding how mocks work with Mockito?
Thanks a lot for any help.

**Comment by srawlins** [comment]
In your example, you instantiate a MockRandom object, but you don't give it to any other code to use. No code can call `getRandomString()`.

**Comment by pwnywiz** [comment]
It gets called inside a widget which I omitted for the shake of brevity. I only mentioned the test parts but here's an oversimplified example of my widget :).

```
class A extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return IconButton(
          icon: Icon(
            Icons.add,
          ),
          onPressed: () => getRandomString(),
        )
  }
}
```

**Comment by srawlins** [comment]
> It gets called inside a widget

It does _not_ get called. You instantiate an instance of MockRandom here:

`final randomMocked = MockRandom();`

and then never use it. No code calls `getRandomString()` on `randomMocked`. If `class A` has code which calls `this.getRandomString()`, that is quite unconnected from your `randomMocked` instance.

**Comment by pwnywiz** [comment]
So you're saying that I need to call the widget explicitly from within my test suite for it to return the mocked version?

**Comment by natebosch** [comment]
What @srawlins is saying is that the _instance_ that your widget has, when it calls the method, must be the instance that you created as a mock.

In your example the only code that references an instance of your mocked class is:

```dart
        final randomMocked = MockRandom();
        print('INSIDE DATA HANDLER');
        when(randomMocked.getRandomString()).thenReturn('aaabbb');
        break;
```

That `randomMocked` variable is not passed into the widget, it is not the same instance that is being used.

You'll need to use something like dependency injection to make sure that the actual object being used by your code is an instance of the mock, not an instance of the real thing.

If this is still a problem for you please post a more complete example where you pass the `randomMocked` instance into the code under test.
