### ISSUE TITLE
Verify if a mocked class function is called

### ISSUE THREAD

**Issue by DonMatano** [dart-lang/mockito#249]
Hey. I am trying to test if a function in a mocked class is called.

**The class I will mock**. As you can see the class doesn't extend the `Fake` class. It's just a normal class.
```
class FakeWeddingRepository implements WeddingRepository {
  final listOfWeddings = <Wedding>[];
  @override
  Future<Wedding> addWedding(Wedding wedding) {
    listOfWeddings.add(wedding);
    return Future.value(wedding);
  }
}
```
**In the usecase**
```
class AddWeddingUseCase implements AddWeddingInput {
 WeddingRepository _weddingRepository;
 AddWeddingUseCase({@required WeddingRepository weddingRepository}) {
  this._weddingRepository = weddingRepository;
 }

  @override
  Future<void> execute({@required AddWeddingParams params}) async {
    Wedding wedding = Wedding(name: params.name);
    Wedding addedWedding = await _weddingRepository.addWedding(wedding);
  }
}
```

**Mocking in test**
```
class MockFakeWeddingRepository extends Mock implements FakeWeddingRepository {}
void main() {
  test('Adds wedding', () async {
    final weddingRepository = MockFakeWeddingRepository();
    final wedding = Wedding(name: 'Example')
    final addWeddingUseCase = AddWeddingUseCase(weddingRepository: weddingRepository);
    final params = AddWeddingParams(weddingName);
    await addWeddingUseCase.execute(params: params);
    verify(weddingRepository.addWedding(wedding));
  });
}
```

**Question**
It seems the `weddingRepository`, _which is an instance of `MockFakeWeddingRepository`_, `addWedding` method doesn't call the base class method or even never called. What I get back from calling this is `null` instead of a `Wedding` object as expected. Moreover the `verify(weddingRepository.addWedding(wedding));` check always fails with no interaction error. This has me asking :-

 - Am I doing something wrong? If so some assistance will be of help.
 - Does that mean the only way to verify a function call is to create a stub of the `addWedding` 
    function? From reading the docs, seems unlikely to be the case.
 - But if it is the case. How exactly does one just check if a function was called?

Your assistance will be of much help.
Thanks in advance.

**Comment by srawlins** [comment]
> It seems the weddingRepository, which is an instance of MockFakeWeddingRepository, addWedding method doesn't call the base class method or even never called.

This is true. The method stubs do not execute the super (base) functionality.

> Moreover the `verify(weddingRepository.addWedding(wedding));` check always fails with no interaction error.

What is `wedding`? At first glance, I would think this verification would work with `any`.

**Comment by DonMatano** [comment]
> This is true. The method stubs do not execute the super (base) functionality.
> 
Oh as I assumed. And how do I verify if a function of the super base class is called? Is there a way?

> 
> What is `wedding`? At first glance, I would think this verification would work with `any`.

Sorry I had removed the initialization and assignment of wedding in the process of remove the non essential part of the code for this question. I have edited it in.

**Comment by srawlins** [comment]
> And how do I verify if a function of the super base class is called? Is there a way?

No, this would be a "test spy," which Mockito does not support. You would write a class something like this:

```dart
class MockFakeWeddingRepository extends FakeWeddingRepository {
  int _addWeddingWasCalled = false;
  Future<Wedding> addWedding(Wedding wedding) async {
    _addWeddingWasCalled = true;
    return null;
  }
}
```

> Sorry I had removed the initialization and assignment of wedding in the process of remove the non essential part of the code for this question.

Ah ha, but here is why the `verify` failed. `weddingRepository.addWedding` was not called with the instance of Wedding created in the test case; it was called with the instance of Wedding created in `AddWeddingUseCase.execute`.

**Comment by DonMatano** [comment]
> 
> No, this would be a "test spy," which Mockito does not support. You would write a class something like this:
> 
> ```dart
> class MockFakeWeddingRepository extends FakeWeddingRepository {
>   int _addWeddingWasCalled = false;
>   Future<Wedding> addWedding(Wedding wedding) async {
>     _addWeddingWasCalled = true;
>     return null;
>   }
> }
> ```
> 
Yep this make sense. I was already thinking along that way. I guess `spy` may be a future feature request. Looking at the changelog it seems it was scrap off before.
> 
> Ah ha, but here is why the `verify` failed. `weddingRepository.addWedding` was not called with the instance of Wedding created in the test case; it was called with the instance of Wedding created in `AddWeddingUseCase.execute`.
>
True Makes sense. I am verifying two different instances. Thanks. 👍

**Comment by srawlins** [comment]
Yeah, we may be able to consider Spies with a new code generation API we're cooking up. Glad to help.
