### ISSUE TITLE
Why doesn't  thenReturn support invocation ?

### ISSUE THREAD

**Issue by DanielCardonaRojas** [dart-lang/mockito#251]
This might be just my own ignorance but why are the API's for thenAnswer and thenReturn different ? Its seems that the only difference should be that one is asynchronous while the other synchronous, and therefore have the same api.

I was expecting to do something like: 

```dart

when(obj.someMethod(any)).thenReturn((invocation) => .....)
```

But thenReturn doesn't take a function (invocation) => value, but instead just the value.

**Comment by srawlins** [comment]
The argument passed to `thenReturn` will be returned by the method stub. It would be onerous to require users to always write a callback (as in `thenAnswer`) when they want to return a static value which does not depend on the invocation.

**Comment by DanielCardonaRojas** [comment]
So what is the alternative workaround to have the same effect and inspect the argument ? 

This is something that would be required to create a spy for instace.

**Comment by srawlins** [comment]
If you wish to specify a return value based on an argument, you use `thenAnswer`:

```dart
when(a.b(any)).thenAnswer((Invocation invocation) {
  return invocation.positionalParameters.first * 2;
});

a.b(3); // returns 6.
```
