### ISSUE TITLE
mockito not official product?

### ISSUE THREAD

**Issue by allentv** [dart-lang/mockito#253]
The last line of the README says `NOTE: This is not an official Google product`. This repo being part of `dart-lang` org, I would assume it is an official package. Is it not? Curious to know the details.

**Comment by srawlins** [comment]
It is not an official product. I'm not sure what constitutes an official product, only that this Dart package is not one.

**Comment by natebosch** [comment]
cc @mit-mit - curious if we have any official policy on this type of disclaimer

**Comment by mit-mit** [comment]
@allentv sorry about the confusion, this package indeed is part of the Dart open source project. I'm removing the verbiage in https://github.com/dart-lang/mockito/pull/256
