### ISSUE TITLE
verifyInOrder should not pass when it's not verifying the order

### ISSUE THREAD

**Issue by tp** [dart-lang/mockito#262]
I had test code like this:

```dart
verify(cat.burp());
verify(cat.eatFood("Milk"));
```

Since burping should happening after eating, I though I'd assert the order of invocation.

Initially I migrated to this version to check that if would fail with the wrong order of calls. To my surprise it passed:

```dart
verifyInOrder([
  verify(cat.burp());
  verify(cat.eatFood("Milk"));
]);
```

Only after re-reading the docs, my implementation, and then the test code again did it occur to me that the "inner `verify`s" shouldn't be there.

Once I remove the `verify` the test failed as expected.

Is there any way it could've failed earlier though, when I passed the `verify` instead of the plain mock calls?

**Comment by srawlins** [comment]
Good catch. The `verify` calls should have caught that a verification was in progress.

**Comment by rohan20** [comment]
@tp Thank you! You saved my day ⭐ 

> Only after re-reading the docs, my implementation, and then the test code again did it occur to me that the "inner verifys" shouldn't be there.

**Comment by thiagozg** [comment]
This verification seems to solve the problem, WDYT?
https://github.com/thiagozg/mockito/commit/8e66e57c69ac133703dcf539d92527df7c30ccbc

**Comment by srawlins** [comment]
Mockito 5.0.0 ships with fixes to this bug, and new features on `verifyInOrder`.
