### ISSUE TITLE
How can I mock an extension from a class?

### ISSUE THREAD

**Issue by dacianf** [dart-lang/mockito#265]
I've created an extension on a class and I want to mock that extension.
Here is the mock
`class MockLocation extends Mock implements Location {}`
Here is the extension's signature
`Stream<bool> isCurrentLocationInRange(GeolocationModel geofence,
      {double rangeInMeters = _maxGeofenceDistance})`
And here is where I try to mock the extension's result
`when(
      _locationManager.isCurrentLocationInRange(
        any,
        rangeInMeters: anyNamed("rangeInMeters"),
      ),
    ).thenAnswer((_) => Stream.value(true));`

Using this setup I get the following error:
> Invalid argument(s): An ArgumentMatcher was declared as named rangeInMeters, but was not passed as an argument named rangeInMeters.

Am I doing something wrong? Or how could I solve this problem?

I'm using Flutter v1.17.5, Dart v2.8.4 and Mockito v4.1.1

**Comment by srawlins** [comment]
Sorry that the error message is not clear. But basically, extensions cannot be mocked. There is explanation in the FAQ. https://github.com/dart-lang/mockito/blob/master/FAQ.md#how-do-i-mock-an-extension-method
