### ISSUE TITLE
Export package:test_api's Fake after test_api is published

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#266]
After https://github.com/dart-lang/test/pull/1304 lands, and a version of test_api is published, mockito should remove its own Fake and instead export _that_ Fake.

At which point the following changes also need to be made:

* [ ] set the minimum SDK version to 2.10.0-dev.0.0 (or however that trailing number is written), as test_api will only support 2.10.0-dev
* [ ] opt all files _out_ of Null safety.

**Comment by srawlins** [comment]
cc @stereotype441 @natebosch @jakemac53

**Comment by jakemac53** [comment]
Note that you don't technically _need_ to set the min SDK, and I would probably recommend not doing so. The downside is you can't actually test whatever your min sdk constraint is, but manually opting out all the libraries is i think worse than that (incurs more technical debt and has more potential for issues later on).

**Comment by stereotype441** [comment]
FYI, test_api was just published today: https://pub.dev/packages/test_api/versions/0.2.19-nullsafety, so I believe this task is now unblocked.

**Comment by srawlins** [comment]
Forgive my ignorance. How do I require that version of test_api in mockito's pubspec?

**Comment by stereotype441** [comment]
> Forgive my ignorance. How do I require that version of test_api in mockito's pubspec?

Just checked with @jakemac53 on this.  He says to use: `test_api: '^0.2.19-nullsafety'`

**Comment by srawlins** [comment]
This has landed internally.

**Comment by srawlins** [comment]
This has been published as mockito 4.1.2.
