### ISSUE TITLE
No docs for mockito 4.1.2

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#273]
Mockito 4.1.2 was released, depending on `test_api >=0.2.19-nullsafety which requires SDK version >=2.10.0-0 <2.10.0`, so docs cannot be built, using the current stable release, 2.9.0.

**Comment by srawlins** [comment]
Half due to https://github.com/dart-lang/pub-dev/issues/2762

**Comment by okayfine** [comment]
I'm still facing this issue since I'm using bloc_test package. To remove the error I'm using bloc_test version 7.0.0 and mockito 4.1.1

**Comment by srawlins** [comment]
Looks like we have docs for 4.1.3.
