### ISSUE TITLE
How to avoid throwOnMissingStub in generated mocks?

### ISSUE THREAD

**Issue by ova2** [dart-lang/mockito#295]
We use mockito's code generation. The generated code looks like e.g. as

```dart
/// A class which mocks [ShasLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockShasLogger extends _i1.Mock implements _i3.ShasLogger {
  MockShasLogger() {
    _i1.throwOnMissingStub(this);
  }
}
```

`throwOnMissingStub` overwrites default "null response" on mock.

```dart
void throwOnMissingStub(Mock mock) {
  mock._defaultResponse =
      () => CallPair<dynamic>.allInvocations(mock._noSuchMethod);
}
```

I know, this is because of "Null Safety" since Dart 2.10. But now, we always should stub the methods which could be potentially called on mock. Like this

```dart
    when(_logger.info(any)).thenReturn(null);
    when(_logger.debug(any)).thenReturn(null);
    when(_logger.error(any)).thenReturn(null);
    when(_logger.warning(any)).thenReturn(null);
```

Otherwise, a "noSuchMethod" exception will be called on any method which was not stubed with `when(...).then...`, but invoked.

This is not how Mockito in Java works. Is there any possibility to avoid a lot of stubbing on mock and only stub methods to be verified in tests? I just want to have a behavior which mockito had before the "Null Safety" feature was introduced.

**Comment by srawlins** [comment]
See the "old missing stub behavior" in the README: https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#old-missing-stub-behavior
