### ISSUE TITLE
Generator doesn't generate stubs for inherited methods

### ISSUE THREAD

**Issue by simolus3** [dart-lang/mockito#297]
Considering an input like

```dart
//@dart=2.12
import 'package:mockito/annotations.dart';

abstract class A {
  String a(String nonNullableArg);
}

@GenerateMocks([B])
abstract class B extends A {
  String b();
}

```

The generator outputs

```dart
class MockB extends _i1.Mock implements _i2.B {
  MockB() {
    _i1.throwOnMissingStub(this);
  }

  String b() => super.noSuchMethod(Invocation.method(#b, []), '');
}
```

This makes it impossible to mock `A.a()`. I can submit a PR to fix this is the desired behavior is to consider all methods.

**Comment by srawlins** [comment]
What inherited methods are you expecting to see?

**Comment by srawlins** [comment]
Should `B` extend `A`?

**Comment by simolus3** [comment]
Ah sorry - yes it should, but that doesn't change the generated output.

**Comment by simolus3** [comment]
I have a fix [here](https://github.com/dart-lang/mockito/compare/master...simolus3:generate-inheritance?expand=1) but I'm rather unhappy with the implementation. I couldn't figure out a good way to merge inherited methods, so it wouldn't support something like

```dart
abstract class A {
  String foo();
}

abstract class B {
  String foo({required String x});
}

// should be able to generate a mock interface for this, with an optional parameter
abstract class C implements A, B {}
```

I think the analyzer has `InheritanceOverrideVerifier` for this, but its private.

**Comment by srawlins** [comment]
Thanks for the fix! I can work on a solution, as I think it will be a pain to get the tests passing. They're not written very well now, but I've learned a new technique of asserting things with build_test.

**Comment by srawlins** [comment]
I've landed fixes for this, including support for mixins. It will sync to GitHub this coming week.

**Comment by simolus3** [comment]
@srawlins I tried the version from the GitHub sync and it works - thanks! Since you currently have a PR open, can you also raise the upper bound of the `analyzer` dependency to support `0.41.x`?
I changed that locally, ran `dart pub upgrade` and `dart test` without any failures so it doesn't look like `mockito` is affected by 0.41 breaking changes. I can open a PR myself if that's easier for you, but I thought it might cause more hassle with the ongoing sync.
