### ISSUE TITLE
Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?

### ISSUE THREAD

**Issue by chinkysight** [dart-lang/mockito#303]
```dart
class MockResponse extends Mock implements Response {}

void main() {
  MockResponse response = MockResponse();
  test("description", () {
  when(response.name).thenReturn("Myra");
  });
}
```
I have a very simple test, when I try to stub the getter method `response.name` I got the following exception: **``Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?``**

**Comment by srawlins** [comment]
Can you show me the API of `Response`? Is `name` a method or a getter?

**Comment by chinkysight** [comment]
> Can you show me the API of `Response`? Is `name` a method or a getter?

It's a getter

**Comment by srawlins** [comment]
Mockito can stub getters. It just seems like it's perhaps a method. Can you show me the code declaring Response.name?

**Comment by chinkysight** [comment]
```dart 
class Response{
  String _name = "Ryan";
  String get name => _name;
}
```

**Comment by srawlins** [comment]
Sorry, this works for me:

```none
$ dart a.dart 
00:00 +0: description

00:00 +1: All tests passed!

srawlins-macbookpro:dart-mockito srawlins$ cat a.dart 
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

class MockResponse extends Mock implements Response {}

void main() {
  MockResponse response = MockResponse();
  test("description", () {
  when(response.name).thenReturn("Myra");
  });
}

class Response {
  String _name = "Ryan";
  String get name => _name;
}
$ dart a.dart 
00:00 +0: description

00:00 +1: All tests passed!
```

Can you tell me what version of mockito and of the Dart SDK you are using?

**Comment by chinkysight** [comment]
> Sorry, this works for me:
> 
> ```
> $ cat a.dart 
> import 'package:mockito/mockito.dart';
> import 'package:test/test.dart';
> 
> class MockResponse extends Mock implements Response {}
> 
> void main() {
>   MockResponse response = MockResponse();
>   test("description", () {
>   when(response.name).thenReturn("Myra");
>   });
> }
> 
> class Response {
>   String _name = "Ryan";
>   String get name => _name;
> }
> $ dart a.dart 
> 00:00 +0: description
> 
> 00:00 +1: All tests passed!
> ```
> 
> Can you tell me what version of mockito and of the Dart SDK you are using?

My code looks like this : 



```dart
class Response {
  String _name = "Ryan";
  String get name => _name;
}
```

```dart
import 'package:flutter_practice/response.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

class FakeResponse extends Fake implements Response {
  @override
  String get name => "Tenzin";
}
void main() {
  FakeResponse fakeResponse = FakeResponse();

  test("description", () {
    when(fakeResponse.name).thenReturn("Dolma");
  });
}
```
I forgot to tell you that I was using a `Fake` class. I am currently using `mockito: ^4.1.3` which is the latest version and this is the result of `flutter doctor -v`: 

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/chinkysight/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/chinkysight/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by srawlins** [comment]
The Fake class does not have the mocking abilities that the Mock class provides. You cannot stub methods on a Fake class, nor verify method calls on a Fake class.

**Comment by chinkysight** [comment]
> The Fake class does not have the mocking abilities that the Mock class provides. You cannot stub methods on a Fake class, nor verify method calls on a Fake class.

Ahhh is that so, thank you so much for your help :1st_place_medal:
