### ISSUE TITLE
How to setup calling a function on a mock with a mock as parameter (with NNBD)?

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/mockito#306]
Using 5.0.0-nullsafety.0.

I have a class `Foo` and a class `Bar` which I want to mock for use in the class I want to test. Both classes interact with each other. Before nullsafety I could simply set this up, but I'm not sure how I am supposed to do that post-NNBD because mockito itself uses methods on the mocks that aren't mocked and I don't think I should mock stuff so mockito works.

Example:
```dart
// foobar.dart
class Foo {
  String process(Bar bar) => 'result';
}

class Bar {}

// foobar_test.dart
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

import 'package:foobar/foobar.dart';
import 'world_test.mocks.dart';

@GenerateMocks([
  Foo,
  Bar
], customMocks: [
  MockSpec<Foo>(as: #MockFoo2, returnNullOnMissingStub: true),
  MockSpec<Bar>(as: #MockBar2, returnNullOnMissingStub: true),
])
void main() {
  test('default mock', () {
    final foo = MockFoo();
    final bar = MockBar();
    when(foo.process(bar)).thenReturn('mockedResult');

    foo.process(bar);
  });
  test('null mock', () {
    final foo = MockFoo2();
    final bar = MockBar2();
    when(foo.process(bar)).thenReturn('mockedResult');

    foo.process(bar);
  });
}
```

The code fails in the `foo.process(bar);` line.

The resulting error of the `default mock` test is: `NoSuchMethodError: Object has no == method accepting arguments (_)`

The resulting error of the `null mock` test is: `type 'Null' is not a subtype of type 'bool'`

The important part of the stacktrace is this:
```
test\foobar_test.mocks.dart 62:13      MockBar2.==
package:collection/src/equality.dart 87:45          DefaultEquality.equals
package:collection/src/equality.dart 458:18         DeepCollectionEquality.equals
package:mockito/src/invocation_matcher.dart 184:18  _MatcherEquality.equals
package:collection/src/equality.dart 177:29         ListEquality.equals
package:mockito/src/invocation_matcher.dart 158:12  _InvocationMatcher.matches
package:mockito/src/mock.dart 141:27                Mock.noSuchMethod.<fn>
```

If I do something stupid like `when(bar == bar).thenReturn(true);` I'll just get a stackoverflow.

**Comment by srawlins** [comment]
Great catch. This is related to #305, in which it is requested that `Object.==` be auto-stubbed instead of throwing.

> The resulting error of the default mock test is: `NoSuchMethodError: Object has no == method accepting arguments (_)`

Right, so without the `returnNullOnMissingStub` feature, mockito has called `MockBar.==`, which used to return null (unless you called `throwOnMissingStub`) and now throws, unless you'd stubbed `==`. We might be able to tiptoe around `==` with an `is` check or an `identical` call or something... Hopefully we can make a solution that doesn't involve new code for you to write, like a stub.

> The resulting error of the null mock test is: `type 'Null' is not a subtype of type 'bool'`

This test uses the old behavior (`returnNullOnMissingStub`), in which `null` is returned for `MockBar.==`. Fixing the above case might fix this, but generally speaking, this is why the default behavior is changed; `null` is no longer the safe return value it once was.

**Comment by denniskaselow** [comment]
I wouldn't call `returnNullOnMissingStub` the old behavior because those tests work with stable mockito. Things like `==`, `runtimeType` and `toString()` never returned `null`. They just used the real implementation of the `Mock` or `Object` class and couldn't even be stubbed.

**Comment by denniskaselow** [comment]
Those functions/operators still exist on the `Mock` class (https://github.com/dart-lang/mockito/blob/master/lib/src/mock.dart#L160) and are maybe overridden by mistake because of issue#297?

**Comment by srawlins** [comment]
@denniskaselow You're completely right. The solution is to stop overriding any methods defined by `Mock` or inherited by `Mock`, (`get hashCode`, `operator ==`, `toString()`, `get runtimeType`).

**Comment by srawlins** [comment]
This is fixed in 5.0.0-nullsafety.1.

**Comment by radvansky-tomas** [comment]
I have still this issue in 5.0.0
`
'Object.==' ('bool Function(Object)') isn't a valid concrete implementation of 'CollectionReference.==' ('bool Function(dynamic)').`

**Comment by srawlins** [comment]
@radvansky-tomas  I don't think your error is related to this issue.

**Comment by milanobrenovic** [comment]
I still have this issue in mockito ^5.0.14

```
Add a stub for this method using Mockito's 'when' API, or generate the mock for MockIDatasource with 'returnNullOnMissingStub: true'.
```

**Comment by srawlins** [comment]
@milanobrenovic I don't see any reason why your issue is related to this one. Feel free to open a new bug with a minimal reproduction case.
