### ISSUE TITLE
[question] Can I call real method on a mock?

### ISSUE THREAD

**Issue by rasuru** [dart-lang/mockito#313]
Is there a partial use of the class which is implemented as `spy` in Java's Mockito?

And, can I verify if the real method was called?

**Comment by srawlins** [comment]
Sorry no. You will have to implement your own spies by extending your class.

**Comment by kjawadDeveloper1** [comment]
How to implement spies?

**Comment by fzyzcjy** [comment]
+1 this is very much needed feature...

**Comment by JulianBissekkou** [comment]
Can we reopen the issue and maybe discuss why this feature is not beeing implemented?
I can understand that this is quite complex, but as other people said its a needed feature...
