### ISSUE TITLE
Non-nullable returns for argument matchers

### ISSUE THREAD

**Issue by thiagozg** [dart-lang/mockito#333]
At the moment, all the argument matcher functions are returning `Null` on the function, with the dart null safety, it will be not possible to use Mockito on non-nullable parameters, because it generates a compilation error:

For example:
```dart
class _RealClass {
  String? methodWithNormalArgs(int x) => 'Real';
}

mock.methodWithNormalArgs(argThat(greaterThan(100))
```
Results:
```
error: The argument type 'Null' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [mockito] test/verify_test.dart:153)
```
I was thinking about the possibility to create a default value and return it instead of `Null`.

**Comment by srawlins** [comment]
Have you looked at the [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md)?

**Comment by thiagozg** [comment]
Hi @srawlins, thanks for your reply.

I have read it, great documentation by the way, but I was thinking here, the second solution may require too many efforts during a migration on a project that uses Mockito on a large scale, and generate code it's helpfull, but some people don't like to deal with it, since it might generate hidden errors and generates a lot of code at the compilation time.

The possibility to use reflection and create a default instance was already discarded at some point? I can help on that.

**Comment by natebosch** [comment]
> The possibility to use reflection and create a default instance was already discarded at some point? I can help on that.

I'm not sure if we ever discussed using reflection specifically. I don't think it would be worth the effort to try - I strongly suspect that we won't find a complete enough solution, and I think an incomplete solution could be even more painful. Even with a contributed solution we'd not likely be able to accept it and the maintenance burden.

Solutions that use reflection will run into a number of issues:
- `dart:mirrors` don't work on the web or native compiles (flutter) so we'd have to be careful to use conditional imports which adds to the complexity and reduces the utility.
- We likely can't construct a reasonable default value for 100% of classes, and especially so if the language starts to add support for things like `sealed`.

I think the highest leverage we will have here will be to make it easier to discover when this is happening and guide users towards the supported approaches.

**Comment by srawlins** [comment]
> We likely can't construct a reasonable default value for 100% of classes

I think this is the hardest part of using mirrors. Constructing a Foo may be very hard, and you cannot declare a new class with mirrors.

Note also #286 is a discussion on alternatives to code generation.

**Comment by srawlins** [comment]
> Is it bad practice to use @GenerateMocks in the file of the testable class like this?

Yes, if the library foo.dart is part of your application. This test infrastructure should not leak into your Flutter application.

> It's convenient to have a single mock class for all tests, but does this affect the size of the app (for example, Flutter) after building?

Yes, it will affect the size of the app.

**Comment by srawlins** [comment]
The solution to the original problem is to use the solutions in the null safety readme. For alternatives see #286 and #347.
