### ISSUE TITLE
Regression: Cannot call `when` from inside of a static method or extension method

### ISSUE THREAD

**Issue by SupposedlySam** [dart-lang/mockito#344]
## Request

I would like for the ability to set up all of my mocks inside of an external function to make the mocked class reusable across files.

Note: I've been using extension methods successfully in previous versions of Mockito (4.1.1 specifically)

## The Problem
Currently, if you try to create a utility class or use an extension, errors are returned when you try to use the helper function.

## Code Example
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

class MockPerson extends Mock implements Person {}

extension MockPersonExtension on MockPerson {
  void initialize() => when(name).thenReturn("MockedName");
}

class MockPersonUtility {
  static void initialize(MockPerson mockPerson) =>
      when(mockPerson.name).thenReturn("MockedName");
}

void main() {
  test('test extension setup', () {
    final mockPerson = MockPerson()..initialize();  // Error: type 'Null' is not a subtype of type 'String'

    expect(mockPerson.name, "MockedName");
  });

  test('test utility setup', () {
    final mockPerson = MockPerson();
    MockPersonUtility.initialize(mockPerson);  // Error: Bad state: Cannot call `when` within a stub response

    expect(mockPerson.name, "MockedName");
  });
}

class Person {
  final String _name = "RealName";
  String get name => _name;
}

```

### Package Version
mockito: ^5.0.0

### Flutter Doctor
<details><summary>Expand</summary>
<p>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.1, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)

• No issues found!
```

</p>
</details>

### SDK
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"

**Comment by srawlins** [comment]
The error messages you are seeing indicates you are not using Mockito properly in null safe Dart. Please read [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md). Please update here if your issue is still relevant even when using null safe mocks.

**Comment by SupposedlySam** [comment]
Thanks for pointing me to this @srawlins!

Looking at the new way that Mockito generates Mocks for you I've come up with a solution.

## Goals

1. Create a uniform way of mocking dependencies via an extension method called `setValues`
2. Eliminate duplicate mock classes (even though they're generated for you)
3. Allow for a single import to provide all mock possibilities

## Solution

1. Create a `mocks` folder under `test`
2. add a file called `test.dart` with the correct annotation for all classes needing to be mocked in my test suite
```dart
// test.dart
...
import 'package:mockito/annotations.dart';

@GenerateMocks([FirebaseCoreService, LocalDataSource, StartupService])
void main() {}
```

3. Run the command `flutter packages pub run build_runner build --delete-conflicting-outputs` with the latest version of `build_runner` package
4. Connect the newly generated `test.mocks.dart` file to my extension files
<details><summary>View Code</summary>
<p>

```dart
// mock_firebase_core_service_extension.dart
...
import 'test.mocks.dart';

extension MockFirebaseCoreServiceExtension on MockFirebaseCoreService {
  void setValues({AsyncValue<Null>? initializeReturnValue}) {
    final initializeValue = initializeReturnValue ?? AsyncValue.data(null);

    when(initialize()).thenAnswer(
      (_) => Future.value(initializeValue),
    );
  }
}

// mock_local_storage_extension.dart
...
import 'test.mocks.dart';

extension MockLocalStorageExtension on MockLocalDataSource {
  void setValues({AsyncValue<Null>? initializeReturnValue}) {
    final initializeValue = initializeReturnValue ?? AsyncValue.data(null);

    when(initialize()).thenAnswer(
      (_) => Future.value(initializeValue),
    );
  }
}

// mock_startup_service_extension.dart
...
import 'test.mocks.dart';

extension MockStartupServiceExtension on MockStartupService {
  void setValues({AsyncValue<Null>? generateReturnValue}) {
    final generateValue = generateReturnValue ?? AsyncValue.data(null);

    when(generateAndStoreSecretIfNotExists())
        .thenAnswer((_) => Future.value(generateValue));
  }
}
```

</p>
</details>

5. Create an `imports.dart` file to export all the necessary mocks and extension methods so I can just import this one file inside of my tests

```dart
// imports.dart
export 'test.mocks.dart';
export 'mock_firebase_core_service_extension.dart';
export 'mock_local_storage_extension.dart';
export 'mock_startup_service_extension.dart';
```

Now all I need to do is import my new file and set my values!

```dart
...
import 'mocks/imports.dart';

void main() {
  late Widget widget;
  late MockFirebaseCoreService mockFirebaseCoreService;
  late MockLocalDataSource mockLocalStorage;
  late MockStartupService mockStartupService;

  setUp(() {
    mockFirebaseCoreService = MockFirebaseCoreService()..setValues();
    mockLocalStorage = MockLocalDataSource()..setValues();
    mockStartupService = MockStartupService()..setValues();
    widget = ProviderScope(
      overrides: [
        fbCoreProvider.overrideWithProvider(
          Provider((ref) => mockFirebaseCoreService),
        ),
        localStoreProvider.overrideWithProvider(
          Provider((ref) => mockLocalStorage),
        ),
        startupProvider.overrideWithProvider(
          Provider((ref) => mockStartupService),
        )
      ],
      child: AppLoad(),
    );
  });

...

```

**Comment by hiteshsapra** [comment]
This question isn't closed. because getting one issue. Please help me. Re: below error.

returns a Post if the http call completes successfully [E]
  type 'Null' is not a subtype of type 'Future<Response>'

**Comment by srawlins** [comment]
@hiteshsapra please file a new issue for the problem you are seeing, with a complete minimal reproduction case, the expected output, and the actual output.
