### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by isorensen** [dart-lang/mockito#348]
Hello! thanks for the awesome package.

Dart 2.12 and flutter 2.0.0 are now in stable with the null-safety feature.

Migrating this package to null-safety would help a lot. :)

Here's an official guide from dart doc
https://dart.dev/null-safety/migration-guide

**Comment by srawlins** [comment]
Mockito 5.0.0 is already null safe. https://github.com/dart-lang/mockito/blob/master/CHANGELOG.md

**Comment by rlazom** [comment]
If the plugin has "null safety support" why it doesn't show the null safety badge on [pub.dev](https://pub.dev/packages/mockito)?

**Comment by srawlins** [comment]
A valid question! @jonasfj can you tell if mockito needs to do something specific to get the "null safety" badge?

**Comment by srawlins** [comment]
That page is very cool! Thanks Jonas.
