### ISSUE TITLE
'Object.==' ('bool Function(Object)')

### ISSUE THREAD

**Issue by radvansky-tomas** [dart-lang/mockito#354]
I see this a lot when I am trying to mock firebase libs:

`'Object.==' ('bool Function(Object)') isn't a valid concrete implementation of 'Reference.==' ('bool Function(Object?)').`

And thats because of their:
```
 @override
  bool operator ==(Object? other) =>
      other is Reference &&
      other.fullPath == fullPath &&
      other.storage == storage;
```

Any idea how to use generator for such thing ?

**Comment by srawlins** [comment]
Oooh yikes. That's not great. [Object.==](https://api.dart.dev/stable/2.12.0/dart-core/Object/operator_equals.html) indeed accepts a non-nullable `Object` as an argument. It is a bit strange that Reference would expand that parameter type to be `Object?`. I don't think we can or perhaps should support mocking classes which change the types of Object's method parameters...

**Comment by radvansky-tomas** [comment]
Thats not only reference, there are plenty classes under flutter fire, which has same issue this is documentReference:

```
  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(dynamic other) =>
      other is DocumentReference &&
      other.firestore == firestore &&
      other.path == path;
```

A saw more with storage, etc..

**Comment by srawlins** [comment]
I suggest opening bugs against those packages, perhaps asking why they expanded the parameter type on the `==` operator. It may be accidental.

**Comment by srawlins** [comment]
This should be fixed in mockito 5.0.10.

**Comment by MoustafaMesbah** [comment]
issue still existed in mockito 5.0.10

**Comment by cedvdb** [comment]
on 5.0.14 it is an issue when trying to mock just_audio AudioPlayer

**Comment by Samin-youki** [comment]
@srawlins any update in this?

**Comment by ihorvitruk** [comment]
@srawlins I have the same issue with google_sign_in plugin.
```
 class MockGoogleSignInAccount_ extends _i1.Mock 'Mock.==' ('bool Function(Object)') isn't a valid concrete implementation of
                                                    'GoogleSignInAccount.==' ('bool Function(dynamic)'). #invalid_implementation_override
```

This is because `==` operator takes dynamic argument for `GoogleSignInAccount` class:
```
@override
  bool operator ==(dynamic other) {
    ...
```

Insight: It (generated mock) used to work until I performed migration of the package to null-safety.


@Samin-youki The workaround is to temporarily use stub for your `EtherAmount` with override `==` and `hashCode`:

```
class _TestEtherAmount implements EtherAmount {
 @override
  bool operator ==(dynamic other) =>
      other is EtherAmount ? super == other : false;

  @override
  int get hashCode => super.hashCode;

  ...
```
