### ISSUE TITLE
Flip mockito.dart with mockito_no_mirrors.dart

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mockito#36]
I think it would be worth it just to have `package:mockito/mockito.dart` not include mirrors.

The only extra function Mockito provides for mirrors users is `spy`:

``` dart

dynamic spy(dynamic mock, dynamic spiedObject) {
  var mirror = reflect(spiedObject);
  setDefaultResponse(
      mock,
      () => new CannedResponse(null,
          (Invocation realInvocation) => mirror.delegate(realInvocation)));
  return mock;
}
```

I am not even sure there _is_ usage of this and could be convinced to just remove it.

/cc @srawlins @TedSander

**Comment by srawlins** [comment]
I like the idea of 2-stepping it.

* 1.2.0: flip `mockito{,_no_mirrors}.dart`
* 1.3.0: remove mirrors if we don't need it.

**Comment by matanlurey** [comment]
+1 to 2-step. Just wanted the buy-in (I'll wait for Ted before starting)

**Comment by TedSander** [comment]
Spy is actually used but not much just a couple of instances from the code I can see.

I think it isn't that much of a burden to keep it for now. I do agree we should flip the default.

**Comment by srawlins** [comment]
No flipping the default?

**Comment by matanlurey** [comment]
Closed on accident.

**Comment by matanlurey** [comment]
So this already was flipped in `2.0.0-dev` - this needs to be merged internally.

**Comment by matanlurey** [comment]
I believe @srawlins is merging internally.

**Comment by srawlins** [comment]
@matanlurey made the flip in 2.0.0-dev dc8ce18d6e1096d2546d1ef5afe417cd9e042aee.
