### ISSUE TITLE
null-safety question

### ISSUE THREAD

**Issue by ammaratef45** [dart-lang/mockito#360]
The version that supports null safety is a stable release now but pub website doesn't show the `Null Safety` mark next to it as other packages!

**Comment by srawlins** [comment]
See this comment: https://github.com/dart-lang/mockito/issues/348#issuecomment-796853318

**Comment by ammaratef45** [comment]
@srawlins Is there a ticket that tracks that in `source_gen`? what is the plan to make sure that your package is supporting `null-safety`?

**Comment by srawlins** [comment]
Here is the ticket. https://github.com/dart-lang/source_gen/issues/493

 I'm not sure what their plans are.
