### ISSUE TITLE
v5.0.0 doesn't seem to work with null safety

### ISSUE THREAD

**Issue by eggnstone** [dart-lang/mockito#361]
Using
- Flutter 2.0.1
- Dart 2.12.0
- Mockito 5.0.0

This simple example

```
abstract class C
{
    int square(int x) <-- runtime error points here
    => x * x;
}

class MockC extends Mock
    implements C
{}

test('1', ()
{
    C c = MockC();
    when(c.square(1)); <-- runtime error points here
});
```
produces

`type 'Null' is not a subtype of type 'int'`

**Comment by srawlins** [comment]
Please read the [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md).
