### ISSUE TITLE
How to stub the equality operator?

### ISSUE THREAD

**Issue by eggnstone** [dart-lang/mockito#365]
How can I stub the equality operator?
Neither compile:
```
when(mock.==(obj));
when(mock.operator==(obj));
```

**Comment by srawlins** [comment]
@eggnstone can you explain or paste why they don't compile?

**Comment by eernstg** [comment]
`mock.==(obj)` is a Scala style operator invocation, Dart doesn't support that. The syntax to invoke `operator ==` is simply `e1 == e2`, so you could try `when(mock == obj)`.

**Comment by eggnstone** [comment]
@eernstg 
```
when(mock == any);
when(mock == obj); // same result
Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?
```

@srawlins 
```
when(mock.operator == any);
when(mock.operator==(any)); // same result
error: The getter 'operator' isn't defined for the type 'MockC'. (undefined_getter at [xyz])
```

```
when(mock.== any);
when(mock.==(any)); // same result
error: Expected an identifier. (missing_identifier at [xyz])
```

**Comment by srawlins** [comment]
To remove some confusion:

1. `mock.operator== any)` is parsed as `mock` (an expression) followed by `.operator`, calling the `operator` getter on `mock` (which there is none), and comparing the result of `mock.operator`, via `==` to `any`. This is not what you want to do. This error is unrelated to mockito.
2. `mock.== any` just doesn't parse, as @eernstg said. It's a syntax error unrelated to mockito. `mock.` (an expression followed by .) should be followed by an identifier, like `mock.isEven`, not `==`.

**Comment by srawlins** [comment]
> when(mock == obj); // same result

> Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?

This shows that `==` cannot be stubbed with mockito. The Mock class [overrides `Object ==`](https://github.com/dart-lang/mockito/blob/master/lib/src/mock.dart#L196) with its own implementation, which is called when you run `mock==any`, rather than the stubbing logic.

I'm not sure if we can support stubbing the `==` operator...

**Comment by cohenadair** [comment]
I'm running into the same issue because I'm using mocked objects in a `Set`.

> I'm not sure if we can support stubbing the `==` operator...

I hope there's something that can be done. It's very inconvenient having to create custom "subclass" mocks for this purpose.

**Comment by srawlins** [comment]
I don't think there is any way we can support stubbing the equality operator.
