### ISSUE TITLE
emitsInOrder doesn't work correctly on try/catch sentence

### ISSUE THREAD

**Issue by EhiltonKazuo** [dart-lang/mockito#372]
I followed some course and I am new in mockito.

I google it, but i can't find something helpful with my problem.

I made two tests with streams: isLoadingStream, anyErrorStream. Inside the doSomething method has two states for isLoading: true and false. True when it is before the someMethod executes and running the outside of the try/catch operator. False when complete the try/catch operator.

When i test for happy path is compile normally, but for the fail test isn't apply correcty.

Am i doing wrong? 

Sorry for any mistakes. English is not my native language

This is the sample of the code:
```
import 'dart:async';

import 'package:test/test.dart';
import 'package:mockito/mockito.dart';

enum SomeError {
  anyError,
}

class AnyState {
  bool isLoading = false;
  String anyError;
}

abstract class AnyPresenter {
  Stream<bool> get isLoadingStream;
  Stream<String> get anyErrorStream;

  void doSomething();
}

class StreamAnyPresenter implements AnyPresenter {
  final AnyLibrary anyLibrary;

  var _controller = StreamController<AnyState>.broadcast();
  var _anyState = AnyState();

  StreamAnyPresenter(this.anyLibrary);

  Stream<bool> get isLoadingStream =>
      _controller.stream.map((anyState) => anyState.isLoading);
  Stream<String> get anyErrorStream =>
      _controller.stream.map((anyState) => anyState.anyError);

  Future<void> doSomething() async {
    _anyState.isLoading = true;
    _controller.add(_anyState);
    try {
      await anyLibrary.someMethod();
    } on SomeError catch (error) {
      if (error == SomeError.anyError) {
        _anyState.anyError = 'Any error';
      }
    }
    _anyState.isLoading = false;
    _controller.add(_anyState);
  }
}

abstract class AnyLibrary {
  Future<void> someMethod();
}

class AnyLibrarySpy extends Mock implements AnyLibrary {}

void main() {
  AnyLibrarySpy anyLibrary;
  StreamAnyPresenter sut;

  setUp(() {
    anyLibrary = AnyLibrarySpy();
    sut = StreamAnyPresenter(anyLibrary);
  });

  PostExpectation mockSomeMethodCall() => when(anyLibrary.someMethod());

  void mockSomeMethod() => mockSomeMethodCall().thenAnswer((_) => null);

  void mockSomeMethodError(SomeError error) =>
      mockSomeMethodCall().thenThrow(error);

  test('Should emit events on Success', () async {
    mockSomeMethod();

    expectLater(sut.isLoadingStream, emitsInOrder([true, false]));

    await sut.doSomething();
  });
  test('Should emit event on AnyError', () async {
    mockSomeMethodError(SomeError.anyError);

    expectLater(sut.isLoadingStream, emitsInOrder([true, false]));
    sut.anyErrorStream.listen((error) => expect(error, 'Any error'));

    await sut.doSomething();
  });
}
```

**Comment by srawlins** [comment]
`thenThrows` happens synchronously. So I think what is happening is, in the "Success" case:

1. `_anyState` is added to the controller
2. `someMethod` is asynchronous, so the call is pushed onto the event loop.
3. `emitsInOrder` gets a value off of the stream, with `isLoading` true.
4. `someMethod` is called, returns normally, and the same `_anyState` object is again added to the controller.
5. `emitsInOrder` gets another value off of the stream, with `isLoading` false.

In the "Failure" case:

1. `_anyState` is added to the controller.
2. `someMethod` is _synchronous_, so is run immediately.
3. `_anyState`'s `isLoading` is set to false.
4.  The same `_anyState` object is again added to the controller. It is now in the stream twice, and as it is the same object, the `isLoading` property on that object is the same for each of the two elements in the stream (false).
5. `emitsInOrder` gets two values off of the stream, with `isLoading` false in each case.

**Comment by EhiltonKazuo** [comment]
So, even though the `_controller` and `_anyState` are outside the try/catch operator can't received true? 

Then, the `emitsInOrder` only triggers if has asynchronous call to pushed it and because the `thenThrows` is synchronous can't pushed into the event loop?

The correct test for "Failure" is:
```
test('Should emit event on AnyError', () async {
    mockSomeMethodError(SomeError.anyError);

    expectLater(sut.isLoadingStream, emitsInOrder([false, false]));
    sut.anyErrorStream.listen((error) => expect(error, 'Any error'));

    await sut.doSomething();
  });
```

**Comment by srawlins** [comment]
`emitsInOrder` (or, whatever is pulling events off of `isLoadingStream`) does not get a chance to see a true `isLoading` value because by the time it pulls the first value off, the `isLoading` value has already changed to false.

The value changes to false before any `isLoadingStream` reads any value off of `_controller`. It's the same as if `doSomething` looked like:

```dart
  Future<void> doSomething() async {
    _anyState.isLoading = true;
    _controller.add(_anyState);
    _anyState.isLoading = false;
    _controller.add(_anyState);
  }
```

I think it is impossible to write code which reads elements from `_controller.stream` and ever get an element with `isLoading` true.

**Comment by EhiltonKazuo** [comment]
So, in any case the `_anyState.isLoading` can't get true in failure case, that means always receive error without any delay to show for user? If so, it's okay. Thanks for the help!
