### ISSUE TITLE
Please upgrade Mockito to use source_gen 1.0.0

### ISSUE THREAD

**Issue by pavanpodila** [dart-lang/mockito#373]
Mockito still depends on `^0.9.6`. It would be great if it could upgrade to the null-safe version of `source_gen`, which is in **`1.0.0`**

**Comment by srawlins** [comment]
Tests are happy with 1.0.0. I'll mail and land this soon.

**Comment by UliPrantz** [comment]
Any updates on this one? Can I probably help anywhere :)

And btw thanks for your create work.

**Comment by srawlins** [comment]
source_gen 1.0.0 is supported at master. pub.dev has been having issues tonight, so I'm going to wait to release until the morning.

**Comment by chrallard** [comment]
Any updates?

**Comment by srawlins** [comment]
published 5.0.3
