### ISSUE TITLE
Problems with any in Packages NullSafety

### ISSUE THREAD

**Issue by toshiossada** [dart-lang/mockito#377]
I've updated packages to nullsaffety version, include mockito, and now I get the following erro
![image](https://user-images.githubusercontent.com/2637049/113345793-55e51f80-9309-11eb-9eaa-627dadb7517c.png)

**Comment by srawlins** [comment]
Please see the README, under [Let's create mocks](https://github.com/dart-lang/mockito#lets-create-mocks).
