### ISSUE TITLE
Test fail when I Throws a exception

### ISSUE THREAD

**Issue by toshiossada** [dart-lang/mockito#384]
I Have a function that throws a Failure
```
  Future getAll() async {
      throw DioFailure(
        message: '',
        statusCode: 400,
      );
  }
```
And I writing a Test to verify if my function are throwing a exception

```
  test('should return a DioFalure from API', () async {
    //arrange
    when(dioMock.get(any))
        .thenThrow(DioFailure(message: 'message', statusCode: 401));

    //act
    Future<List<PeopleModel>> result;

    result = datasource.getAll();
    
    expect(result, throwsA(isA<DioFailure>()));
  });
```
![image](https://user-images.githubusercontent.com/2637049/114916796-978ec380-9dfb-11eb-89bc-9868a4e49496.png)

thats works, but if I put a delay between act and expect the test go fail
```
  test('should return a DioFalure from API', () async {
    //arrange
    when(dioMock.get(any))
        .thenThrow(DioFailure(message: 'message', statusCode: 401));

    //act
    Future<List<PeopleModel>> result;

    result = datasource.getAll();
    
    await Future.delayed(Duration(seconds: 2));
    expect(result, throwsA(isA<DioFailure>()));
  });
```

![image](https://user-images.githubusercontent.com/2637049/114916823-a2e1ef00-9dfb-11eb-8f72-271f35aa01c8.png)

![image](https://user-images.githubusercontent.com/2637049/114916854-abd2c080-9dfb-11eb-8f56-590772091348.png)

**Comment by srawlins** [comment]
I don't think you are using `throwsA` as you expect. See test's documentation. https://pub.dev/packages/test

`expect(result, throwsA(isA<DioFailure>()));`. Since `result` is a Future, not a function. I think in order to catch the error thrown by the test in the second case, you may need `expectAsync`. In either case, I don't think anything points to mockito being the culprit here.

Without having a complete example, it would be hard to diagnose this further.

**Comment by srawlins** [comment]
To speculate a bit, I think that in your second case, the async event loop hits the delayed Future, then `getAll` throws its error, before you ever get to the last line where the error is "expected," so the thrown error escapes the test case.

**Comment by natebosch** [comment]
> I could be wrong. See test's documentation. https://pub.dev/packages/test. `expect(result, throwsA(isA<DioFailure>()));`. Since `result` is a Future, not a function.

It is fine to use `throwsA` to match against a `Future`. Your other comment is correct.

> I think that in your second case, the async event loop hits the delayed Future, then `getAll` throws its error, before you ever get to the last line where the error is "expected," so the thrown error escapes the test case.

Yes, this has to do with whether the `Future` which resolves to an error has a listener when it completes.

This doesn't have anything to do with Mockito. You can demonstrated it with the following:

```dart
void main() {
  test('some test passes', () async {
    var f = Future.error('sad');
    expect(f, throwsA(anything));
    // Passes because the `throwsA` matcher adds an error
    // handler on the Future _synchronously_ before the next microtask.
   }
   
   test('some test fails', () async {
    var f = Future.error('sad');
    await Future(() {});
    // fails because the Future.error completes before
    // there is any error handler - it's only a variable
    // that hasn't been used so far.
    // The unhandled async error makes the overall test fail.
    expect(f, throwsA(anything)); // we reach this line, but the test has already failed.
   }
 }
 ```
 
 You can also replace `expect(f, throwsA(anything));` with `f.catchError((e, st) {});` to ignore the error and it's no longer an unhandled async error.

**Comment by natebosch** [comment]
See also https://dart.dev/guides/libraries/futures-error-handling#potential-problem-failing-to-register-error-handlers-early

I'll add a note about this in the `package:test` README. https://github.com/dart-lang/test/pull/1501

I'll close here since there are no actions to take in Mockito.
