### ISSUE TITLE
Generated Mock returns Future<dynamic> instead of Future<T>

### ISSUE THREAD

**Issue by cadaniel** [dart-lang/mockito#391]
So it looks like Futures always return dynamic instead of the type they're mocking. This causes the compilation error 

    MockCycleEventService.getLastCycleEventWithType' ('Future<dynamic> Function(List<CycleEventType>?)') isn't a valid override of 'CycleEventService.getLastCycleEventWithType' ('Future<CycleEvent?> Function(List<CycleEventType>)').

Class being mocked

    @injectable
    class CycleEventService {
      final CycleEventRepository cycleEventRepository;
      final UserRepository userRepository;
      final CycleSync exerciseSync;
    
      CycleEventService(
          this.cycleEventRepository, this.userRepository, this.exerciseSync);
    
      Future<void> deleteEvent(CycleEvent event) =>
          cycleEventRepository.deleteEvent(event);
    
      Future<void> updateEvent(CycleEvent event) async {
        await cycleEventRepository.saveEvent(event);
      }
    
      Future<void> saveCycleEvent(CycleEventTableCompanion? event) async {
        if (event == null) {
          return;
        }
        await _calculateCycleAverage(event);
        await cycleEventRepository.saveEventCompanion(event);
        exerciseSync.exerciseSync();
      }
    
      Future<CycleEvent?> getLastCycleEventWithType(List<CycleEventType> type) {
        return cycleEventRepository.getLastCycleEventWithType(type);
      }
    
      Future<List<CycleEvent>> getEvents(DateTime start, DateTime end) =>
          cycleEventRepository.getEvents(start, end);
    
      Stream<List<CycleEvent>> getEventsStream(DateTime start, DateTime end) =>
          cycleEventRepository.getEventsStream(start, end);
    
      Future<List<CycleEvent>> getEventsForDay(DateTime day) {
        var start = DateTime(day.year, day.month, day.day, 0, 0);
        var end = DateTime(day.year, day.month, day.day, 23, 59);
        return cycleEventRepository.getEvents(start, end);
      }
    
      Future<void> _calculateCycleAverage(CycleEventTableCompanion newEvent) async {
        var lastCycleEvent = await cycleEventRepository
            .getLastCycleEventWithType([newEvent.cycleEventType.value]);
        if (lastCycleEvent == null) {
          return;
        }
        var user = await userRepository.getUser();
        if (user == null) {
          return;
        } else if (user.cycleLength == null) {
          user = user.copyWith(cycleLength: 28, periodLength: 5);
          userRepository.saveUser(user);
          return;
        }
        var diff = lastCycleEvent.eventDate
            .difference(newEvent.eventDate.value)
            .inDays
            .abs();
        if ((newEvent.cycleEventType.value == CycleEventType.PERIOD_START ||
                newEvent.cycleEventType.value == CycleEventType.PHANTOM_PERIOD) &&
            diff < 36) {
          var newAverage = ((user.cycleLength! * user.cycleLengthCount) + diff) /
              (user.cycleLengthCount + 1);
          user = user.copyWith(
              cycleLength: newAverage.floor(),
              cycleLengthCount: (user.cycleLengthCount + 1));
          userRepository.saveUser(user);
        } else if (newEvent.cycleEventType.value == CycleEventType.PERIOD_END &&
            diff < 15) {
          var newAverage = ((user.periodLength! * user.periodLengthCount) + diff) /
              (user.periodLengthCount + 1);
          user = user.copyWith(
              periodLength: newAverage.floor(),
              periodLengthCount: (user.periodLengthCount + 1));
          userRepository.saveUser(user);
        }
      }
    } 

Mockito generated output

    /// A class which mocks [CycleEventService].
    ///
    /// See the documentation for Mockito's code generation for more information.
    class MockCycleEventService extends _i1.Mock implements _i19.CycleEventService {
      MockCycleEventService() {
        _i1.throwOnMissingStub(this);
      }
    
      @override
      _i3.CycleEventRepository get cycleEventRepository => (super.noSuchMethod(
          Invocation.getter(#cycleEventRepository),
          returnValue: _FakeCycleEventRepository()) as _i3.CycleEventRepository);
      @override
      _i2.UserRepository get userRepository =>
          (super.noSuchMethod(Invocation.getter(#userRepository),
              returnValue: _FakeUserRepository()) as _i2.UserRepository);
      @override
      _i13.CycleSync get exerciseSync =>
          (super.noSuchMethod(Invocation.getter(#exerciseSync),
              returnValue: _FakeCycleSync()) as _i13.CycleSync);
      @override
      _i15.Future<void> deleteEvent(dynamic event) =>
          (super.noSuchMethod(Invocation.method(#deleteEvent, [event]),
              returnValue: Future<void>.value(null),
              returnValueForMissingStub: Future.value()) as _i15.Future<void>);
      @override
      _i15.Future<void> updateEvent(dynamic event) =>
          (super.noSuchMethod(Invocation.method(#updateEvent, [event]),
              returnValue: Future<void>.value(null),
              returnValueForMissingStub: Future.value()) as _i15.Future<void>);
      @override
      _i15.Future<void> saveCycleEvent(dynamic event) =>
          (super.noSuchMethod(Invocation.method(#saveCycleEvent, [event]),
              returnValue: Future<void>.value(null),
              returnValueForMissingStub: Future.value()) as _i15.Future<void>);
      @override
      _i15.Future<dynamic> getLastCycleEventWithType(
              List<_i16.CycleEventType>? type) =>
          (super.noSuchMethod(Invocation.method(#getLastCycleEventWithType, [type]),
              returnValue: Future<dynamic>.value(null)) as _i15.Future<dynamic>);
      @override
      _i15.Future<List<dynamic>> getEvents(DateTime? start, DateTime? end) =>
          (super.noSuchMethod(Invocation.method(#getEvents, [start, end]),
                  returnValue: Future<List<dynamic>>.value(<dynamic>[]))
              as _i15.Future<List<dynamic>>);
      @override
      _i15.Stream<List<dynamic>> getEventsStream(DateTime? start, DateTime? end) =>
          (super.noSuchMethod(Invocation.method(#getEventsStream, [start, end]),
                  returnValue: Stream<List<dynamic>>.empty())
              as _i15.Stream<List<dynamic>>);
      @override
      _i15.Future<List<dynamic>> getEventsForDay(DateTime? day) =>
          (super.noSuchMethod(Invocation.method(#getEventsForDay, [day]),
                  returnValue: Future<List<dynamic>>.value(<dynamic>[]))
              as _i15.Future<List<dynamic>>);
    }
     
Fixed class that actually compiles 

    /// A class which mocks [CycleEventService].
    ///
    /// See the documentation for Mockito's code generation for more information.
    class MockCycleEventService extends _i1.Mock implements _i19.CycleEventService {
      MockCycleEventService() {
        _i1.throwOnMissingStub(this);
      }
    
      @override
      _i3.CycleEventRepository get cycleEventRepository => (super.noSuchMethod(
          Invocation.getter(#cycleEventRepository),
          returnValue: _FakeCycleEventRepository()) as _i3.CycleEventRepository);
      @override
      _i2.UserRepository get userRepository =>
          (super.noSuchMethod(Invocation.getter(#userRepository),
              returnValue: _FakeUserRepository()) as _i2.UserRepository);
      @override
      _i13.CycleSync get exerciseSync =>
          (super.noSuchMethod(Invocation.getter(#exerciseSync),
              returnValue: _FakeCycleSync()) as _i13.CycleSync);
      @override
      _i15.Future<void> deleteEvent(dynamic event) =>
          (super.noSuchMethod(Invocation.method(#deleteEvent, [event]),
              returnValue: Future<void>.value(null),
              returnValueForMissingStub: Future.value()) as _i15.Future<void>);
      @override
      _i15.Future<void> updateEvent(dynamic event) =>
          (super.noSuchMethod(Invocation.method(#updateEvent, [event]),
              returnValue: Future<void>.value(null),
              returnValueForMissingStub: Future.value()) as _i15.Future<void>);
      @override
      _i15.Future<void> saveCycleEvent(dynamic event) =>
          (super.noSuchMethod(Invocation.method(#saveCycleEvent, [event]),
              returnValue: Future<void>.value(null),
              returnValueForMissingStub: Future.value()) as _i15.Future<void>);
      @override
      _i15.Future<CycleEvent?> getLastCycleEventWithType(
              List<_i16.CycleEventType>? type) =>
          (super.noSuchMethod(Invocation.method(#getLastCycleEventWithType, [type]),
              returnValue: Future<dynamic>.value(null)) as _i15.Future<CycleEvent>);
      @override
      _i15.Future<List<CycleEvent>> getEvents(DateTime? start, DateTime? end) =>
          (super.noSuchMethod(Invocation.method(#getEvents, [start, end]),
                  returnValue: Future<List<dynamic>>.value(<dynamic>[]))
              as _i15.Future<List<CycleEvent>>);
      @override
      _i15.Stream<List<CycleEvent>> getEventsStream(DateTime? start, DateTime? end) =>
          (super.noSuchMethod(Invocation.method(#getEventsStream, [start, end]),
                  returnValue: Stream<List<dynamic>>.empty())
              as _i15.Stream<List<CycleEvent>>);
      @override
      _i15.Future<List<CycleEvent>> getEventsForDay(DateTime? day) =>
          (super.noSuchMethod(Invocation.method(#getEventsForDay, [day]),
                  returnValue: Future<List<dynamic>>.value(<dynamic>[]))
              as _i15.Future<List<CycleEvent>>);
    }
     

The different being that things no longer return dynamic, but actual types.

**Comment by srawlins** [comment]
Thanks for the concrete bug report. Looks like the issue is the `getLastCycleEventWithType` method. Can you report what version of mockito you are using?

**Comment by cadaniel** [comment]
It actually does it for every method on the service, but didn't want to write the same error message multiple times. 

Ive verified the bug on 5.0.5

**Comment by srawlins** [comment]
Every method? What's wrong with `_i15.Future<void> deleteEvent(dynamic event) =>` for example? I only see that `getLastCycleEventWithType` is wrong.

**Comment by srawlins** [comment]
Oh here's another one. `_i15.Future<List<dynamic>> getEvents(DateTime? start, DateTime? end) =>` should not be `List<dynamic>`.

**Comment by cadaniel** [comment]
returnign Future<void> is fine, but anything that has an actual return type doesn't compile with everything being dynamic. 

I'll take another look in a bit here when I can easily undo my current changes.

**Comment by srawlins** [comment]
I have unit tests for these things and cannot reproduce what you are seeing. :(

For example, given:

```dart
class Foo {
  Future<bool?> m(int i) async => false;
}
```

I see generated:

```dart
  @override
  _i3.Future<bool?> m(int? i) => (super.noSuchMethod(Invocation.method(#m, [i]),                                                                         
      returnValue: Future<bool?>.value(false)) as _i3.Future<bool?>);
```

Can you reproduce with a small example, without all of the types found in your first repro?

**Comment by srawlins** [comment]
This might be the type of result that happens when CycleEvent is not a resolved type, like if its a generated type or something like that...

**Comment by cadaniel** [comment]
> This might be the type of result that happens when CycleEvent is not a resolved type, like if its a generated type or something like that...

100% this probably.

All my classes and types are freezer objects, which are other generated types.

**Comment by srawlins** [comment]
Ah ha I can 100% reproduce this with unresolved types. I think the behavior should be to throw instead of secretly use `dynamic`.

**Comment by cadaniel** [comment]
What would this mean for my use case where all my objects are generated? Would this mean I can't use the generator?

**Comment by srawlins** [comment]
Are the generated types like CycleEvent generated by the build system a la build_runner and build.yaml, etc? In that case, I think re-ordering build.yaml is a functional solution, and something I should put in the README.

**Comment by cadaniel** [comment]
> Are the generated types like CycleEvent generated by the build system a la build_runner and build.yaml, etc? In that case, I think re-ordering build.yaml is a functional solution, and something I should put in the README.

Yes everything I do is build using build_runner. 

So I use moor, freezed, and injectable. The first two generate classes, while injectable is able to use them. Maybe that might be a place to look at how they use this?

**Comment by srawlins** [comment]
Here's a similar thread from so many moons ago, also regarding moor. https://github.com/dart-lang/mockito/issues/345#issuecomment-792463979

**Comment by cadaniel** [comment]
> Here's a similar thread from so many moons ago, also regarding moor. [#345 (comment)](https://github.com/dart-lang/mockito/issues/345#issuecomment-792463979)

Interesting, I don't get the same error they did. I even use the companion object heavily in my app (I know I know, I'll be moving away from it as soon as I get time).

**Comment by cadaniel** [comment]
Any update on this? 

I haven't been able to find a config that works

**Comment by srawlins** [comment]
Have you fiddled with your build.yaml file to make sure the other generators run before mockito does? Otherwise no update from me.

**Comment by cadaniel** [comment]
I did, I wasn't able to get it to do that though. 

I can't find explicit instructions on how to order things though. That link above doesn't really explain what's going on, and just relies on a magic config. 

I tried forking freezer to add a run_before parameter in that build.yml, and I tried adding a depends_on for mockito in my build file. Neither worked.

**Comment by srawlins** [comment]
Do you have a public repo / branch that I can clone and play with?

**Comment by cadaniel** [comment]
I don't, my main app that I'm working on is private, give me a min and I'll try and come up with something

**Comment by cadaniel** [comment]
So I set up a demo, and it turns out it is moor, but I don't understand the linked solution enough to actually get it working

I have a sample repo 
https://github.com/cadaniel/mockito_test

**Comment by cadaniel** [comment]
I got it working!

So you might want to add an FAQ if you are using moor. 

I had to set up the build values for multiple steps rather than a one shot one kill. 

This took some trial and error.

**Comment by vanlooverenkoen** [comment]
@cadaniel we are having the exact same issue. Can you give a little more information on how you fixed that issue?

**Comment by GenixPL** [comment]
@vanlooverenkoen I guess you have managed to solve the issue over the past 2 years 😄 
but for anyone who stumbles upon this issue, the solution is to skip type declaration and the mocks will be generated with `T`

```
@GenerateMocks(<Type>[], customMocks: <MockSpec<dynamic>>[
  // YES
  // ignore: always_specify_types
  MockSpec<FimpSelectAction>(as: #GeneratedMockFimpSelectAction),
  
  // NO
  // MockSpec<FimpSelectAction<dynamic>>(as: #GeneratedMockFimpSelectAction),
])
class MockFimpSelectAction<T> extends GeneratedMockFimpSelectAction<T> {
  // ...
}
```
