### ISSUE TITLE
GenerateMocks not working on class that GetxController

### ISSUE THREAD

**Issue by lifez** [dart-lang/mockito#396]
I have a class that extends GetxController from a library [Getx](https://pub.dev/packages/get) and uses GenerateMocks but I have a problem with the screenshot below. Please advise.

Mockito: 5.0.5
Get: 4.1.4

<img width="740" alt="Screen Shot 2021-04-27 at 15 48 53" src="https://user-images.githubusercontent.com/2588927/116213609-242c7080-a770-11eb-82bf-cdec589c0c13.png">

**Comment by srawlins** [comment]
`_InternalFinalCallback` is a private class so it cannot be faked. It is in the signatures of one of the methods of one of the classes being mocked in `GenerateMocks`.

Mockito should throw instead of generating this library.

**Comment by lifez** [comment]
@srawlins Yes exactly. I fork target library and change to the public, then it works!.

**Comment by lifez** [comment]
@srawlins So should we rename the title of this issue to "Throw errors If found the private class"?

I will help to contribute on this.

**Comment by srawlins** [comment]
Thanks for the info @lifez ; fixed in 5.0.7.
