### ISSUE TITLE
GenerateMocks not properly generating mocks that use the Diagnosticable mixin

### ISSUE THREAD

**Issue by arthurpiccoli** [dart-lang/mockito#397]
After generating the following mock class:
`class _FakeTextStyle extends _i1.Fake implements _i12.TextStyle {}`

This error occurred: 
`'Object.toString' ('String Function()') isn't a valid concrete implementation of 'Diagnosticable.toString' ('String Function({DiagnosticLevel minLevel})')`

It happened due to the `toString` method on `Diagnosticable` dependent classes, as `TextStyle` being one, having a different format, needing a `DiagnosticLevel` as param. This simple solution did the trick, but it was necessary to edit the generated file:
```
class _FakeTextStyle extends _i1.Fake implements _i12.TextStyle {
  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return super.toString();
  }
}

**Comment by srawlins** [comment]
Thanks for opening an issue. This has been discussed at https://github.com/dart-lang/mockito/issues/233. See [the solution](https://github.com/dart-lang/mockito/issues/233#issuecomment-607533095).

**Comment by safarmer** [comment]
@srawlins the solution in #233 only seems to cover manually created mocks? How would we apply this to `@GeneratedMocks`?

**Comment by srawlins** [comment]
Oops, apologies. You are correct; that solution works for manual mocks. This issue is actually a duplicate of https://github.com/dart-lang/mockito/issues/371.
