### ISSUE TITLE
How to mock a method with any function as the named argument?

### ISSUE THREAD

**Issue by pawelpetruch** [dart-lang/mockito#398]
Before the null safety I could simply mock up the sendRequest(...) method like that:

```
 void stubBaseRepositorySendRequestResponse(String response) {
    when(baseRepository.sendRequest(onGetData: anyNamed('onGetData')))
        .thenAnswer((_) {
      return Future<String>.value(response);
    });
  }
```

where **sendRequest** is:

`Future<T> sendRequest<T>({required Future<T> Function() onGetData}) async
{
...
}`

How can this be done with null safety? 
Can I still maintain the generic character of this stub and allow for any arguments to be passed in?

**Comment by srawlins** [comment]
Are you using the generated mock solution or the manual mock solution, each found in [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md)?

For the generated mock solution, this is the same issue as https://github.com/dart-lang/mockito/issues/338.

**Comment by pawelpetruch** [comment]
@srawlins I was intending to use the generated mock solutions to avoid the hassle.

**Comment by pawelpetruch** [comment]
This can be easily done with [mocktail](https://pub.dev/packages/mocktail) by @felangel.

Important to import mocktail:
`import 'package:mocktail/mocktail.dart';`

then create a mock of the class that we want to mock:
`class MockBaseRepository extends Mock implements BaseRepository {}`

```
  void stubBaseRepositorySendRequestResponse(String response) {
    when(() => baseRepository.sendRequest(
        onGetData: any(named: 'onGetData', that: isNotNull))).thenAnswer((_) {
      return Future<String>.value(response);
    });
  }
```
