### ISSUE TITLE
Conditionally disable fakes

### ISSUE THREAD

**Issue by cadaniel** [dart-lang/mockito#409]
I'm using the generator, and I'm having troubles with the generated fake classes from moor.

```
Object.==' ('bool Function(Object)') isn't a valid concrete implementation of 'User.==' ('bool Function(dynamic)').
```

I've opened an issue with moor at https://github.com/simolus3/moor/issues/1192 but in the mean time, I would like to conidtionally disable Fakes. I don't use them when stubbing personally, instead feeding 'real' classes.

**Comment by srawlins** [comment]
Thanks for opening an issue.

The code you point to is probably in a generated mock, not a generated fake.

**Comment by cadaniel** [comment]
@srawlins 

The offending line of code is 

`class _FakeUser extends _i1.Fake implements _i3.User {}`

**Comment by srawlins** [comment]
Ah that is very interesting. Even this tiny snippet results in the error you show:

```dart
class User {
  bool operator == (dynamic other) => true;
}

class FakeUser extends Fake implements User {}

class Fake {
  dynamic noSuchMethod(_) {}
}
```

I really think the Moor classes should not override `operator ==` to accept a `dynamic` parameter...

In any case, this class is required in order to generate your mocks. If you search the generated library for references to _FakeUser, you will see where it is needed.

**Comment by cadaniel** [comment]
I'm sssoooo close to being able to use the generator again. I don't use the Fakes anyways, is there a way to turn them off for now?

**Comment by srawlins** [comment]
No. If a fake is referenced in the generated library, then it is necessary. Otherwise the code would reference a type which doesn't exist.

**Comment by cadaniel** [comment]
hmmm..

I've also noticed this isn't the first time this has come up, I wonder if a setting to not override could be possible? 

Thoughts for a future problem. I'll go back to manually creating mocks for now.

**Comment by cadaniel** [comment]
That's not 100% true. 

So my case here is I use moor data classes as returns. I don't need that to be a mocked return. All I do to fix this is take a generated class, and remove the Fake return, and instead just use the normal return.

This is what I need:

```
  @override
  _i11.Stream<List<ExerciseEvent>> getEventsBetweenStream(
          DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
              Invocation.method(#getEventsBetweenStream, [start, end]),
              returnValue: Stream<List<ExerciseEvent>>.empty())
          as _i11.Stream<List<ExerciseEvent>>);
```

Where what returns from the generator is 

```
@override
  _i12.Stream<List<_i3.ExerciseEvent>> getEventsBetweenStream(
          DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
              Invocation.method(#getEventsBetweenStream, [start, end]),
              returnValue: Stream<List<_i3.ExerciseEvent>>.empty())
          as _i12.Stream<List<_i3.ExerciseEvent>>);
```
_i3.ExerciseEvent references the moor class, not the fake. 

This makes sense because the fake is a child of the class.

**Comment by cadaniel** [comment]
I'll let you decide if further action is needed. Moor has just fixed this making it kinda moot for now

**Comment by srawlins** [comment]
Your example is intriguing; this easily looks like a bug/shortcoming that we can address in mockito; I'll re-open to fix this.

Thanks for digging it up!!!
