### ISSUE TITLE
expect(false, true) works

### ISSUE THREAD

**Issue by boldt** [dart-lang/mockito#421]
## MWE

```
  test("expect(false, true)", () {
    expect(false, true);
  });
```

## Issue

A test using the above code succeeds.

![grafik](https://user-images.githubusercontent.com/750793/120322336-97338480-c2e4-11eb-9f66-8fd537932518.png)

## Expected

Should throw an exception.

## Our setup

* dart: 2.13.0
* flutter: 2.2.0
* mockito: 5.0.8

**Comment by srawlins** [comment]
Does this have to do with mockito, or should I transfer this to the `test` package's repository?

**Comment by boldt** [comment]
Who can provide this info?

**Comment by boldt** [comment]
I don't know what changed, but the test fails now (as expected):

![grafik](https://user-images.githubusercontent.com/750793/121138595-26d2b900-c838-11eb-9255-04d3feb24173.png)

![grafik](https://user-images.githubusercontent.com/750793/121138651-32be7b00-c838-11eb-8560-3ccc06a6f4f2.png)
