### ISSUE TITLE
anyNamed for required named 

### ISSUE THREAD

**Issue by MlecznyU** [dart-lang/mockito#430]
In readme there is a Cat class:

`class Cat {
  String? sound() => 'Meow';
  bool? eatFood(String? food, {bool? hungry}) => true;
  Future<void> chew() async => print('Chewing...');
  int? walk(List<String>? places) => 7;
  void sleep() {}
  void hunt(String? place, String? prey) {}
  int lives = 9;
}`

For named argument you recommend: anyNamed, argThat, captureAnyNamed and captureThat

My question is as follows. What if we changed the parameter for hungry in eatFood function to required bool hungry?

In that case, from what I can see, I get the following error:
"The argument type 'Null' can't be assigned to the parameter type 'bool'.

What should I do in the case like this?

**Comment by srawlins** [comment]
Can you post the line of code which is generating that error? Are you using mockito's code generation? You might want to read the NULL_SAFETY_README to see how to use argument matchers (like `anyNamed`) with non-nullable types.

**Comment by MlecznyU** [comment]
I have read both readmes thoroughly, but unfortunately, I am still missing something. I haven't found any example of what to do if one of the parameters is required and named at the same time. 

I get the error when I replace 
`eatFood(String? food, {bool? hungry}) => true;` 
with line 
`eatFood(String? food, {required bool hungry}) => true;`

**Comment by srawlins** [comment]
Can you paste to me the line of code which generates the error? It should be a call to `eatFood`.

Can you also paste to me the generated library with the generated Mock of Cat?

**Comment by MlecznyU** [comment]
`// ignore_for_file: sdk_version_async_exported_from_core
// ignore_for_file: unawaited_futures
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

import 'example.mocks.dart';

// Real class
class Cat {
  String? sound() => 'Meow';

  bool? eatFood(String? food, {required bool hungry}) => true;

  Future<void> chew() async => print('Chewing...');

  int? walk(List<String>? places) => 7;

  void sleep() {}

  void hunt(String? place, String? prey) {}
  int lives = 9;
}

@GenerateMocks([
  Cat
], customMocks: [
  MockSpec<Cat>(as: #MockCatRelaxed, returnNullOnMissingStub: true),
])
void main() {
  late Cat cat;

  setUp(() => cat = MockCat());

  test('Named arguments', () {
    // GOOD: argument matchers include their names.
    when(cat.eatFood(any, hungry: anyNamed('hungry'))).thenReturn(true);
    when(cat.eatFood(any, hungry: argThat(isNotNull, named: 'hungry')))
        .thenReturn(false);
    when(cat.eatFood(any, hungry: captureAnyNamed('hungry'))).thenReturn(false);
    when(cat.eatFood(any, hungry: captureThat(isNotNull, named: 'hungry')))
        .thenReturn(true);
  });
}
`

**Comment by MlecznyU** [comment]
I reproduced the situation with the example from the readme. The only thing you have to do is to change the nullable named argument to non-nullable

**Comment by srawlins** [comment]
Ah, the `cat` is declared as a `Cat`, which does indeed require a non-null `hungry` argument. `cat` should be declared as a `MockCat`.

**Comment by MlecznyU** [comment]
Thank you for your help. I thought that it is not enough, but I had some typos in my code. Closing issue

**Comment by Rohithgilla12** [comment]
Thanks it helped me :smile:
