### ISSUE TITLE
Mocking inner class to import certain data

### ISSUE THREAD

**Issue by code-4-bread** [dart-lang/mockito#431]
I am having trouble mocking a class that is used externally.

**user_utils.dart**
```
class UserUtils {
	Future<String> getUserID() {
		return UserID;
	}
}
```

In one of my widget, this `UserUtils.getUserID` will be called. I have mocked the class to return certain UserID.
But during the test, seems my mock is not being called. Must I pass in the mock as parameter? If so, my widget doesn't take UserUtils as param, any other way to make this work?

**Comment by srawlins** [comment]
The code which calls `getUserID` must call `getUserID` on an instance of you mock class. Can you show where you create an instance of your mock class and use it in a test?

> Must I pass in the mock as parameter? If so, my widget doesn't take UserUtils as param, any other way to make this work?

We can't really answer this question here; this is probably better suited to ask in a Flutter chat or on StackOverflow.

**Comment by code-4-bread** [comment]
I managed to solved the issue by the package itself that the function is calling. I will be closing the issue now. Thank you for info.
