### ISSUE TITLE
Running flutter analyze on generated mock results in "implementation_imports" failure.

### ISSUE THREAD

**Issue by alexghiu** [dart-lang/mockito#440]
Should the *.mocks.dart files contain an entry for `ignore_for_file: implementation_imports`?

I'm generating a mock for a service class that receives `http.Client` as a dependency. The generated mock (see sample below) causes `flutter analyze` to fail with `implementation_imports`.

```dart
// Mocks generated by Mockito 5.0.10 from annotations
// in src/service.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/src/client.dart' as _i2;
import 'package:http/src/response.dart' as _i7;

// ... more stuff ...

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

```

Given that the generated mock already contains comments for suppressing rules, should `implementation_imports` be added by default as well?

```
    • Flutter version 2.2.2 at /Users/alex/Applications/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
```

**Comment by srawlins** [comment]
Yeah we should ignore that lint as well.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/mockito/pull/447/commits/c34cea6fab24d0f3597826eb6ea06818e2028dea
