### ISSUE TITLE
Code generation creates duplicate names

### ISSUE THREAD

**Issue by tjarvstrand** [dart-lang/mockito#441]
Hi! I currently have code which looks something like this:

```
@GenerateMocks(
  [AuthenticationRepository, UserRepository],
)
void main() {
  ...
}
```

`AuthenticationRepository` internally uses `User` from the firebase_auth package whereas `UserRepository` (and most of the rest of my application) uses my own representation of a user. This currently results in code generation producing something like this:
```
...
class _FakeUser extends _i1.Fake implements _i2.User {
  @override
  String toString() => super.toString();
}
...
class _FakeUser extends _i1.Fake implements _i5.User {}
...
```

Which gives me this error when trying to run the code: `Error: Can't use '_FakeUser' because it is declared more than once.`

I've tried adding `customMocks: [MockSpec<firebase.User>(as: #FirebaseUser)` which does generate the `FirebaseUser` class but it is not used by the `AuthenticationRepository` mock. Is there any way to solve this?

**Comment by srawlins** [comment]
Yikes, good issue. No way at present to solve it. But since these are private classes, the generator should be able to detect this situation and add suffixes or something to distinguish. You could imagine `class _FakeUser_i2` and `class _FakeUser_i5`...
