### ISSUE TITLE
Does Mockito only stub methods from a mocked class? 

### ISSUE THREAD

**Issue by thechinkysight** [dart-lang/mockito#448]
I have a class named `ApiClientProvider` which has a function `getName()`:

```dart
class ApiClientProvider {
  Future<String> getName() async {
    return "Incognito";
  }
}
```
I wrote a test like this:
```dart
void main(){
    test("description", () async{
      ApiClientProvider apiClientProvider = ApiClientProvider();
      when(apiClientProvider.getName()).thenAnswer((_) async => "Alice");
      expect(await apiClientProvider.getName(), "Alice");
    });
}
```
**Note: `ApiClientProvider` class is not a mocked class**

So when I ran the test, I got an error saying **`Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?`**

From this error I doubted that Mockito can only stub methods from mocked classes, but I was not sure. I googled my doubt but that wasn't helpful so I end up opening an issue here.

**Comment by srawlins** [comment]
Correct. It can only stub methods on mocked classes.

**Comment by chinkysight** [comment]
> Correct. It can only stub methods on mocked classes.

Got it 🙂 thank you so much
