### ISSUE TITLE
Lint violation in generated file: unnecessary_overrides with toString()

### ISSUE THREAD

**Issue by jeiea** [dart-lang/mockito#450]
I'm getting the following suggestion after replacing pedantic package with flutter_lints. It seems additional lint ignoration is necessary.

<img width="807" alt="Screen Shot 2021-07-16 at 2 51 40 PM" src="https://user-images.githubusercontent.com/4188984/125899084-9dddd790-7561-4266-9943-50edb2b1863a.png">

**Comment by srawlins** [comment]
Hmm good bug find. We might be able to carefully _not_ implement this overriding method.

**Comment by srawlins** [comment]
With the latest release (specifically https://github.com/dart-lang/mockito/commit/ce2e6cfe32aaf478fbd2ab0cd94c85a35db09f98), we should only override `toString` when it needs  more parameters.
