### ISSUE TITLE
Linter fails on generated code (avoid_setters_without_getters)

### ISSUE THREAD

**Issue by p0wl90** [dart-lang/mockito#453]
When I generate a mock for InterceptedClient from the http_interceptor package, the linter fails on the avoid_setters_without_getters rule. maybe you can add it to the ignored rules in the generated files?

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/mockito/commit/a93b4348df0de508f056f8ee896bb2260c01aaec
