### ISSUE TITLE
No matching calls with objects as argument

### ISSUE THREAD

**Issue by sebastianbuechler** [dart-lang/mockito#455]
I call in one of my tests the following:

`model.setAddress(street: "test", city: "test");`

In the viewmodel where this tested function is placed, I aggregate these values into an `Address` object and save it persistently. 

Therefore I want to check that this saving takes place:

` verify(_userService.setAddress(Address(street: "test", city: "test")));`

However, now I don't get the call:

`No matching calls. All calls: MockUserService.setAddress(Instance of 'Address')`

Why doesn't it recognize that the two arguments match? One is created in the test and one is created in the method I want to test, thus it does not have the same hash value, but does that matter here?

**Comment by srawlins** [comment]
Mockito should be using `==` to compare whether the first address you used is equal to the address you used in `verify`. They are apparently unequal.

To help with debugging this, you can add a `toString` method to Address, so that the error message contains the fields. You can also print the two object's hashCode, or see if `==` has been overridden to make the objects inequal somehow.

**Comment by sebastianbuechler** [comment]
@srawlins The `toString` method shows exactly the same output. The hashCodes however are different, because I guess they are not the same instance (one initiated in the test itself and the other in the function I want to test). `==` hast not been overridden, they are not complicated objects. 

Can the behaviour of the `verify` be changed? I think often when you initiate an object in a function you want to test you don't care if it is no the exact same object, but similar enough (=same field entries).

**Comment by srawlins** [comment]
Sorry, this behavior will not be changing. Mockito uses `==` to know what stub response to return, and whether an invocation matches in `verify`. I'm not sure what you would propose instead, but for example, to compare the `toString()` value of two objects would make _most_ objects of the same type "equal". In your own example, any two Address objects would be "equal" because their `toString()` value is "Instance of 'Address'".

**Comment by sebastianbuechler** [comment]
I think a typical use-case would be to test the creation of an object and that will always fail with `==`. So I would propose to make an additional method to `verify` in a "shallow" meaning which would compare only the variables of objects and not their hashCode. However, I did not find a suitable approach yet on how to implement this. 

For now, the best solution I could find for testing objects is this manual approach by using `expect` on captured variables:
```
final arguments = verify(navigationService.replaceWith(Routes.landingView, arguments: captureAnyNamed('arguments'))).captured.single as LandingViewArguments;
expect(arguments.needBackground, true);
```

**Comment by srawlins** [comment]
>  I think a typical use-case would be to test the creation of an object and that will always fail with ==

I'm not sure what you mean here.  A typical  `==` operator would look something like `operator ==(Object? other) => other is Address && street == other.street && city == other.city;`.

**Comment by sebastianbuechler** [comment]
> > I think a typical use-case would be to test the creation of an object and that will always fail with ==
> 
> I'm not sure what you mean here. A typical `==` operator would look something like `operator ==(Object? other) => other is Address && street == other.street && city == other.city;`.

I don't think it's nice to adjust the `==` only to pass a test if it doesn't have any meaning in your code. It is highly impractical to adjust each of your objects only to have it testable. 

Why not adjust the testing library in a way that has more purpose for object testing? It would help enormously if `Verify` (or a similar method) could test for the objects field if we want it to do so. 

This way we could really test if an object is created properly without adjusting unnecessary `==` operators.

**Comment by natebosch** [comment]
The supported approach to use something other than `==` to compare argument is `argThat` with a matcher validating whatever properties you are interested in.

https://pub.dev/documentation/mockito/latest/mockito/argThat.html

It is not possible without reflection to automatically check for any other meaning of "equality" so the meaning of equality that you want other than `==` needs to be implemented manually. If you want to write a reflection based check you could implement a custom `Matcher` for that. We don't have have any plans to write such a matcher.

**Comment by sebastianbuechler** [comment]
@natebosch So if you have dozens of bigger models and you want to test if the creation of new instances of those models works as you want it, you really need to write out everything manually with `argThat`? Isn't that tedious?

**Comment by natebosch** [comment]
> you really need to write out everything manually with `argThat`? Isn't that tedious?

We generally prefer explicitly indicating what we are checking than to use reflection to perform checks that aren't easy to predict statically.

This doesn't stop you from using reflection, but it isn't a goal for the Dart team so it won't be built in to the package and we won't be providing the implementation.

**Comment by sebastianbuechler** [comment]
@natebosch If you have instead of a model with two fields an advanced model with nested models inside it can get pretty easily more than 50 fields you would need to check in my initial example. `argThat` can't be the optimal solution to check each of those.

I know reflect is not optimal, but the current solution isn't either.
