### ISSUE TITLE
Cannot generate mock for a class that extends GetxController

### ISSUE THREAD

**Issue by jimbengtsson92** [dart-lang/mockito#456]
When generating a mock for a class that extends GetxController, the generated file contains the following error:

> 'MockTestControllerToMock.addListener' ('void Function(void Function()?)') isn't a valid override of 'ListNotifierMixin.addListener' ('void Function() Function(void Function())')

[Minimal GitHub repo](https://github.com/jimbengtsson92/mockito_mock_getx_controller) that shows the error.

![Screenshot 2021-07-27 at 14 50 16](https://user-images.githubusercontent.com/74904815/127156812-99b1e27f-6f03-4e60-a08e-fa7be81fb100.png)

**Comment by srawlins** [comment]
Here's the type hierarchy:

```dart
class Listenable {
  void addListener(VoidCallback listener) { /*...*/ }
}

mixin ListenableMixin implements Listenable {}
mixin ListNotifierMixin on ListenableMixin {
  @override
  Disposer addListener(GetStateUpdate listener) { /*...*/ }
}
```

Mockito appears to be going for the overridden signature, instead of the proper signature.
