### ISSUE TITLE
null error when using any on manually extends mock object

### ISSUE THREAD

**Issue by spontaneous01** [dart-lang/mockito#458]
Hi,
I don't want to generate code by mockito. 
So, I extends `Mock` manually. 
Then I get an error message on `any`.
The below is my sample code.
Does it means we cannot skip the annotation `@GenerateMocks`  or else something I am miss understand?
Thank!
```
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';


class A {
  String method(String a) {
    return "TEST$a";
  }
}

class MockA extends Mock implements A {}

void main() {

  final MockA a = MockA();
  test("name", () {
    when(a.method(any)).thenReturn("test");  //<--- The argument type 'Null' can't be assigned to the parameter type 'String'.
  });
}
```

**Comment by srawlins** [comment]
Please read the NULL_SAFETY_README section regarding [manually override a method with a non-nullable parameter type](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#manually-override-a-method-with-a-non-nullable-parameter-type).

**Comment by spontaneous01** [comment]
Hi,

Thank you for assistance.
I get the point is I need to do it myself which generator.
I will go back to let generator do it.
Cheers 👍
