### ISSUE TITLE
Mocking a moor database fails

### ISSUE THREAD

**Issue by kuhnroyal** [dart-lang/mockito#459]
Generating a mock for a database generated with https://github.com/simolus3/moor fails.
I thought this may be fixed by the new `source_gen` from https://github.com/dart-lang/mockito/issues/425 but this didn't help.

This may happen with all factories that return a subclass which is not declared in the same file.

---

There is a `TableUpdateQuery` class here: https://github.com/simolus3/moor/blob/develop/moor/lib/src/runtime/api/stream_updates.dart#L122 with a factory
`const factory TableUpdateQuery.any() = AnyUpdateQuery;`.

The `AnyUpdateQuery` class is declared in another file here: https://github.com/simolus3/moor/blob/develop/moor/lib/src/runtime/executor/stream_queries.dart#L279

When the mock for the database is generated it contains this fragment for a method where the const factory is used as default value for a parameter:

```dart
import 'package:moor/src/runtime/api/runtime_api.dart' as _i29;
import 'package:moor/src/runtime/executor/stream_queries.dart' as _i32;

  @override
  _i35.Stream<Set<_i29.TableUpdate>> tableUpdates(
          [_i29.TableUpdateQuery? query = const _i32.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(Invocation.method(#tableUpdates, [query]),
              returnValue: Stream<Set<_i29.TableUpdate>>.empty())
          as _i35.Stream<Set<_i29.TableUpdate>>);
```

The `_i32` import prefix is obviously wrong and doesn't point to the file containing the factory function but instead to the type that is being returned by the factory function. This should be `_i29` as well.

@simolus3 FYI

**Comment by srawlins** [comment]
Yikes that doesn't look good.

Can you paste your `package.lock` file so I can see the version of analyzer and source_gen in play.

**Comment by kuhnroyal** [comment]
```yaml
analyzer: 2.0.0
source_gen: 1.0.5
```

I closely watched the recent fixe in `source_gen` but that didn't have an effect on this issue.
`analyzer` and `source_gen` seem to be returning the correct types, there is just no way (I could find) to figure out that this is a redirected factory.

My PR seems to work for now, can't think of a case where it would fail nut not sure it is the best approach.

**Comment by kuhnroyal** [comment]
Also I now think that this only happens for a factory redirect, not for a factory returning a subclass per se.

**Comment by srawlins** [comment]
I see, yeah `const factory` is definitely a case I hadn't considered, and maybe source_gen too.

**Comment by srawlins** [comment]
I can reproduce this with a unit test.

**Comment by kuhnroyal** [comment]
Yes, I also added a test which produces this in my PR.

**Comment by kuhnroyal** [comment]
@srawlins Can you cut a patch release with this by any chance?
