### ISSUE TITLE
How to verify if setter was called?

### ISSUE THREAD

**Issue by bartekpacia** [dart-lang/mockito#467]
Let's say that I have some setter:

```dart
class Foo {
  String category;

  set category(String newValue) {
      category = newValue;
    }
}
```

Now, in tests, I'd like to verify that it was called twice. I tried out 2 approaches:

1.
```dart
verify(mockFoo.category).called(2);
```

2.
```dart
verify(mockFoo.category=any).called(2);
```

but it doesn't work, because it is not a callable function (?), like, with the parentheses (forgive me, I am not a Dart expert).

Is it solved (if yes, there should be info in README about this behavior), and if not: are there any workarounds and are there any plans to implement this (assuming it's even possible).

**Comment by srawlins** [comment]
Let us know if you need further assistance. You can post the error message if you continue to have problems.

**Comment by bartekpacia** [comment]
Hi, in fact, the second attempt in fact worked. It was 2 AM and I must've been tired. Thanks for the help!

I think info about this feature should be added to README:)
