### ISSUE TITLE
Mocking ScrollPosition generates wrong default parameters

### ISSUE THREAD

**Issue by bornold** [dart-lang/mockito#468]
Maybe related to https://github.com/dart-lang/mockito/issues/459

To reproduce:
1. Clone https://github.com/bornold/mockito_gen_bug
2. run `flutter packages pub run build_runner build     `

Problem here: https://github.com/bornold/mockito_gen_bug/blob/0e61f07d48c598ef47b7e8ea2b75928834de14a2/test/scroll_position.mocks.dart#L204
```dart
  @override
  _i11.Future<void> ensureVisible(_i12.RenderObject? object,
          {double? alignment = 0.0,
          Duration? duration = const Duration(seconds: 0),
          _i10.Curve? curve = _i10.Cubic.ease,
```
Which should be:
```dart
 @override
  _i11.Future<void> ensureVisible(_i12.RenderObject? object,
          {double? alignment = 0.0,
          Duration? duration = const Duration(seconds: 0),
          _i10.Curve? curve = _i10.Curves.ease,
```
Problem discription
```
The getter 'ease' isn't defined for the type 'Cubic'.
Try importing the library that defines 'ease', correcting the name to the name of an existing getter, or defining a getter or field named 'ease'.
```

**Comment by srawlins** [comment]
Can you post the version of mockito in play? Either from `pub get` or the file `.dart_tool/package_config.json`.

**Comment by bornold** [comment]
Pushed the whole .dart_tool to the repo: https://github.com/bornold/mockito_gen_bug/blob/master/.dart_tool_copy/package_config.json

```json
    {
      "name": "mockito",
      "rootUri": "file:///Users/jonasbornold/.pub-cache/hosted/pub.dartlang.org/mockito-5.0.15",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
```

Seems to be using the latest mockito version?

**Comment by srawlins** [comment]
Thanks for showing the whole package_config.json!

I think you need a newer `source_gen` to avoid a bug in that package. 1.0.5 I think is good enough. https://pub.dev/packages/source_gen/changelog

`pub upgrade` should do the trick. Not sure if there is a specific Flutter workflow.

**Comment by bornold** [comment]
Thanks for the answer!

Unfortunately
> flutter pub upgrade

did not upgrade `source_gen`

  Tried to add `  source_gen: ^1.0.5` to pubspec.yaml but it is not compatible with `flutter_test`

```
Because source_gen >=1.0.4 <1.1.0 depends on analyzer ^2.0.0 and no versions of source_gen match >1.1.0 <2.0.0, source_gen >=1.0.4 <1.1.0-∞ or >1.1.0 <2.0.0 requires analyzer ^2.0.0.


And because source_gen 1.1.0 depends on analyzer ^2.1.0, source_gen ^1.0.4 requires analyzer ^2.0.0.
And because analyzer >=2.0.0 depends on meta ^1.7.0 and every version of flutter_test from sdk depends on meta 1.3.0, source_gen ^1.0.4 is incompatible with flutter_test from sdk.

So, because mocktito_gen_bug depends on both flutter_test any from sdk and source_gen ^1.0.5, version solving failed.
pub get failed (1; So, because mocktito_gen_bug depends on both flutter_test any from sdk and source_gen ^1.0.5, version solving failed.)
```

So I guess no progress until `flutter_test` supports `meta ^1.7.0`?

**Comment by srawlins** [comment]
I think that's right. Unfortunately, I don't see a tracking issue for this at Flutter's repo. :/
