### ISSUE TITLE
Friendly debug messages when mock methods without expectations set are called.

### ISSUE THREAD

**Issue by renning22** [dart-lang/mockito#47]
For example:
```
//Real class
class Cat {
  String sound() => "Meow";
}

//Mock class
class MockCat extends Mock implements Cat {}

//mock creation
var mockCat = new MockCat();

// Would throw exception "NoSuchMethodError: The method 'toUpperCase' was called on null.".
mockCat.sound().toUpperCase();
```

The actual cause is during the test development, developer forgot to write "when(cat.sound()).thenReturn("Purr");".

The message "'toUpperCase' was called on null" isn't helpful for finding out the casue and a more friendly message could be "'toUpperCase' was called on the return value of 'Cat.sound()', but no exceptions were set on it".

This could be achieved by returning instead of 'null' but a special object carrying the method invocation information for any 'un-expected' methods.

I can come with a design doc if this sounds possible.

**Comment by TedSander** [comment]
Because of Strong mode you can only return the type specified in the type signature of the method, or null (it matches everything.)

So you can't return a special object carrying the method invocation information because this breaks the type contract.

**Comment by srawlins** [comment]
Yeah @TedSander mentions the main reason we can't really do this.

In general though, many users of mockito might rely on `null` being returned from un-stubbed methods (maybe unknowingly). This request is akin to requesting that we throw if a method is called without a canned response. Which might be a good feature as well, but... only like... in "development mode" or something.

I actually think we could write something like that. I think I would support an API that maybe futzes with Mock's [noSuchMethod](https://github.com/dart-lang/mockito/blob/master/lib/src/mock.dart#L99) and adds a new top-level `noSuchCannedResponse` method or something, very similar to what [spy does](https://github.com/dart-lang/mockito/blob/master/lib/src/spy.dart#L29).

**Comment by srawlins** [comment]
Debugging something today, I could really use this feature :stuck_out_tongue_closed_eyes:
