### ISSUE TITLE
Verify failed when dio.post() is called with parameter 'options'

### ISSUE THREAD

**Issue by helianthus1120** [dart-lang/mockito#470]
**Envs:**
mockito: ^5.0.15
build_runner: ^2.0.2
test: ^1.16.5

**Purpose:**
Verify a post request with parameter 'options', is called ever.

**Problem desc:**
I don't know how to apply correct parameters to make verify passed, please help me.

**Error message:**

> No matching calls. All calls: MockDio.post('path', {data: {}, queryParameters: null, options: Instance of 'Options', cancelToken: null, onSendProgress: null, onReceiveProgress: null})
> (If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)

**Code:**

Annotation of Dio class.
```
  @GenerateMocks([Dio])
  void main() { ... }
```
Mocked client.
```
  final client = MockDio();
```

Use Mockito to return a successful response when it calls the provided Dio.
```
  when(client.post(any, data: anyNamed('data'), options: anyNamed('options')))
      .thenAnswer((_) async =>
          Response(requestOptions: requestOptions, statusCode: 200));
```
Launch and verify it.
```
  // launch
  dataSource.post('path', client, headers: {}, body: {})
  
  // verify
  verify(client.post(
    'path',
    data: {},
    options: Options(headers: {}),
  ));
```
Here's dataSource.post():
```
  static Future<Response> post(String url, Dio client,
      {Map<String, String>? headers, body}) {
    return client
        .post(url, options: Options(headers: headers), data: body)
        .then((value) {
      return value;
    });
  }
```

**Comment by srawlins** [comment]
You unfortunately have to pass in all of the parameters found in the real call, which look to include `queryParameters`, `cancelToken`, ...

**Comment by helianthus1120** [comment]
@srawlins thanks for reply.

After few tryings, I simplify the launch and verify call.
here's the only way to pass test:
```
  //launch
  client.post(url,
      data: {},
      options: Options(headers: {}),);
  
  //verify
  verify(client.post(url,
          data: {},
          options: anyNamed('options'),))
      .called(1);
```
I have tried pass all parameters but it doesn't work. It seems like that options make test failed.

**Comment by srawlins** [comment]
You can also log all invocations which have been made with [logInvocations](https://pub.dev/documentation/mockito/latest/mockito/logInvocations.html). Good luck!
