### ISSUE TITLE
check that method finished without throw

### ISSUE THREAD

**Issue by wondertalik** [dart-lang/mockito#474]
Hello, how can i check that method finished without throw?

For example
```
void add(int toKey, int key) {
//some verifications if true
if(root == null) throw StateError();

//someactions
}
```
So, i want to know that add method executed ok. Thanks.

**Comment by srawlins** [comment]
I don't think you would use mockito for this purpose. The **test** package has a matcher called [returnsNormally](https://pub.dev/documentation/matcher/latest/matcher/returnsNormally-constant.html) (can be used like `expect(() => foo.add(...), returnsNormally);`.

**Comment by wondertalik** [comment]
> I don't think you would use mockito for this purpose. The **test** package has a matcher called [returnsNormally](https://pub.dev/documentation/matcher/latest/matcher/returnsNormally-constant.html) (can be used like `expect(() => foo.add(...), returnsNormally);`.

Thanks. That it was i looking for.
