### ISSUE TITLE
Can't stub generic function with nested function param of unknown type

### ISSUE THREAD

**Issue by AlexandrKedrov** [dart-lang/mockito#476]
Code:

```dart
abstract class Foo {
    T? foo<T>(Map<String, T Function()> options);
}

T? fooShim<T>(Map<String, T Function()>? options> {
    return null;
}

@GenerateMocks([], customMocks[
    MockSpec<Foo>(fallbackGenerators: {#foo: fooShim})
])
...
```

Error:
```
Invalid @GenerateMocks annotation: Mockito cannot generate a valid mock class which implements 'Foo' for the following reasons:
    The method 'Foo.foo' features a non-nullable unknown return type, and cannot be stubbed without a dummy generator specified on the MockSpec.
```

Call stack:
![image](https://user-images.githubusercontent.com/20287007/133883331-7260c5be-61d9-4268-a9df-818ffe1f082b.png)

Problem is that neither `hasFallbackGenerator` nor `isParameter` passed to the second `_checkFunction` call.

As stubbing generic function with `Map<>` or `T Function() ` should work(at least I hope so according to the current implementation), it is ambiguous their composition causes any trouble

**Comment by srawlins** [comment]
Thanks for the bug report and the initial investigation!
