### ISSUE TITLE
stub error in a post test with http library

### ISSUE THREAD

**Issue by Flavio-Vieirastack** [dart-lang/mockito#482]
hello guys I'm trying to test the get method using mockito, but it's giving me this error and I don't know what to do, can someone help me?
code:

import 'package:faker/faker.dart';
import 'package:http/http.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

import 'http_adapter_test.mocks.dart';

class HttpAdapter {
  final Client client;

HttpAdapter({required this.client});

Future<void> request({
  required Uri url,
  required String method,
  }) async {
await client.post(url);
  }
 }

@GenerateMocks([Client])
 void main() {
   group("post", () {
   test("Deve retornar post com valores corretos", () async {
  final client = MockClient();
  final sut = HttpAdapter(client: client);
  final url = Uri.parse(faker.internet.httpUrl());

  await sut.request(url: url, method: "post");

  verify(client.post(url));
    });
 });
 }

Error:

![Sem título](https://user-images.githubusercontent.com/85948951/136409946-e2b9ebeb-0d9d-4820-974e-a1de12679af2.png)

**Comment by srawlins** [comment]
Apologies for the late response.

Debugging questions like this are best asked on a forum like StackOverflow.

See in the error all of the other arguments passed to `post`, which must match the `verify` expectation.
