### ISSUE TITLE
Generator does not work with .g.dart classes

### ISSUE THREAD

**Issue by easeccy** [dart-lang/mockito#483]
When having following source code

**foo.dart**
```
part 'foo_bar.dart';

class Foo with Mix {}
```

**foo_bar.dart**
```
part of 'foo.dart';

mixin Mix {
  int get value => 0;
}
```

generated code is:
```
class MockFoo extends _i1.Mock implements _i2.Foo {
  MockFoo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get value =>
      (super.noSuchMethod(Invocation.getter(#value), returnValue: 0) as int);
  @override
  String toString() => super.toString();
}
```

When the file name changed to _foo.g.dart_

**foo.dart**
```
part 'foo.g.dart';

class Foo with Mix {}
```

**foo.g.dart**
```
part of 'foo.dart';

mixin Mix {
  int get value => 0;
}
```

Generated class is missing the `value`.

```
class MockFoo extends _i1.Mock implements _i2.Foo {
  MockFoo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}
```

**Comment by srawlins** [comment]
I cannot reproduce this error (at HEAD). Can you report your mockito version, and show (a snippet of) your .dart file which includes the `@GenerateMocks` annotaion (and import of foo.dart).

**Comment by easeccy** [comment]
Any progress on this?

**Comment by yringler** [comment]
Likewise tottally confused about mockito
The docs say to use @GenerateMocks, did that and... crickets.
No files generated.

```dart
import 'package:flutter/widgets.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

import 'json_loader.mock.dart';

@GenerateMocks([AssetBundle])
void main() {
  final mock = MockAssetBundle();
  group('json loader', () {});
}

**Comment by srawlins** [comment]
@easeccy  Sorry I still cannot reproduce:

1. `mkdir repro-483; cd repro-483`
2. write `pubspec.yaml` with mockito and build_runner dependencies, and SDK constraint >=2.12.0
3. `mkdir lib`
4. write your foo.dart example to `lib/foo.dart`, and your `foo_bar.dart` example to `lib/foo_bar.dart`.
5. `mkdir test`
6. write your `foo_test.dart` example to `test/foo_test.dart`, removing references to `flutter_test`, `expect`, and changing import URIs to reference file in `lib/`.
7. `pub run build_runner build`
8. `test/foo_test.mocks.dart` looks as yours does.
9. `mv lib/foo_bar.dart lib/foo.g.dart`
10. update reference in `lib/foo.dart` to its part.
11. `pub run build_runner build`
12. `test/foo_test.mocks.dart` still looks as yours does.

Can you confirm I've done what you expected? Perhaps the directory structure is different?

**Comment by srawlins** [comment]
@yringler Thanks for reporting this issue. Please report new issues as new issues. Your reproduction does not reference any files ending in `.g.dart` and does not seem related to this issue.

**Comment by yringler** [comment]
That's an active repo; I've tried using both import and part, seems I
removed it by the time I pushed.
 (Build would fail because of the missing import/part)
I'll make a new branch with the issue later today

**Comment by easeccy** [comment]
Issue is resolved in both repro case and the real codebase. I only updated the Flutter since the first appearence. I guess that fixed it.
