### ISSUE TITLE
@GenerateMocks  wrong type on flutter_bloc

### ISSUE THREAD

**Issue by andredealmei** [dart-lang/mockito#488]
`est/bloc_test.mocks.dart:57:37: Error: The parameter 'transformer' of the method 'MockCounterBloc.on' has type 'Stream<E> Function(Stream<E>,
Stream<E> Function(E))?', which does not match the corresponding type, 'Stream<E> Function(Stream<E>, Stream<E> Function(E))?', in the overridden
method, 'Bloc.on'.`

To see the full error, just clone [this repo](https://github.com/andredealmei/flutter_bloc_mockito_error) and run "flutter test"

**Comment by srawlins** [comment]
Thanks for the report and the repo!

**Comment by srawlins** [comment]
This proves to be a curious example of overrides. I've filed a Dart issue here: https://github.com/dart-lang/sdk/issues/47808

**Comment by srawlins** [comment]
Ah, mockito generates correct code; there was a bug in the VM that caused it to reject overrides like this. It is fixed in Dart 2.15 (not yet released).

**Comment by andredealmei** [comment]
> Ah, mockito generates correct code; there was a bug in the VM that caused it to reject overrides like this. It is fixed in Dart 2.15 (not yet released).


Thanks, i have upgraded to flutter beta and can confirm that is working now
