### ISSUE TITLE
mock function is only called in test file but no in real code

### ISSUE THREAD

**Issue by maestrolsj** [dart-lang/mockito#491]
- mockito: ^5.0.16
- flutter : 2.6.0-12.0.pre.1002

I mocked a "version" field from PackgeInfo class
It works when I print the filed inside Test function. 
but my original code on my screen still refer real class.

[Real code on loading screen ]
![image](https://user-images.githubusercontent.com/16445243/146010818-aedf71f0-907c-4c1a-a495-53d4d182181b.png)

[ Test code ]
![image](https://user-images.githubusercontent.com/16445243/146010416-73d6764c-5825-47dd-9e3d-63e34e338b65.png)

[ Generated mock class ]
![image](https://user-images.githubusercontent.com/16445243/146010503-a6498a60-9244-4553-85a8-e2d61bfe704f.png)

**Comment by srawlins** [comment]
@maestrolsj thanks for filing an issue. Please explain more what your issue is. I do not understand what you are expecting. Code in a test is (presumably) not imported into your app, so it cannot affect your app. What result do you expect and what is the actual result?

**Comment by maestrolsj** [comment]
> 

It is a test code for integration test to check if user's app is latest or not.
The actual code of version checking is needUpdate( ) function in "Loading_screen"

As you can see I mocked "packageInfo.version" with "9.9.9" as a return value.

I ran this test file on my simulator
$ flutter drive --driver=./test/e2e/driver.dart -d "iPhone 11" --target=./test/e2e/update_modal_test.dart

There are two "Prints" . one is in the test code the other one is in actual code in "Loading_screen"

[ Expected ]
- Test code prints "9.9.9"
- Actual code prints "9.9.9"  (as I mocked )

[ Happens ]
- Test code prints "9.9.9"
- Actual code prints "1.0.0"  (not mocked )

**Comment by srawlins** [comment]
I'm not sure what you mean by "actual code." If you mean the code found in the first screenshot (just a guess), then 9.9.9 will not be printed in that code: you construct a PackageInfo from `PackageInfo.fromPlatform` (another guess; I don't know what class this is and I don't know that `PackageInfo.fromPlatform` is a constructor). So this code has nothing to do with the code in the screenshot; it does not reference a MockPackageInfo object, and it does not create one.

(For future reference, screenshot images are not ideal for bug reports; I cannot copy/paste your code for a response, and I cannot copy/paste it to try myself.)
