### ISSUE TITLE
Unable to verify calls to a setter

### ISSUE THREAD

**Issue by bparrishMines** [dart-lang/mockito#498]
When a class contains a setter for a variable:

```dart
class MyClass {
  set myVariable(int myVariable) {
     // set variable
  }
}
```

`mockito` would generate the stub for it, but I wasn't able to find a way to access it and verify:

```dart
class MockMyClass {
  @override
  set myVariable(int? myVariable) =>
      super.noSuchMethod(Invocation.setter(#myVariable, myVariable),
          returnValueForMissingStub: null);
}
``` 

Using `verify(myMockClass.myVariable)` complains because you can't use a setter this way and I wouldn't be able to verify the value passed. 

My current workaround is:
```dart
void mockitoVerifySetterWorkaround(
  Mock mock,
  Symbol memberName,
  Object? argument,
) {
  verify<dynamic>(mock.noSuchMethod(
    Invocation.setter(memberName, argument),
    returnValueForMissingStub: null,
  ));
}
```

**Comment by srawlins** [comment]
Thanks for filing an issue. `verify(myMockClass.myVariable)` would verify a getter. Including an `=`, and arguments, would verify a setter.

**Comment by bparrishMines** [comment]
Ah, thanks! I tried that originally and it didn't work, but it looks like it is now. I must have been doing something wrong before.
