### ISSUE TITLE
Verify that a function is called with any argument

### ISSUE THREAD

**Issue by Hannnes1** [dart-lang/mockito#499]
I need to verify that a function I have is not called at all, with any argument. This could be done with `any` before null safety was introduced. Now that is not possible anymore. Is there another way to use `verify` and `verifyNever` without having to specify an exact argument?

I have looked at [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md), and it does mention that [`any` can't be used anymore](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#argument-matchers). However, it does not mention a solution.

**Comment by srawlins** [comment]
Thanks for filing an issue, @Hannnes1 . `any` might work great, for you! Unless the parameter type is non-nullable, in which case you'll need to change the mocking code in one of the ways mentioned in NULL_SAFETY_README (generate mocks, manually override a method with nullable parameter types). Can you provide a reproduction of code that does not work any more with null safety?

**Comment by Hannnes1** [comment]
So I figured out a solution to my problem. I had generated mocks for the class, but my problem was that I'm using [get_it](https://pub.dev/packages/get_it) as a service locator. The class with the method that I was trying to test therefore had the same type as the real class even if it was the mocked version. See example below:

```dart
import 'package:get_it/get_it.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

import 'mockito_example.mocks.dart';

final locator = GetIt.instance;

@GenerateMocks([Cat])
void main() {
  test('should return cat name', () {
    final cat = registerCat();

    CallCat().call();

    verify(cat.sound(any)).called(1);
  });
}

Cat registerCat() {
  final cat = MockCat();

  when(cat.sound(any)).thenAnswer((_) => 'Meow');

  locator.registerSingleton<Cat>(cat);
  return cat;
}

class Cat {
  String sound(int a) {
    return 'Meow';
  }
}

class CallCat {
  final Cat _cat = locator<Cat>();

  String call() {
    return _cat.sound(1);
  }
}
```

My solution was to add `as MockCat` to `final cat = registerCat();`. As I am writing this I also realize that there is no reason for `registerCat()` to have `Cat` as return type instead of `MockCat`, so I might as well change that to solve my problem.
