### ISSUE TITLE
flutter GraphQLClient call real network instead of using when 

### ISSUE THREAD

**Issue by tazik561** [dart-lang/mockito#500]
I am using `graphql_flutter: ^5.0.0`  and `  mockito: ^5.0.17` on my application. I am trying to make unit test for this so this is my test:

    @GenerateMocks([GraphQLClient])
    void main() {
      late SplashRemoteDataSourceImp mackApi;
      final _client = MockGraphQLClient();
      final injectClient = GraphClient(_client);
      setUp(() {
        mackApi = SplashRemoteDataSourceImp(injectClient);
      });
    
      group('Remote datasource', () {
        //arange
        test(
            "should return remote data when the call to remote data source is successfull",
            () async {
          final list = <LanguageResponseModel>[];
    
          final jsonMap =
              json.decode(fixture('languages.json')) as Map<String, dynamic>;
    
          // when(_client.query(any)).thenAnswer(
          //   (final _) async =>
          //       QueryResult(data: jsonMap, source: QueryResultSource.cache),
          // );
    
          for (final i in jsonMap['data']['languages']['listDto']['items']) {
            list.add(LanguageResponseModel.fromJson(i as Map<String, dynamic>));
          }
          final t = await mackApi.getLanguages();
   
          expect(t, ApiResult.success(data: list));
        });
      });
    }

I faced an unusual situation. As you can see I comment this part :

      // when(_client.query(any)).thenAnswer(
      //   (final _) async =>
      //       QueryResult(data: jsonMap, source: QueryResultSource.cache),
      // );

The problem is here? Why in unit test, real network call happens? and my test is passed?

    => request: POST https://.....s/graphql,
    => headers: {
      "connection": "keep-alive",
      "content-type": "application/json",
      "date": "Wed, 05 Jan 2022 18:13:32 GMT",
      "content-length": "640",
      "server": "nginx/1.14.2"
    },
    <- statusCode: 200,
    <- responseString: {
      "data": {
        "__typename": "Queries",
        "languages": {

Why graph client call network ? means real call ?

**Comment by srawlins** [comment]
Thanks for filing an issue!

I'm unfamiliar with these packages. You'll have to walk through the code and see what `SplashRemoteDataSourceImp.getLanguages()` does, and how it uses, or does not use, the GraphClient passed into the constructor.

**Comment by tazik561** [comment]
> Thanks for filing an issue!
> 
> I'm unfamiliar with these packages. You'll have to walk through the code and see what `SplashRemoteDataSourceImp.getLanguages()` does, and how it uses, or does not use, the GraphClient passed into the constructor.

this is my method: 
```
class SplashRemoteDataSourceImp extends SplashRemoteDataSource {
  SplashRemoteDataSourceImp(this._client);
  final GraphClient _client;

  @override
  Future<ApiResult<List<LanguageResponseModel>>> getLanguages() async {
    try {
      final result = await _client.query(
        mainPath: ServerPath.cms,
        requiredToken: false,
        query:
            ' { languages(filter:{}) { listDto{ count items { id slug name flagUrl languageDirection } } } } ',
      );

      if (result.hasException) {
      }

      return ApiResult.success(data: list);
    } on Exception catch (e) {
      
    }
  }
```

**Comment by srawlins** [comment]
Please re-open if you can provide more info.
