### ISSUE TITLE
Detect when we try to create subclasses of sealed classes

### ISSUE THREAD

**Issue by natebosch** [dart-lang/mockito#522]
Otherwise the error coming from analyzer later is more confusing. Ideally we'd make an error with a message that gives some pointers towards a workaround.

**Comment by Stumblinbear** [comment]
In Dart 3, mockito is unable to generate valid mocks for classes which use return types that are marked as `sealed class`.

**Comment by hongfeiyang** [comment]
Same here. the generated mocks try to implement a sealed class.

**Comment by yanok** [comment]
@natebosch I assume this bug was filed for a `@sealed` annotation, right? Can we assume it's going to fade away now, with Dart3 support for real sealed classes?

@Stumblinbear you now can use `provideDummy`/`provideDummyBuilder` functions to give Mockito a dummy value of the sealed class. This should help with the sealed return types.

@hongfeiyang Have you tried the version from the master branch? We shouldn't try to implement sealed classes anymore.

**Comment by srawlins** [comment]
> I assume this bug was filed for a @sealed annotation, right? Can we assume it's going to fade away now, with Dart3 support for real sealed classes?

I'm not sure it will go away, but it is certainly less interesting than it used to be. With the addition of the more powerful concepts in Dart 3, I think it would be lower priority to help users using `@sealed`.

**Comment by natebosch** [comment]
> Can we assume it's going to fade away now, with Dart3 support for real sealed classes?

We still want to make sure we have a nice user facing error if we have a `MockSpec` pointing to a `sealed`, `final`, or `base` class? Do we already have that checking?

**Comment by yanok** [comment]
The current situation is:
* for the Dart3's class modifiers we do check for `sealed`/`final` or `base` classes and refuse to mock them: https://github.com/dart-lang/mockito/blob/cca4858ad0f1e3930ebdcc6faf4a918616cca48c/lib/src/builder.dart#L748-L760
  for `sealed` we suggest trying with one of its variants (could be confusing if they are all `final`).
* for the `@sealed` annotation we just add `// ignore_for_file: subtype_of_sealed_class` to the generated code, which could lead to problems if the code assumes exhaustiveness, like
  ```dart
  @sealed
  abstract class S {}
  class A extends S {}
  class B extends S {}
  int f(S s) {
    if (s is A) {
      return 0;
    } else if (s is B) {
      return 1;
    }
    throw StateError('impossible'); // MockS will end up here.
  }
  ```
  probably it makes more sense to refuse mocking of `@sealed` classes as well.

**Comment by natebosch** [comment]
> * for the Dart3's class modifiers we do check for `sealed`/`final` or `base` classes and refuse to mock them

👍 


> * probably it makes more sense to refuse mocking of `@sealed` classes as well.

It would be fine either way. We won't be getting new usage of `@sealed` going forward, so fixing this isn't likely to have long term payoff.

**Comment by yanok** [comment]
Thanks for confirmation! Going to close this as completed then.
