### ISSUE TITLE
Deprecate private-ish public APIs by 3.0.0?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mockito#53]
* Answering
* Expectation
* PostExpectation
* VerificationResult
* Verification

Do we need these? I'll check internal uses as well.

**Comment by TedSander** [comment]
These seem to all be exposed to the client in some way.
Answering is a typeDef used in thenAnswer which seems like a good idea to keep the typedef if people want to use it.
Same with Expectation it is used in when
PostExpectation is class returned by when
similar with VerficiationResult/Verification

Are you just suggest we return dynamic instead? Seems safer to have have the typedefs and the classes.

**Comment by srawlins** [comment]
I'd love to get this resolved in the next few months, releasing 3.0.0 in Q1. @TedSander I wonder if `when` can return a private class to really discourage ever... assigning to a variable. Is that ever needed? I'm not sure I've ever seen a good reason to store things like this...

But even then, can there be a greater negative consequence by making PostExpectation private, etc.?

**Comment by TedSander** [comment]
I'd be OK with making them private if it doesn't impair the primary use cases.

**Comment by matanlurey** [comment]
I think there isn't anything actionable here anymore.
