### ISSUE TITLE
flutter GenerateMocks is not generated mock class

### ISSUE THREAD

**Issue by tazik561** [dart-lang/mockito#536]
I am trying to use `@GenerateMocks` on my test method, This is my dev dependancies:

    dev_dependencies:
      test: any
      flutter_test:
        sdk: flutter
      flutter_driver:
        sdk: flutter
      integration_test:
        sdk: flutter
      flutter_lints: ^1.0.4
      build_runner: ^2.1.4
      mockito: ^5.0.0
      mocktail: ^0.2.0

and I am using like this: 

    @GenerateMocks([CustomerPOAutocompleteState])
    void main() {
      TestWidgetsFlutterBinding.ensureInitialized();

But after running `flutter pub run build_runner build` nothing is generated? 

```
alt@Alis-MacBook-Pro rr-portal-front % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-AM)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
alt@Alis-MacBook-Pro rr-portal-front % 
```

**Comment by srawlins** [comment]
Can you show the terminal output of `flutter pub run build_runner build`? And then the contents of `.dart_tool/build/generated/<your package>`? The generated file should be under there somewhere.

**Comment by srawlins** [comment]
That's too bad. It should be generated there. :(

Are you able to create a minimal reproduction that I can execute?

**Comment by TomBenaiteau** [comment]
@tazik561 Can you look your build.yaml maybe the file you want to mock is not include in the source of the build.yaml

**Comment by BenjiFarquhar** [comment]
@tazik561 Me too.  Did yours start working?

**Comment by tazik561** [comment]
I did not use it and used the same method of making a traditional Mock

**Comment by srawlins** [comment]
Sorry for the delay. @tazik561 can you say where the test file is, with `@GenerateMocks`? It should be in your package's `test/` directory.

**Comment by BenjiFarquhar** [comment]
@srawlins  Mine works after doing that. Thanks.

**Comment by TinhHuynh** [comment]
This should be mentioned in the documentation :(

**Comment by mnelsonwhite** [comment]
This is an extremely annoying design choice. Why does this constraint exist?
