### ISSUE TITLE
After migrating my code to flutter null safety I have some issues in some methods (anyNamed("") , any, captureAny )

### ISSUE THREAD

**Issue by aboud-masoud** [dart-lang/mockito#542]
in my unit test these methods now return Null (anyNamed(""), any, captureAny ), and my methods did not accept null as a argument, so what is the replacement for these methods?

previously before migrating these methods working fine with me but now i don't know what to do in these cases

**Comment by Saleh-Yousef** [comment]
Facing the same issue, any suggestions?

**Comment by srawlins** [comment]
All generated mocks have methods with nullable parameters. Have you reviewed https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md?

**Comment by matux** [comment]
I'm having the same issue, I think the problem is that both the parameter _and_ the return value are non-null.

This is the abstract class:
```dart
abstract class Sender {
  Future<bool> send(JsonMap payload);
}
```

And this is the Mock implementation:
```dart
class MockSender extends Mock implements Sender {
  @override
  Future<bool> send(JsonMap? payload) async {
    return super.noSuchMethod(
      Invocation.method(#send, [payload]),
      returnValue: Future<bool>.value(true),
    );
  }
}
```

And the error:

```
type 'Null' is not a subtype of type 'FutureOr<bool>'
MockSender.send
```

**Comment by srawlins** [comment]
All generated mocks have methods with nullable parameters. Have you reviewed https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md?

**Comment by matux** [comment]
> All generated mocks have methods with nullable parameters. Have you reviewed https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md?

Yes I have. I'm doing a manual mock implementation.

The documentation says:

> Only public methods (including getters, setters, and operators) which either have a non-nullable return type, or a parameter with a non-nullable type, need to be overridden. For each such method:

So, I'm hung with the "either" part. Is that an exclusive or? Can I mock over methods that have _both_ a non-nullable return type _and_ a non-nullable parameter?

**Comment by matux** [comment]
Thanks for the clarification. I managed to find the issue in my code, which was unrelated to the Mock itself, and now it's working with both non-nullable parameter and return value!
