### ISSUE TITLE
Consider generating method overrides when the type-to-mock is in a null safe library

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#555]
Right now, if mockito is generating a mock class because of an annotation in a pre-null safe library, it will not generate overrides (see `if (sourceLibIsNonNullable)` in the code). This is mostly to avoid generating code which is unnecessary, not out of any issue of correctness.

However, @jakemac53 found a case like so:

```dart
// foo.dart
abstract class Foo {
  String bar;
}

String getBarLength(Foo foo) => (foo.bar ?? '').length;

// foo_test.dart
// @dart=2.9
@GenerateMocks([], customMocks: [MockSpec<Foo>(onMissingStub: OnMissingStub.returnDefault)])
void main() {
  var foo = MockFoo();
  getBarLength(foo);
}
```

In migrating `foo.dart` to null safety, static analysis wants us to remove `?? ''`, as `bar` is now non-nullable. If we did that, the code now has a runtime error, because `Foo.bar` was not overridden in `class MockFoo`, and so `foo.bar` will return `null`.

**Comment by yanok** [comment]
This should be fixed by 0660e6112086886e9e9bac93d834da6b0bf7fbbc
