### ISSUE TITLE
Error in combining mock and getter 

### ISSUE THREAD

**Issue by TuanPhong15** [dart-lang/mockito#556]
**I'm using mockito to fake the status of the internet connection, but it returns an error :** 
`type 'Null' is not a subtype of type 'Future<bool>'`
Code below: 

- network_info.dart
```
import 'package:internet_connection_checker/internet_connection_checker.dart';
abstract class NetworkInfo {
  Future<bool> get isConnected;
}
class NetworkInfoImpl implements NetworkInfo {
  NetworkInfoImpl();
 static final InternetConnectionChecker internetConnectionChecker =
      InternetConnectionChecker();
  @override
  Future<bool> get isConnected {
    return internetConnectionChecker.hasConnection;;
  }
}
```
- 
```
class MockNetworkInfo extends Mock implements NetworkInfoImpl {}

void main() {
  MockNetworkInfo mockNetworkInfo = MockNetworkInfo();
  test('test online', () async {

    final isConnected = await mockNetworkInfo.isConnected; //bug in this line
  });
}
```

  _**mockito: ^5.3.0
  flutter: 3.0.5**_

**Comment by srawlins** [comment]
Please show how you generate your mock class, with something like [`@GenerateMocks`](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md).

**Comment by TuanPhong15** [comment]
> Please show how you generate your mock class, with something like [`@GenerateMocks`](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md).

I have edited, I tried with `implements NetworkInfoImpl` and `implements NetworkInfo` but it still didn't work.

**Comment by srawlins** [comment]
This code will not work. The mock class returns null for a getter, `isConnected`, wirth a non-nullable type. Please see [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md) for how to use mockito in null safe code.
