### ISSUE TITLE
Generator should refuse to generate mock if there are members returning `Future<T>` if `T` is potentially non-nullable

### ISSUE THREAD

**Issue by yanok** [dart-lang/mockito#560]
Example:

```dart
@GenerateMocks([Foo])
import 'test.mocks.dart';

abstract class Foo<T> {
  Future<T> m();
}
```

currently Mockito will happily generate a mock, but it's impossible to use it with non-nullable `T` and set an expectation for `m`, since overloaded method passes `returnValue: Future<T>.value(null)` to `super.noSuchMethod`.

**Comment by RafaelNagai** [comment]
I think this topic can help you
https://github.com/dart-lang/mockito/issues/559

I solved my problem using:
``` dart
@GenerateMocks(
  [],
  customMocks: [
    MockSpec<Foo<Bar>>(
      as: #MockFoo
    )
  ],
)
```

**Comment by srawlins** [comment]
Thanks for the link, @RafaelNagai. If you'll notice, @yanok opened both that issue and this one 😉 

This issue stands though, as it is described above.

**Comment by zhanglix** [comment]
Maybe you can try my workaround #592

**Comment by yanok** [comment]
This is obsolete now, closing.
