### ISSUE TITLE
Generated mocks should ignore deprecatedmember_use

### ISSUE THREAD

**Issue by noinskit** [dart-lang/mockito#565]
It can make sense to create a mock of a class that has deprecated members, uses deprecated libraries (with the class itself not being deprecated).

For example, I need to mock `PeopleResource` from `package:googleapis/people/v1.dart` which uses deprecated fields in its implementation (although I'm not using any of them directly) and I'm getting the following analyzer warning that I can't get rid of:
```
info: 'package:googleapis/shared.dart' is deprecated and shouldn't be used. Avoid importing this library. Use the members defined in the target API library instead.. (deprecated_member_use at [lifepal_app] test/services/google_people_test.mocks.dart:11)
```

**Comment by cubuspl42** [comment]
I like this idea! In general, in my personal opinion, it would be great if Dart code generators would generate code with good support for restrictive Analyzer configuration.

**Comment by fzyzcjy** [comment]
+1 Is there any updates?

**Comment by srawlins** [comment]
No updates

**Comment by Merrit** [comment]
Is there a workaround so this doesn't show up as a warning in a project, without having to edit generated code?
