### ISSUE TITLE
build_runner execution time becomes extremely slow after upgrading from 5.2.0 to 5.3.0

### ISSUE THREAD

**Issue by lcdsmao** [dart-lang/mockito#566]
We are also using other code generation libraries like freezed, json_serializable, etc.

The average execution time of build_runner when using mockito 5.3.0 and 5.2.0:

- 5.2.0: 3m
- 5.3.0: 10m

**Comment by srawlins** [comment]
Yikes, that is really long!

**Comment by kuhnroyal** [comment]
Yea this really hurts the dev speed 😥

**Comment by srawlins** [comment]
I haven't investigated yet, but a few questions:

* Can you show your version of analyzer and code_builder, from pubspec.lock?
* Can you list your Dart/Flutter version?
* If you `dart pub upgrade`, does it get better? I'm wondering if code_builder 4.3.0 would help.
* If you upgrade Dart to 2.18.0 (not sure of the equivalent flutter version...), and `dart pub upgrade`, does it get better?

**Comment by kuhnroyal** [comment]
It looks like it is back to normal with Dart 2.18.1 and:

```yaml
mockito: 5.3.2
code_builder: 4.3.0
```

**Comment by srawlins** [comment]
Great! Please feel free to re-open if it drops again.
