### ISSUE TITLE
How to stub a getter with a manually implemented Mock class?

### ISSUE THREAD

**Issue by juskek** [dart-lang/mockito#576]
Hi there, great package! 

I just started using Mockito and so this might be a silly question, but is it possible to stub a getter with a manually implemented Mock class?

E.g. 
1. After creating a dart interface and extending it as a Mock class,

```dart
/// some interface
abstract class IExampleClass {
    double get exampleVar;

}

/// manually create mock
class MockExampleClass extends Mock implements IExampleClass {}
```

2. I can run it in a test file, but cannot stub it.

```dart 
void testExample() {
    var mockExampleClass = MockExampleClass();

    when(mockExampleClass.exampleVar).thenReturn(0.0);

    // THROWS ERROR: The following _TypeError was thrown running a test:
   // type 'Null' is not a subtype of type 'double'
}

```
I suspect that it is due to a missing stub, but am not sure how to circumvent this issue.

Would appreciate any guidance!

**Comment by juskek** [comment]
More INFO: Trying to run the same test works when the Mock class is generated automatically with annotations,

e.g.
```dart
@GenerateNiceMocks([MockSpec<IExampleClass>()]) // auto create mock
abstract class IExampleClass {
    double get exampleVar;
}

```
```dart
void testExample() {
    var mockExampleClass = MockIExampleClass();

    when(mockExampleClass.exampleVar).thenReturn(1.0);
    expect(mockExampleClass.exampleVar, 1.0); // verify getter was stubbed

    // test passes!
}

```

**Comment by srawlins** [comment]
Please see the [NULL_SAFETY_README](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#manually-override-a-method-with-a-non-nullable-return-type) for how to override a method (or getter) with a non-nullable return type.

**Comment by juskek** [comment]
THANK YOU!

Manually creating the Mock class and overriding with super.noSuchMethod worked! 
```dart
class MockExampleClass extends Mock implements IExampleClass {
  @override
  double get exampleVar =>
      super.noSuchMethod(Invocation.getter(#exampleVar), returnValue: double.nan);
}
```
