### ISSUE TITLE
A method with a return type of Offset is not created.

### ISSUE THREAD

**Issue by bosskmk** [dart-lang/mockito#580]
Mock the class like below.
```dart
@GenerateNiceMocks([
  MockSpec<TestClass>(),
])

class TestClass {
  Offset getOffset() {
    return const Offset(0, 0);
  }

  int getInt() {
    return 0;
  }
}
```

If the return value is Offset , the method is not created.
```dart
/// A class which mocks [TestClass].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestClass extends _i1.Mock implements _i10.TestClass {
  @override
  int getInt() => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}
```

It was created in the past, but it is not created at any time after updating the version.
```
mockito: ^5.3.2
build_runner: ^2.2.0
```

**Comment by bosskmk** [comment]
Previously, even if the return value was Offset, it was generated.
```dart
@override
_i5.Offset toDirectionalOffset(_i5.Offset? offset) => (super.noSuchMethod(
     Invocation.method(
       #toDirectionalOffset,
       [offset],
     ),
     returnValue: _FakeOffset_13(
       this,
       Invocation.method(
         #toDirectionalOffset,
         [offset],
       ),
     ),
     returnValueForMissingStub: _FakeOffset_13(
       this,
       Invocation.method(
         #toDirectionalOffset,
         [offset],
       ),
     ),
   ) as _i5.Offset);
```

**Comment by bosskmk** [comment]
Add that method to `fallbackGenerators` and run build_runner again.
And delete `fallbackGenerators` and run build_runner again.
The file was created normally.

Does this have anything to do with caching?
Even after `flutter clean`, the problem persisted, but when I tried again, it was created normally without knowing why.

**Comment by srawlins** [comment]
Is `Offset` a generated class? If the element cannot be resolved, it will be deemed `dynamic`, and then an override will not be generated.

**Comment by bosskmk** [comment]
Offset is a class in flutter's material or ui/geometry.dart.

I don't know why, but it's been fixed.
