### ISSUE TITLE
Mockito doesn't work in integration test

### ISSUE THREAD

**Issue by LucasXu0** [dart-lang/mockito#594]
I added a `@GenerateMocks([FilePicker])` under the `integration_test` path. But nothing generates after executing `flutter pub run build_runner build`.

But it works fine in the unit test. So, does mockito work in the integration tests?

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/mockito/issues/545 and https://github.com/dart-lang/mockito/issues/550

**Comment by alanrubin** [comment]
Seems this was finally solved by Mockito 5.4.0 - just configure the build.yaml as https://stackoverflow.com/a/68275812 (and obviously upgrade Mockito to v5.4.0+)
