### ISSUE TITLE
Exclude class from being generated with @GenerateNiceMocks

### ISSUE THREAD

**Issue by DjordjeMancic97** [dart-lang/mockito#595]
So a bit of context what I am trying to achieve:

There is a custom HttpClient which I want mocked but internally it is interacting with another custom class which is acting as a response wrapper.

So functions outside the test which are using the client are accessing the response through that custom class, example CustomResponse.json - to get response data in json. 

Problem is, Mockito is generating mock for HttpClient and all other classes involved, including the CustomResponse. So when I try to test a function which is using the CustomResponse in any way I get FakeUsedError. I don't really need the CustomResponse to be a mock, is there an option to somehow exclude it?

**Comment by srawlins** [comment]
What is the behavior that you want? A mock _implements_ a class, and in no way _extends_ it, so you do not get any functionality from the class being mocked.

**Comment by DjordjeMancic97** [comment]
> What is the behavior that you want? A mock _implements_ a class, and in no way _extends_ it, so you do not get any functionality from the class being mocked.

Let me try to further clarify :

```
class CustomHttp {

 Future<CustomResponse> makeRequest() async {
     return CustomResponse;
}
}
```

Code above is just an example, I generated mocks for CustomHttp and it also mocked the CustomResponse class. This creates a problem because CustomResponse has its own properties which I want to access and I can't do that if it's a fake. So I was asking if there is a way for me to say "generate mocks for CustomHttp class but not the CustomResponse inside of it"...

**Comment by srawlins** [comment]
Did you try stubbing `makeRequest` with `when(foo.makeRequest()).thenAnswer((_) => whateverCustomResponseYouWant)`?

**Comment by DjordjeMancic97** [comment]
> Did you try stubbing `makeRequest` with `when(foo.makeRequest()).thenAnswer((_) => whateverCustomResponseYouWant)`?

Yes, problem was stub request arguments were not the same as in the real call.. My bad. Thanks for replying, will close the issue.
