### ISSUE TITLE
Generating mocks mixing in `MockPlatformInterfaceMixin`

### ISSUE THREAD

**Issue by AsturaPhoenix** [dart-lang/mockito#603]
Automatic mock generation currently requires that mixins implement the type being mocked, which precludes mixins like [`MockPlatformInterfaceMixin`](https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/MockPlatformInterfaceMixin-class.html).

Simply removing the check seems to produce no ill effects for me:
```diff
       }
       final mixinInterfaceType =
           _determineDartType(typeToMixin, entryLib.typeProvider);
-      if (!mixinInterfaceType.interfaces.contains(type)) {
-        throw InvalidMockitoAnnotationException('The "mixingIn" type, '
-            '${typeToMixin.getDisplayString(withNullability: false)}, must '
-            'implement the class to mock, ${typeToMock.getDisplayString(withNullability: false)}');
-      }
       mixins.add(mixinInterfaceType);
     }
```
https://github.com/AsturaPhoenix/mockito/commit/9d36e917de6d4bc004abda2ee2b54f9b31ab4fb2

Example usage:
```dart
@GenerateNiceMocks([
  MockSpec<TripPlannerHttpClient>(),
  MockSpec<http.Client>(),
  MockSpec<PermissionHandlerPlatform>(mixingIn: [MockPlatformInterfaceMixin]),
  MockSpec<GeolocatorPlatform>(mixingIn: [MockPlatformInterfaceMixin]),
])
import 'harness.mocks.dart';
```
https://github.com/AsturaPhoenix/trip_planner_aquamarine/blob/6f1356e2b7d82a817f0dabb63aff1fe686c19275/test/util/harness.dart#L24-L25

Is there a story behind this? I'd be open to doing further investigation and a short pull request.

**Comment by srawlins** [comment]
I don't know of a  specific reason to require the mixin to implement the type-to-mock.

I think when `mixingIn` was implemented, the use cases were to bring in mixins which _do_ implement the type-to-mock.

CC @yanok

**Comment by yanok** [comment]
Sorry, I have zero context on this, this error seems to be there since the first addition of  `mixingIn` support in https://github.com/dart-lang/mockito/commit/b6d49ba86480fc1c5a1a8abc624ed82d0a40f690.

I would guess that we usually expect a mock to have **exactly** the same API as the type it mocks. While if the mixin doesn't implement the type-to-mock, the API of the resulting mock can be wider. But I don't know for sure.

**Comment by srawlins** [comment]
> I would guess that we usually expect a mock to have exactly the same API as the type it mocks.

Yeah definitely. `mixingIn` was brought in to support some very obscure cases, specifically to allow a language change where private members do not get generated by `noSuchMethod`.

@AsturaPhoenix could you detail a little what your use case is for using `mixingin`?

**Comment by AsturaPhoenix** [comment]
[Mocking a Flutter plugin's platform interface](https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests#mock-the-plugins-platform-interface) is one of the strategies for testing a Flutter app with federated native plugins. [MockPlatformInterfaceMixin](https://github.com/flutter/plugins/blob/729c14a9243ebd2b16d7ec2a63b4e54661b00641/packages/plugin_platform_interface/lib/plugin_platform_interface.dart#L113-L129) is a marker interface that [bypasses](https://github.com/flutter/plugins/blob/729c14a9243ebd2b16d7ec2a63b4e54661b00641/packages/plugin_platform_interface/lib/plugin_platform_interface.dart#L90) the [token verification](https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/PlatformInterface/verify.html) normally done on federated plugin implementations.

**Comment by natebosch** [comment]
Does it work to do

```dart
@GenerateNiceMocks([MockSpec<MockablePermisionHandlerPlatform>()]);
import 'foo_test.mocks.dart';

abstract class MockablePermissionHandlerPlatform implements PermissionHandlerPlatform, MockPlatformInterfaceMixin {}
```

**Comment by yanok** [comment]
Yes, I believe both this and the other way around (first creating a mock class and then trivially extending it and making a subtype of `MockPlatformInterfaceMixin`) should work.
