### ISSUE TITLE
Is there any way to customise the generated mocks?

### ISSUE THREAD

**Issue by yasht01** [dart-lang/mockito#606]
I am trying to mock the `File` class using `mockito` but the `length` getter returns 0 as mentioned in the generated file. Is there any value to customise the return value?

**Comment by srawlins** [comment]
No there is not. What is your use case?

**Comment by srawlins** [comment]
Questions like this are better asked at user forums which have many more eyes to answer.

**Comment by yasht01** [comment]
I was trying to create a temporary file having some content using mockito. Anyways, I created a temporary file using `dart:io` for my use case. Yeah my bad, I'll ask these in the user forums next time onwards.
