### ISSUE TITLE
Mockito needs significantly more documentation

### ISSUE THREAD

**Issue by Hixie** [dart-lang/mockito#64]
The dartdocs for mockito leave much to be desired.

Here are some random examples:

* `when` has no docs and the library itself has no top-level docs (as far as I can tell these are the two most important things in mockito).

* One of the first things in the README is:

  > ## Let's verify some behaviour!
  > ```dart
  > //using mock object
  > cat.sound();
  > //verify interaction
  > verify(cat.sound());
  > ```
  > Once created, mock will remember all interactions. Then you can selectively verify whatever interaction you are interested in.

  I have no idea what any of that means. The word "verify" is never defined. The dartdocs for `verify` are blank.

* The README references `throwOnMissingStub` in a code sample with no prose. That method doesn't seem to exist.

* The word "answer" appears exactly once in the README, with no commentary, and there's no dartdocs for either `PostExpectation.thenAnswer` or `Answering`.

**Comment by srawlins** [comment]
Hi @Hixie, thanks for collecting these. I've just sent a PR to start addressing these.

As for the README, and broader explanations, I'd appreciate PRs. I don't think I'd be good at explaining the concepts of mocking from the inside.

**Comment by srawlins** [comment]
@Hixie Anything else needed?

**Comment by Hixie** [comment]
I've no idea. Can someone who knows nothing about mockito successfully and with no effort use every feature mockito provides without using any documentation other than the dartdocs?

See also the "Documentation comments (dartdocs)" section of https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo for inspiration.

**Comment by srawlins** [comment]
I think we're pretty good now. All elements seem to have docs.
