### ISSUE TITLE
mockito fails to generate code if return type of a method is a typedef that ignores its argument

### ISSUE THREAD

**Issue by yanok** [dart-lang/mockito#642]
An example (I didn't test this specific example, but it should trigger the bug I think):

```dart
import 'other_lib.dart' show SomeType;
typedef Ignore<T> = String;

class C {
  Ignore<SomeType> m() => '';
}

@GenerateNiceMocks([MockSpec<C>()])
void main() {}
```

While generating an override for `C.m` Mockito will fail to import `SomeType` and throw. This is because somehow `_TypeVisitor` doesn't get to ignored arguments, but I'm not sure about the details.

**Comment by fishythefish** [comment]
If that example doesn't work, try

```dart
typedef Ignore<T extends SomeType> = String;
```

In the case I ran into, `SomeType` was itself a generic, with no type arguments provided to it in the typedef, but a specific type argument provided at the use site. I'm not sure which occurrence was responsible for the issue.

**Comment by yanok** [comment]
Apparently we always unroll non-function aliases, but only unroll function ones if needed (alias is private). I guess that originates from times when non-function aliases didn't exist. That's why this bug is rather rare. It's only triggered for function aliases ignoring type parameters.
