### ISSUE TITLE
How to using mockito with coverage

### ISSUE THREAD

**Issue by redevrx** [dart-lang/mockito#650]
I want to write Flutter unit tests using Mockito, and it works fine. However, when it comes to test coverage, it doesn't work with the mock code. Does anyone have a solution to this problem?

**Comment by yanok** [comment]
Could you please be more specific? What exactly doesn't work? Error message? Steps to reproduce?

Thanks!

**Comment by redevrx** [comment]
@yanok Hello, I want to set up a pre-commit hook that runs the "flutter analyze" command. When it encounters incorrect code, it will report an error and prevent the commit from proceeding. This works well. However, when I use "flutter pub run dart_code_metrics:metrics analyze lib", it detects incorrect code but doesn't stop the process. It continues running until the pre-commit hook is finished.

**Comment by srawlins** [comment]
Without specifics (minimal repro, steps to reproduce, coverage report), I can guess that what you describe sounds correct. Using a mock of a class Foo will execute 0 lines of code in Foo, as the mock _implements_ Foo, and does not _extend_ Foo.

**Comment by yanok** [comment]
ok, I'm going to close this as "working as expected".
