### ISSUE TITLE
How to parse any() to not null parameter.

### ISSUE THREAD

**Issue by Nikzed** [dart-lang/mockito#687]
I have a use case with not Null incoming parameter.
```
@override
  Future<bool> call({required DrawerItem params}) async {
  ...
  }
```
and I do want to test it the next way:
```
when(_doSomethingUseCase.call(params: any())).thenAnswer((_) => Future.value(false));
```
but I do have the next problem with ```any()```
```
An expression whose value is always 'null' can't be dereferenced.
Try changing the type of the expression.dart[invalid_use_of_null_value](https://dart.dev/diagnostics/invalid_use_of_null_value)
```

Is there any way to mock this behavior?

**Comment by Nikzed** [comment]
Is this a right way to declare mock classes?
```
late final MockDoSomethingUseCase _doSomethingUseCase;

setUp(() {
      _doSomethingUseCase= MockDoSomethingUseCase();
    });
```
Found in readme about [stubbing](https://github.com/dart-lang/mockito/blob/master/README.md#how-about-some-stubbing)

> The [when](https://pub.dev/documentation/mockito/latest/mockito/when.html), [thenReturn](https://pub.dev/documentation/mockito/latest/mockito/PostExpectation/thenReturn.html), [thenAnswer](https://pub.dev/documentation/mockito/latest/mockito/PostExpectation/thenAnswer.html), and [thenThrow](https://pub.dev/documentation/mockito/latest/mockito/PostExpectation/thenThrow.html) APIs provide a stubbing mechanism to override this behavior. Once stubbed, the method will always return stubbed value regardless of how many times it is called. If a method invocation matches multiple stubs, the one which was declared last will be used. It is worth noting that stubbing and verifying only works on methods of a mocked class; in this case, an instance of MockCat must be used, not an instance of Cat.

Thanks to this kind guy issue https://github.com/dart-lang/mockito/issues/364

**Comment by srawlins** [comment]
> but I do have the next problem with any()

Are you certain you are using this mockito package? We do not have a function called `any()`. There is a top-level property called [`any`](https://pub.dev/documentation/mockito/latest/mockito/any.html).

**Comment by yanok** [comment]
Anyway, it looks like that's an instance of "you *must* declare your mocks to have static mock type", since we are doing overrides. I think we can just close it.

**Comment by Nikzed** [comment]
> Anyway, it looks like that's an instance of "you _must_ declare your mocks to have static mock type", since we are doing overrides. I think we can just close it.

Yes, this is definitely was in generated file .mock
