### ISSUE TITLE
5.4.2 incompatible with Freezed 2.4.2

### ISSUE THREAD

**Issue by rxseb** [dart-lang/mockito#691]
Mockito 5.4.2 is not compatible with freezed 2.4.2 due to analyzer ^6.0.0 requirement.

I noticed analyzer compatibility have been increased on master already. Until next release it is a blocker for our project, since we need latest freezed to handle Dart 3 records.

In order to get some visibility on our side, when is the next release planned?

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/mockito/commit/ff79de69e9ef9e8647bd6008c29c16651c9ac220 – publish coming soon!
