### ISSUE TITLE
Bump Analyzer version to >6 

### ISSUE THREAD

**Issue by momrak** [dart-lang/mockito#706]
The version of analyzer
`  analyzer: '>=5.12.0 <7.0.0'`
is causing issues with several packages as they are starting to use version `>=6`.

It is mentioned in #691 and also  https://github.com/localizely/intl_utils/issues/117. There are probably more packages.

Is there a new release planned for this package any time soon?

**Comment by kuhnroyal** [comment]
Probably a duplicate of https://github.com/dart-lang/mockito/issues/691

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/mockito/commit/ff79de69e9ef9e8647bd6008c29c16651c9ac220 – publish coming soon!
