### ISSUE TITLE
Migrate syntax to be 2.0-primary

### ISSUE THREAD

**Issue by srawlins** [dart-lang/mockito#71]
Today a user can write `when(cat.eatFood(any))...;`, in Dart 1. This has always been odd because `eatFood` accepts a String, not an ArgMatcher (the return value of `any`). But Dart 1 was okie dokie with this, and it allowed for a great mocking library. Dart 2 is not ok with this, hence the [Strong Mode compliance API](https://github.com/dart-lang/mockito#strong-mode-compliance). We should switch mockito to ultimately only support the Dart 2 type system, i.e. make `when(cat.eatFood(any))...;` look like today's `when(cat.eatFood(typed(any)))...;`.

This is absolutely a breaking change, and will be the primary feature that bumps us to Mockito 3.0. It also prevents some old mocking behavior:

`when(obj.fn(any, null))` will no longer be allowed (null in arg list with `any`), as mentioned in the strong mode compliance docs. We'll require `when(obj.fn(any, argThat(equals(null)))`. I think we can introduce `nullArg` or something...

We can also keep `typed` around as an identity function, to allow users to migrate gracefully (except the case above).

**Comment by Aetet** [comment]
Any progress on this?

**Comment by srawlins** [comment]
Not yet. Dart 2.0 won't be final for a few months yet, but I suppose this request isn't really tied to that.

**Comment by Anrock** [comment]
@srawlins any progress on this?

**Comment by srawlins** [comment]
A solution for this is being pursued in #83 . Sorry for not linking earlier. Might make more progress this week.

**Comment by srawlins** [comment]
Marking this closed. New API is available in released version 3.0.0-beta.
