### ISSUE TITLE
Support for extension-type/inline-class

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/mockito#732]
It's probably too early and/or too minor, but would it be possible to already support extension types (like with `-nullsafety`)? The experiment has been enabled by default in the Dart dev version for a while now.

For example, if I have a getter returning an extension type, this is what I get:

```
Bad state: Interface type 'Age' which is nether an enum, nor a class, nor a mixin. This case is unknown, please report a bug.
package:mockito/src/builder.dart 1655:7                    _MockClassInfo._dummyValueImplementing
package:mockito/src/builder.dart 1549:12                   _MockClassInfo._dummyValue
package:mockito/src/builder.dart 1946:24                   _MockClassInfo._buildOverridingGetter
```

And I'm just seeing this, but there is a typo in the error message. It should be "neither" not "nether".

**Comment by yanok** [comment]
yes, extension types are not supported by mockito yet. Adding support should be straight forward, but not sure if I'll have time to add the support before the feature will be officially released.

**Comment by yanok** [comment]
The  version at HEAD should now cover the "method returns an extension type" case. We'll do a release soon.

**Comment by Rexios80** [comment]
@yanok what's the status of releasing this?

**Comment by renancaraujo** [comment]
This should be reopened until a. release is made.

**Comment by eernstg** [comment]
Extension types were released in Dart 3.3.0.

**Comment by denniskaselow** [comment]
Basic extension type support was introduced because of this issue, but has not yet been published on pub as there has been no release for almost a year. Support for extension types with generics does not yet exist, even on the main branch.

A code example for the not working case of an extension type with generics is in issue: https://github.com/dart-lang/mockito/issues/755

**Comment by eernstg** [comment]
Thanks! I asked around a bit to see if somebody can say more.

**Comment by renancaraujo** [comment]
What has stopped a release since February? Should package users expect one at all?
