### ISSUE TITLE
How are we supposed to use any with non null parameters?

### ISSUE THREAD

**Issue by takla21** [dart-lang/mockito#746]
I'm trying to write a test in which I'm trying to mock a method with a non-null parameter. However, I can't compile when I'm trying to use `any` for that non-null parameter.

![image](https://github.com/dart-lang/mockito/assets/17461593/b405737c-4af4-4bf8-baa5-313fc338cf1e)
![image](https://github.com/dart-lang/mockito/assets/17461593/384edc13-25e2-452c-a1ad-6d1e39f6ae87)

Is there something I'm missing or it's a bug?

**Comment by srawlins** [comment]
No parameter of a mock class's method's should be non-nullable. Can you show how you generated your mock class [with `@GenerateNiceMocks`](https://github.com/dart-lang/mockito?tab=readme-ov-file#lets-create-mocks)?

**Comment by takla21** [comment]
Ok I was a dummy here. I didn't read the generated mock part. Sorry for wasting your time
