### ISSUE TITLE
Handle method tear-off on mock

### ISSUE THREAD

**Issue by a14n** [dart-lang/mockito#82]
It would be great to be able to have

```dart
    test("should verify tear-off", () {
      final f = mock.methodWithoutArgs;
      f();
      verify(mock.methodWithoutArgs());
    });
```

## Use-case

I was refactoring some code from

```dart
for (var i in list)
  o.m(i);
```

to 

```dart
list.foreach(o.m);
```

This change triggers several test failures:

```
  NoSuchMethodError: The method 'call' was called on null.
  Receiver: null
  Tried calling: call()
```

**Comment by srawlins** [comment]
This has been decided for us by the Dart 2 language team. In general tearing off noSuchMethod calls is will not be supported in Dart 2. See #107 for more details.

**Comment by lrhn** [comment]
I'm not sure this issue matches #107. 
Rather, as I read it (and correct me if I'm wrong), this issue requests the behavior that will be in Dart 2.
The tear-off of a mock method "just works" - you can call the torn off method, and it works just as calling the original method.

Is the code here running in Dart 2 mode?

**Comment by matanlurey** [comment]
I don't think this is a Dart 2 issue - this just isn't supported.

The mechanics we use to detect the mock aren't compatible with NSM tear-offs.

**Comment by matanlurey** [comment]
Closing, it doesn't look like this is supported by Mockito and is unlikely to be possible.
