### ISSUE TITLE
Having a class use a mocked version of another one

### ISSUE THREAD

**Issue by Fandekasp** [dart-lang/mockito#87]
While learning about flutter testing and trying to write tests for my small application, I couldn't figure out how to mock a class used by another one.

Considering a stateful widget [ListScreen and its related ListScreenState](https://github.com/Fandekasp/grablunch/blob/master/lib/list.dart), the build methods returns an [AppBar with a localized text](https://github.com/Fandekasp/grablunch/blob/master/lib/list.dart#L48).

When trying to write a test for this widget
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

import 'package:grablunch/list.dart' show ListScreen;
import 'package:grablunch/localization.dart' show AppLocalizations;

class MockAppLocalizations extends Mock implements AppLocalizations {}

void main() {
  var localizations = new MockAppLocalizations();
  when(localizations.titleList).thenReturn("titleList");

  testWidgets('my first widget test', (WidgetTester tester) async {
    await tester.pumpWidget(
      new StatefulBuilder(
        builder: (BuildContext context, StateSetter setState) {
          return new ListScreen();
        },
      ),
    );
  });
}
```

flutter test will fail as follow:
```
➜ flutter test test/widget_test.dart
00:00 +0: - my first widget test
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building ListScreen(dirty, state: ListScreenState#496f0):
The getter 'titleList' was called on null.
Receiver: null
Tried calling: titleList
```

Makes sense since the translation is called out of `AppLocalizations.of(context).titleList)`, and the locales were defined in [the root widget](https://github.com/Fandekasp/grablunch/blob/master/lib/main.dart), not used for this test (trying to make a widget test, not an integration one).

How would you go about mocking AppLocalizations (or the context) on the ListScreen class? 
I tried
```
var testListScreen = new ListScreen();
testListScreen.context = new Mock();
```
and to return testListScreen instead, but the context not having a setter, I failed to suceed this way.

Kind of tough to figure things out, lacking some debugging foo up my sleeves. To be honest, I'm not even sure how to test this kind of app that heavily relies on external packages like the firebase ones.
Thanks for your help

**Comment by TedSander** [comment]
@cbracken can you point to someone who can help with flutter's mocking strategy. I'm not sure how /if flutter allows mock objects to be used instead of their 'real' equivalent.

**Comment by cbracken** [comment]
It looks like a mock is being created, but I don't see where `localizations` is being passed into the widget tree -- e.g. how is `ListScreen` getting a hold of it?

**Comment by matanlurey** [comment]
This issue is from November 2017 without response from the original author.

We can re-open if needed.
